### ISSUE TITLE
[DATE-PICKER] Re-selecting a date causes a styling issue

### ISSUE THREAD

**Issue by entity** [themesberg/flowbite#1]
Hi,

When selecting a date picker for the first time, it shows up correctly as you would expect like so;
![image](https://user-images.githubusercontent.com/47271716/139330994-0529479f-bcc8-4ffd-9133-ba499a82968b.png)

However, after re-selecting it (solely just clicking another date) it turns into weird random rounded date entries
<img width="478" alt="CleanShot 2021-10-28 at 9 31 12@2x" src="https://user-images.githubusercontent.com/47271716/139331078-1d475ed9-9e85-429e-8e91-7f9be422e89f.png">
.

**Comment by marchershey** [comment]
Hey @zoltanszogyenyi, is there an update on this? 

I am so excited and ready to make the switch but this is the only thing preventing me from bringing it up to the team. Thanks for any information!

**Comment by zoltanszogyenyi** [comment]
Hey @marchershey,

We'll look into it for the v1.4.0 update along with the release of new components, such as the carousel and spinner (loader) elements.

You can also [join our Discord Server](https://discord.com/invite/4eeurUVvTy) for chit-chat.

**Comment by zoltanszogyenyi** [comment]
Hey @heychazza,

Fixed this issue in v1.4.6.

https://flowbite.com/docs/plugins/datepicker/#date-range-picker
