### ISSUE TITLE
Datepicker: dependencies and issues

### ISSUE THREAD

**Issue by lrusso96** [themesberg/flowbite#100]
Starting from 6b8af5d6940f22b58119e6a735cdbe36c12f1bb5 the npm package is simply `flowbite`, but the [datepicker plugin](https://github.com/themesberg/tailwind-datepicker) still relies on the old `themesberg/flowbite` package.

I know that this issue is related to the plugin rather than this repo, but the issues on that repository are disabled: I suggest you to enable them in the settings, and move this issue (and the others related to the plugin) there.

**Comment by zoltanszogyenyi** [comment]
Hey @lrusso96,

I'll look into the matter.

**Comment by zoltanszogyenyi** [comment]
@lrusso96 renamed to `flowbite-datepicker`starting v1.4.6.
