### ISSUE TITLE
Flowbite blocks seems to constantly throw routing error & navigation very slow

### ISSUE THREAD

**Issue by TechAkayy** [themesberg/flowbite#1000]
Navigating the blocks categories is really slow, probably related to this routing error. 

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/6c1f3083-b761-4282-8e44-6cf6f179c3bf">

1. Go to 'https://flowbite.com/blocks/'
2. Navigate to 'https://flowbite.com/blocks/marketing/hero/'
3. Check for error in the console.

 - OS: Mac OSX
 - Browser: Chrome Version 131.0.6778.86 (Official Build) (arm64)

**Comment by zoltanszogyenyi** [comment]
Hey @TechAkayy - will check this internally, thanks!

**Comment by TechAkayy** [comment]
Just tested and worked like a charm. Thanks @zoltanszogyenyi :-)
