### ISSUE TITLE
i18n for the datepicker

### ISSUE THREAD

**Issue by alarbada** [themesberg/flowbite#105]
Is i18n developed for your datepicker? I cannot see it that option [at the docs](https://flowbite.com/docs/plugins/datepicker)

**Comment by erenergul** [comment]
Did you find any solution to translate datepicker ?

**Comment by not-rusty** [comment]
Well, I went with this instead:
https://air-datepicker.com/

**Comment by dzcpy** [comment]
i18n is really needed for the date picker

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

There's actually support for this, but I'll have to properly document it. Will be added for `v1.6.0`.

**Comment by cotufaloschiflones** [comment]
I have tried multiple approachs and it was impossible for me too

**Comment by cotufaloschiflones** [comment]
I gave up, I'm migrating to this: https://mymth.github.io/vanillajs-datepicker/#/?id=quick-start

**Comment by 0Chan-smc** [comment]
@zoltanszogyenyi Any progress?

**Comment by zoltanszogyenyi** [comment]
Working on it for the next version since I'm adding it to the Instance Manager.

**Comment by zoltanszogyenyi** [comment]
Until we provide docs on this, please do:

1. Install the flowbite-datepicker plugin
2. Configure the languages via this guide: https://mymth.github.io/vanillajs-datepicker/#/i18n

Cheers,
Zoltan
