### ISSUE TITLE
sidebar.js bug in react

### ISSUE THREAD

**Issue by goodlythink** [themesberg/flowbite#106]
i import sidebar.js in index.js
it error on start
<img width="909" alt="Screen Shot 2565-03-10 at 14 22 36" src="https://user-images.githubusercontent.com/12431734/157609735-0ed17718-f905-4025-b4f4-d6918ac3b56a.png">

**Comment by volp99** [comment]
Hello @goodlythink 
Can you share the **file component** and **tailwind.config.js**?
