### ISSUE TITLE
Multi items in carousel

### ISSUE THREAD

**Issue by Nasirinezhad** [themesberg/flowbite#112]
I need a multi item carousel but I don't like to add another package to my project
so I forked this repo and tried to handle my problem, it's work but has some issues especially with responsive
in what I made total items must be determined in data attribute but it will be so better if it justify items automatically
I hope I have get the point across
tnx

**Comment by zoltanszogyenyi** [comment]
Hey @Nasirinezhad,

Please check out the v1.4.0 update where we decoupled the data attributes logic from the Carousel object.
