### ISSUE TITLE
Reinitiate close event for dynamically loaded modal

### ISSUE THREAD

**Issue by anton-ecom** [themesberg/flowbite#115]
Useful feature when you want to reuse one modal, loading only content. Thank you.

**Comment by zoltanszogyenyi** [comment]
Hey @anton-ecom,

We're actually refactoring the core JS using objects, methods, and callback functions.

I believe this issue will be solved once v1.4.0 is out next week.

**Comment by Kellokes** [comment]
@zoltanszogyenyi this feature for create dynamic content for already exist?
