### ISSUE TITLE
Pass relevant object references in the tabs.js onShow callback 

### ISSUE THREAD

**Issue by dpnishant** [themesberg/flowbite#117]
IMHO Changing https://github.com/themesberg/flowbite/blob/main/src/components/tabs.js#L74 to the following
```js
this._options.onShow(this, tab, id)
```
can be really helpful for dynamic manipulation of the active tab elements or any other use-case as suitable. I created this as a feature request as I'm unable to send a PR due to merge conflicts during upstream fetch.

**Comment by zoltanszogyenyi** [comment]
Hey @dpnishant,

Thanks for the suggestion, it makes sense.

I'm thinking we can release this for v1.4.2 along with the other callback functions.

I think that was a GitHub bug by the way. I think it should work now.

**Comment by zoltanszogyenyi** [comment]
@dpnishant solved in v1.4.2

https://flowbite.com/docs/getting-started/changelog/
