### ISSUE TITLE
how to add flowbite datepicker in angular application

### ISSUE THREAD

**Issue by sunysunysuny** [themesberg/flowbite#120]
![datepicker](https://user-images.githubusercontent.com/27955832/159926833-d8cabcae-b4a5-4c74-92ee-58bc956ca2cd.png)

I am following the steps as suggest in documentation

npm i @themesberg/tailwind-datepicker --save

As I am importing it into my component file it displaying below error

import Datepicker from '@themesberg/tailwind-datepicker/Datepicker';

Cannot find module '@themesberg/tailwind-datepicker/Datepicker' or its corresponding type declarations.

Let me know where I am making mistakes

Thanks

**Comment by volp99** [comment]
Hi @sunysunysuny 
Have you try to import the Datepicker from th CDN? You can find the link [here](https://flowbite.com/docs/plugins/datepicker/)

But it looks like Flowbite doesn't support types 🤔

**Comment by BariqDharmawan** [comment]
I've same problem. I'm using vanilla flowbite

**Comment by leomunizq** [comment]
nothing yet ?

**Comment by heloufir** [comment]
Using the datepicker from the Flowbite docs https://flowbite.com/docs/plugins/datepicker/#javascript
I got the same issue, the `import Datepicker from 'flowbite-datepicker/Datepicker';` was not working.

So what I did (_I don't think it's the perfect way to do it, but it works_): 

Add this to the scripts section of `angular.json` file:

`node_modules/flowbite-datepicker/dist/js/datepicker-full.min.js`

<img width="668" alt="image" src="https://github.com/themesberg/flowbite/assets/6197875/a154fba7-60e7-47d9-bf6a-d2ce922fcf2c">

Then to use it in my component I declared a var named `Datepicker`: 

`declare var Datepicker: any;`

Then use it simply like in the docs.

<img width="555" alt="image" src="https://github.com/themesberg/flowbite/assets/6197875/4ffa0c30-5361-4ca1-b6e7-057f61d49797">

**Comment by nieuwie** [comment]
Amazing, your solution works! Thank you so much!

**Comment by pachoGit** [comment]
@heloufir works fine for "Datepicker" but does NOT work for "DateRangePicker"
```ts
declare var Datepicker: any;
declare var DateRangePicker: any;
```
```ts
export class DateRangeSelectComponent implements AfterViewInit {
  @ViewChild('dateField') date!: ElementRef;

  ngAfterViewInit(): void {
    new Datepicker(this.date.nativeElement, {}); // Works fine
    new DateRangePicker(this.date.nativeElement, {}); // Not works!
}
```

**Comment by cirinoe** [comment]
@pachoGit for DateRangePicker the nativeElement must be a container of two inputs otherwise it doesn't work

**Comment by kidskidspacana** [comment]
hello everyone. i did follow your instructions but i got this error: 'ReferenceError: Datepicker is not defined'
can someone help me here

**Comment by kidskidspacana** [comment]
> @heloufir works fine for "Datepicker" but does NOT work for "DateRangePicker"
> 
> ```ts
> declare var Datepicker: any;
> declare var DateRangePicker: any;
> ```
> 
> ```ts
> export class DateRangeSelectComponent implements AfterViewInit {
>   @ViewChild('dateField') date!: ElementRef;
> 
>   ngAfterViewInit(): void {
>     new Datepicker(this.date.nativeElement, {}); // Works fine
>     new DateRangePicker(this.date.nativeElement, {}); // Not works!
> }
> ```

i did follow this but i got an error 'ReferenceError: Datepicker is not defined'

**Comment by heloufir** [comment]
> > @heloufir works fine for "Datepicker" but does NOT work for "DateRangePicker"
> > ```ts
> > declare var Datepicker: any;
> > declare var DateRangePicker: any;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > export class DateRangeSelectComponent implements AfterViewInit {
> >   @ViewChild('dateField') date!: ElementRef;
> > 
> >   ngAfterViewInit(): void {
> >     new Datepicker(this.date.nativeElement, {}); // Works fine
> >     new DateRangePicker(this.date.nativeElement, {}); // Not works!
> > }
> > ```
> 
> i did follow this but i got an error 'ReferenceError: Datepicker is not defined'

Hi,

Just got the same issue on a new project, and resolved it following these steps:

- install Datepicker dependency: `npm install flowbite-datepicker --save`
- Add javascript file to you `angular.json` file:
```json
"scripts": [
  "...",
  "node_modules/flowbite-datepicker/dist/js/datepicker.js"
]
```
- add the Datepicker reference into your component:
```javascript
declare var Datepicker: any;
```
- then use the Datepicker object:
```javascript
new Datepicker(element, {});
```

**Comment by JuankAnacona** [comment]
> @heloufir works fine for "Datepicker" but does NOT work for "DateRangePicker"
> 
> ```ts
> declare var Datepicker: any;
> declare var DateRangePicker: any;
> ```
> 
> ```ts
> export class DateRangeSelectComponent implements AfterViewInit {
>   @ViewChild('dateField') date!: ElementRef;
> 
>   ngAfterViewInit(): void {
>     new Datepicker(this.date.nativeElement, {}); // Works fine
>     new DateRangePicker(this.date.nativeElement, {}); // Not works!
> }
> ```
Nice fix, thanks !!

**Comment by marcoariasm** [comment]
And where do I call the method initDatePickerElement?

**Comment by Joaomarcos7** [comment]
when i use in my component "declare var Datepicker: any;" I am receiving the following error : ERROR ReferenceError: Datepicker is not defined. Can someone help me out here ?

**Comment by byteAr** [comment]
Deben iniciar el método initDatePicker() en:
 ngAfterViewInit(): void {
    this.initDatePicker();
  }

**Comment by Rubanrubi** [comment]
use this way daterangepicker 100% working method

npm install flowbite-datepicker --save

create flowbite-datepicker.d.ts file inside src directory

declare module 'flowbite-datepicker/DateRangePicker' {
  const DateRangePicker: any;
  export default DateRangePicker;
}

in angular.json file scripts array

 "node_modules/flowbite-datepicker/dist/js/datepicker-full.min.js"
 
 Component -ts file
 // import the abstract type which we created for the module
 
 import DateRangePicker from 'flowbite-datepicker/DateRangePicker';

 
  ngAfterViewInit(): void {
      const dateRangePickerEl = document.getElementById('date-rangepicker');
      new DateRangePicker(dateRangePickerEl, {
          // options
      });
  }
 
 In HTML
 
 <div id="date-rangepicker" class="flex items-center">
        <div class="relative">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
              fill="currentColor" viewBox="0 0 20 20">
              <path
                d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
            </svg>
          </div>
          <input name="start" type="text"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Select date start">
        </div>
        <span class="mx-4 text-gray-500">to</span>
        <div class="relative">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
              fill="currentColor" viewBox="0 0 20 20">
              <path
                d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
            </svg>
          </div>
          <input name="end" type="text"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Select date end">
        </div>
      </div>
      
      That's it @heloufir @sunysunysuny

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

Since `v2.4.1` the datepicker is a core component of Flowbite so it will work within Angular:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour

There's this Angular starter repo with Flowbite and Tailwind configured and the datepicker added:

https://github.com/themesberg/tailwind-angular-starter

Cheers,
Zoltan

**Comment by radoman93** [comment]
While the picker works, The input value (Form control field) does not reflect the picked date. Essentially, it's not working as intended.
