### ISSUE TITLE
detect modal is open (javascript)

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#124]
can i check modal (by id) is open or not by javascript?

**Comment by zoltanszogyenyi** [comment]
Hey @KinG-InFeT,

You can use the [callback functions](https://flowbite.com/docs/components/modal/#javascript-behaviour) `onOpen` and `onHide` and store it yourself.

**Comment by KinG-InFeT** [comment]
> Hey @KinG-InFeT,
> 
> You can use the [callback functions](https://flowbite.com/docs/components/modal/#javascript-behaviour) `onShow` and `onHide` and store it yourself.

ok thanks, it would be convenient not to store a lot of information, but to have a simple method to check if the modal is open or not (even a simple check on the hiddens class is present or not)

**Comment by KinG-InFeT** [comment]
any update?

**Comment by zoltanszogyenyi** [comment]
This has been addressed and will be released today for `v1.5.4`.
