### ISSUE TITLE
flowbite.js.map not generated from webpack

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#129]
**Describe the bug**
the file flowbite.js.map not generated from webpack (laravel installation)

**Additional context**
Laravel 9
Flowbite 1.4.1
webpack (laravel mix)

**Comment by zoltanszogyenyi** [comment]
Hey @KinG-InFeT,

I'll check this for the v1.5 update.

Thanks!

**Comment by zoltanszogyenyi** [comment]
Hello @KinG-InFeT,

Since `v1.6.0` the 'flowbite.js.map' is being generated: https://unpkg.com/flowbite@1.6.0/dist/flowbite.js.map

Cheers,
Zoltan
