### ISSUE TITLE
Not a valid ES module

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#130]
You might already know this, but just for your information.

I get the following error when I start a SvelteKit server.

> flowbite doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/147320/162532351-95d284cc-2fd9-409f-9096-9e34dbfdeb98.png">

**Comment by estudiooka** [comment]
with vue as well

**Comment by ymc9** [comment]
Same here in a svelte-kit project

**Comment by eric-naguras** [comment]
I hope this will be solved. Not too fond of warnings.
But I like flowbite, thanks for creating.

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

I'll tackle this for the 1.5 version. We'll release some new components including drawer, stepper, skeleton and popover.

**Comment by samuelstroschein** [comment]
The issue persists with v1.5 of flowbite.

**Comment by zoltanszogyenyi** [comment]
Hello @shinokada @ymc9 @eric-naguras @samuelstroschein,

I've updated Flowbite to `v1.5.5` and the default entry point is now the `src/flowbite.js` file which is ES compatible.

Can you please upgrade and check if still persists?

Thanks!

**Comment by shinokada** [comment]
I have flowbite v1.5.5 and it still gives the same warning.

Can you add `"type": "module",` to package.json?

**Comment by zoltanszogyenyi** [comment]
Hello @shinokada,

I have launched `v1.6.0` and rebuilt the distribution packages and I have built CJS, ESM, and UMD and also the package.json file.

Can you please check it out now?

Cheers,
Zoltan

**Comment by shinokada** [comment]
@zoltanszogyenyi Yes, it works without warnings.

**Comment by zoltanszogyenyi** [comment]
Wohoo @shinokada 🥳
