### ISSUE TITLE
Interactive components are not interactive until refresh

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite#135]
**Describe the bug**
Interactive components (I've identified `Dropdown`, `Toast`, `Tooltip`) are only interactive on the first page visited, before a browser refresh.

**To Reproduce**
Let's say I have the following pages:

- `/: Has a Tooltip`
- `/hello: Has no interactive Flowbite components`

1. Navigate to `/hello`
2. Navigate to `/`
3. The `Tooltip` cannot be closed (it is not interactive)

Alternatively,

1. Navigate to `/`
2. The `Tooltip` *is* interactive
3. Navigate to `/hello`
4. Navigate back to `/`
5. The `Tooltip` is not interactive

**Expected behavior**
Interactive components will respond to user input regardless of whether the user has changed pages without manually refreshing the browser (in other words, clicked a `react-router` `<Link/>`).

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: iOS, Linux, macOS
 - Browser: Chromium, Edge, Firefox
 - Version: (latest)

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPhone 11
 - OS: (latest)
 - Browser: Safari
 - Version: (latest)

**Additional context**
I am using [Remix](https://remix.run). `Remix` bundles with `esbuild`. I import `flowbite` in [`entry.client.tsx`](https://remix.run/docs/en/v1/api/conventions#entryclienttsx).

**Comment by LevaniVashadze** [comment]
I have the same issue and i don't want to use flowbite-react

**Comment by zoltanszogyenyi** [comment]
Hey peeps,

We will always recommend [Flowbite React](https://github.com/themesberg/flowbite-react) for those who want to use Flowbite components with React.

On the other hand, after the `v1.6.0` update with TypeScript we'll show how you can import the components and initialise components programatically with React/Next.js.

**Comment by LevaniVashadze** [comment]
```js
const ge = () => {
  return (
    <img
      className="h-3.5 w-3.5 mr-2"
      src="../../static/images/ge.png"
      alt="georgia-flag"
    />
  );
};

const de = () => {
  return (
    <img
      className="h-3.5 w-3.5 mr-2"
      src="../../static/images/de.png"
      alt="germany-flag"
    />
  );
};

const en = () => {
  return (
    <img
      className="h-3.5 w-3.5 mr-2"
      src="../../static/images/en.png"
      alt="england-flag"
    />
  );
};

<Dropdown
  label={
    language === "en" ? (
      <Dropdown.Item icon={en}>English</Dropdown.Item>
    ) : language === "de" ? (
      <Dropdown.Item icon={de}>Deutsch</Dropdown.Item>
    ) : (
      <Dropdown.Item icon={ge}>ქართული</Dropdown.Item>
    )
  }
  inline={true}
  arrowIcon={false}
>
  <Dropdown.Item icon={en} onClick={() => setLanguage("en")}>
    English
  </Dropdown.Item>
  <Dropdown.Item icon={de} onClick={() => setLanguage("de")}>
    Deutsch
  </Dropdown.Item>
  <Dropdown.Item icon={ge} onClick={() => setLanguage("ge")}>
    ქართული
  </Dropdown.Item>
</Dropdown>
```

![image](https://user-images.githubusercontent.com/100613979/209833849-3a3f9320-bdff-498b-933e-58edf6989a95.png)
all this to achieve just this, that's why I don't like the react library. Very limited customizability and sometimes hard to find things in the docs. Ended up still using the flowbite-react library.
