### ISSUE TITLE
Accordion component is causing javascript error: this._options.onToggle is not a function 

### ISSUE THREAD

**Issue by rebekahocampo7** [themesberg/flowbite#138]
**Describe the bug**
Accordion component is causing javascript error every time you open or close any accordion elements.

Error:

Uncaught TypeError: this._options.onToggle is not a function
    at Accordion.toggle (flowbite.js?v=1.4.1a:18:15)
    at HTMLButtonElement.<anonymous> (flowbite.js?v=1.4.1a:15:58)
toggle  @   flowbite.js?v=1.4.1a:18
(anonymous) @   flowbite.js?v=1.4.1a:15

**To Reproduce**
1. Go to https://flowbite.com/docs/components/accordion/ in Chrome
2. Open Developer tools
3. View Javascript console
4. Click on the Default accordion first element "What is Flowbite?"
5. See error in Javascript console
6. Keep clicking on any of the accordions on the page and you will see the same error each time.

**Expected behavior**
No javascript errors.

**Screenshots**
<img width="1339" alt="Screen Shot 2022-04-20 at 10 09 49 AM" src="https://user-images.githubusercontent.com/75705849/164264759-be9b3978-8240-43c3-ba30-749e5421c02d.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 99.0.4844.83

**Smartphone (please complete the following information):**

**Additional context**
The problem is caused because onToggle is not in the "Default" options at the very top of /src/components/accordion.js

**Comment by Xac** [comment]
+1 having the same issue.

**Comment by zoltanszogyenyi** [comment]
@Xac @rebekahocampo7 

thanks for reporting, will fix in v1.4.4

**Comment by zoltanszogyenyi** [comment]
Fixed in v1.4.4.
