### ISSUE TITLE
Flowbite-injected CSS causes floating dropdown arrows in scrollable <select> elements

### ISSUE THREAD

**Issue by aaronhendry** [themesberg/flowbite#139]
When adding a scrollable select box, such as the following:

```
<select size=2 class="appearance-none">
  <option>2016</option>
  <option>2017</option>
  <option>2018</option>
</select>
```

a floating arrow appears in the middle of the select box. This should not happen. The only way to get rid of it, I believe, is to inject my own CSS overwriting this. 

This can be easily reproduced on tailwind play: https://play.tailwindcss.com/sajBj88nsh

**Comment by zoltanszogyenyi** [comment]
@aaronhendry thanks for the report, this has been fixed with this commit (https://github.com/themesberg/flowbite/compare/main...v1.5.6) and will be added in the next release.
