### ISSUE TITLE
Date picker - date rangepicker - week start of monday.

### ISSUE THREAD

**Issue by peroxovy** [themesberg/flowbite#140]
### Discussed in https://github.com/themesberg/flowbite/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **peroxovy** April  8, 2022</sup>
Hello, I want to ask if there's possibility to change the starting day of week in datepicker from flowbite?
I did several "tests" but any of option don't work. In the documetation I didn't see the option for changing starting day of week to Monday f.e. 

Anyone can help?</div>

**Comment by cotufaloschiflones** [comment]
you should pass to the constructor this options

`new Datepicker(element, { weekStart: 1 })`

**Comment by JustDoItSascha** [comment]
Is this option still valid? Because it's not documented...

**Comment by JustDoItSascha** [comment]
@zoltanszogyenyi Any updates on this? I don't know how this could be considered done when I don't see the weekstart option anywhere? Am I missing something?
