### ISSUE TITLE
Dark/Light component toggle doesn't work as intended while using Dark mode

### ISSUE THREAD

**Issue by PhaxeNor** [themesberg/flowbite#145]
**Describe the bug**
While using dark mode, the component examples that have dark/light toggle doesn't change when switching between them.

**To Reproduce**
1. Set the website mode to Dark mode
2. Go to any component that has a Dark/Light toggle button
3. Click on the Dark/Light toggle button to toggle between dark and light.
4. See that it just stays in dark mode, even when the Light mode has been toggled.

**Expected behavior**
See the component being toggled between the dark and light mode

**Video**

https://user-images.githubusercontent.com/323222/167036347-04302694-677c-4ef9-8dda-c019bc987ad7.mov

**Desktop (please complete the following information):**
 - OS: macOS / Windows
 - Browser: Firefox
 - Version: 99.0.1

**Comment by zoltanszogyenyi** [comment]
Hello @PhaxeNor,

Thanks for the bug report. We're actually aware of this and right now we can make it work only if the code example is loaded inside an `<iframe` because the dark mode is applied by adding the `.dark` class, whereas you can't add a `.light` class right now.

Is this something that prevents you from developing with Flowbite or it's more like a small glitch in your view?

**Comment by PhaxeNor** [comment]
Thanks for the reply @zoltanszogyenyi 

It's not a issue for me, just bug reporting what I found :)

**Comment by DIWAKARKASHYAP** [comment]
@PhaxeNor 

i fork this repository and open code in VS code and i try to run this on localhost  for last 3 days
so,
brother can you help me to run this website on local host using VS code

**Comment by zoltanszogyenyi** [comment]
Hey @PhaxeNor @DIWAKARKASHYAP,

I fixed this in the `docs-layout` branch by using an iframe instead of the code directly.

Here's a preview of the functionality before the deployment:

https://user-images.githubusercontent.com/8052108/178486451-9854da0c-fd07-4f26-9cfa-74762b3ca1ba.mov

**Comment by zoltanszogyenyi** [comment]
Deployed.

**Comment by QuixThe2nd** [comment]
I face the same issue when using the code shown here: https://flowbite.com/docs/customize/dark-mode/

**Comment by DIWAKARKASHYAP** [comment]
@zoltanszogyenyi  
Great
