### ISSUE TITLE
Build a new component page for checkboxes with multiple layouts and styles

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite#15]

**Comment by aggmoulik** [comment]
Hey @zoltanszogyenyi This is for creating the documentation page for the respective component. Can I work on the issue ?

**Comment by zoltanszogyenyi** [comment]
Hey @aggmoulik,

Sure thing. We're thinking about creating states (ie. disabled, active) and positioning (vertical, horizontal) for the checkbox elements similar to what Bootstrap 5 has:

https://getbootstrap.com/docs/5.1/forms/checks-radios/

We're also thinking about creating addition checkbox group styles similar to this:

https://tailwindui.com/components/application-ui/forms/checkboxes (with additional information and grouped selection).

You can pull the https://github.com/themesberg/flowbite/tree/v1.1.2 branch and create a pull request into this branch and work on the existing `checkboxes.md` file that is created.

Feel free to join our Discord channel to discuss via chat as well.
