### ISSUE TITLE
Error: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#150]
**Describe the bug**

Error message:

> [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
> 1  |  /* Write your global styles here, in PostCSS syntax */
> 2  |  @tailwind base;
>    |   ^
> 3  |  @tailwind components;
> 4  |  @tailwind utilities; (x6)

**To Reproduce**

```
npm init svelte@next demo 
cd demo
pnpm install
npx svelte-add@latest tailwindcss // no error here
```

Update tailwind.config.cjs

```
const config = {
	content: ['./src/**/*.{html,js,svelte,ts}'],

	theme: {
		extend: {}
	},

	plugins: [
    require('flowbite/plugin')
  ],
  darkMode: 'class',
};

module.exports = config;
```

Installing flowbite:

```
pnpm i -D flowbite
pnpm run dev // error
```

**Expected behavior**

No error.

**Screenshots**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/147320/168005393-970eb698-89ae-4366-b2cf-76b260207efb.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1

Similar to [this error](https://github.com/tailwindlabs/tailwindcss/issues/8256) and [this issue](https://github.com/tailwindlabs/tailwindcss/issues/8277)

Do you use tailwind/forms?

**Comment by shinokada** [comment]
It was [autoprefixer bug](https://github.com/tailwindlabs/tailwindcss/issues/8250) and using [10.4.5 fixed the problem](https://github.com/BLSQ/accessmod-app/commit/0e0ed2d9929fffaecb96e40bbe6657c0e0c5bc00).

**Comment by desprit** [comment]
@shinokada I'm using the latest version of flowbite (1.4.5) and the latest version of tailwind (3.0.24). How do I silence that warning message, please?

**Comment by shinokada** [comment]
@desprit You need to install autoprefixer@10.4.5

```
npm i -D autoprefixer@10.4.5
```

**Comment by sgehrman** [comment]
not fixed for me.
