### ISSUE TITLE
Code differentiate with npm package

### ISSUE THREAD

**Issue by abdullrahman02000** [themesberg/flowbite#154]
When commit "fix: replace color-adjust by print-color-adjust" was done
https://github.com/themesberg/flowbite/commit/a849bb580f8e2cc86022c8f76a509880b645b72d
I downloaded latest version 1.4.5 and I get warning from vite server that I have to use **print-color-adjust** instead of **color-adjust**
When I opened the effected file **plugin.js** I found it using old version with **color-adjust**

**Comment by zoltanszogyenyi** [comment]
@abdullrahman02000 fixed in v1.4.6 and v1.4.7 respectively.
