### ISSUE TITLE
Drawer (Offcanvas) support

### ISSUE THREAD

**Issue by alvinkonda** [themesberg/flowbite#156]
Example:
https://getbootstrap.com/docs/5.1/components/offcanvas/

I think this is a must-have component, but if you have any workarounds for this please let me know.

**Comment by zoltanszogyenyi** [comment]
Hey @alvinkonda,

We'll get this done in the next version by creating a "Drawer" component.

**Comment by zoltanszogyenyi** [comment]
Released with v1.5.0.

Docs: [Tailwind CSS Drawer - Flowbite](https://flowbite.com/docs/components/drawer/)

**Comment by dc-jahanzaib** [comment]
can anyone tell me how to default hide drawer,  i use `aria-hidden="true"` but it is not working

**Comment by siwonKH** [comment]
> can anyone tell me how to default hide drawer, i use `aria-hidden="true"` but it is not working

This is my solution without using flowbite Drawer API.
idk if this is a proper way, but at least it works.

(This is a part of the flowbite bottom-drawer example from [here](https://flowbite.com/docs/components/drawer/#bottom-drawer))
```html
<div id="drawer-bottom-example" class="... transform-none" tabindex="-1" aria-labelledby="drawer-bottom-label">
  <!-- drawer contents -->
</div>
```
Solution: You just simply change `transform-none` to `translate-y-full`

For other type of drawer.
- Left drawer `-translate-x-full`
- Right drawer `translate-x-full`
- Top drawer `-translate-y-full`
- Bottom drawer `translate-y-full`
