### ISSUE TITLE
Fix dist/flowbite.js to not use arrow function

### ISSUE THREAD

**Issue by ioanacristinamarinescu** [themesberg/flowbite#159]
**Describe the bug**
On IE11 the dropdown does not work because of the use of arrow function.

**To Reproduce**
1. Go to IE11 https://flowbite.com/docs/components/dropdowns/
2. Open web console
3. See error

**Expected behavior**
Dropdown list should appear

**Screenshot**
![Screenshot_2022-05-23_18-06-29](https://user-images.githubusercontent.com/4679587/169850060-87ddb54b-3f70-4e0e-ba58-9fec77d7779c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser IE11
 - Version 1.4.5

**Additional context**
On my project I updated the first line in `flowbite.js` 
```
/******/ (() => { // webpackBootstrap
```
with 
```
/******/ (function() { // webpackBootstrap
```

**Comment by adiroiban** [comment]
The main goal for this is to have IE11 support.

I am not sure if the source files have support for IE11 ... or if the projects even want to support IE11.

For `webpack.config.js`, a quick fix is to use:

```js
module.exports = {
    target: ["web", "es5"]
}
```

**Comment by zoltanszogyenyi** [comment]
Hey @ioanacristinamarinescu  @adiroiban,

I'll look into this for the next version. Thank you!

@adiroiban: you can open a PR if you want to and I'll take a look at it.

**Comment by adiroiban** [comment]
Sure. I will create the PR.

**Comment by adiroiban** [comment]
PR https://github.com/themesberg/flowbite/pull/163

Many thanks for this nice project :)

**Comment by zoltanszogyenyi** [comment]
Hey peeps,

The arrow function is no longer used for the dist files as of `v1.6.0`.

Please check out this resource for confirmation:

```
https://unpkg.com/flowbite@1.6.0/dist/flowbite.min.js
```

Cheers,
Zoltan
