### ISSUE TITLE
Feat: Add visual indicator of disabled dates outside min and max range in datepicker plugin

### ISSUE THREAD

**Issue by yoelpc4** [themesberg/flowbite#165]
**Is your feature request related to a problem? Please describe.**
Hi there, I use flowbite datepicker in my project and already set the minDate and maxDate on options at the 2nd argument of the new Datepicker. After that, I headed to the browser and tried my app. It turns out the dates outside the min-max range are not disabled visually only unclickable, which means the function is working but the interface is not.

**Describe the solution you'd like**
I suggest adding this visual indicator of disabled dates outside the min and max range in order to improve UX quality.

**Additional context**
In addition to my feature request, you can check out the bootstrap datepicker config links below
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#startdate
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#enddate

**Comment by tanami20** [comment]
Was this resolved?

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

I've added the visual indicator via this commit: https://github.com/themesberg/flowbite-datepicker/commit/802fe4c8d43dc67f931735a840acd3b306691bff

Will soon be updated on NPM.

<img width="394" alt="Screenshot 2024-06-11 at 11 36 51" src="https://github.com/themesberg/flowbite/assets/8052108/fbd2ec7d-7f44-4506-89b9-5d932710302a">

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @yoelpc4, @tanami20,

This is now released with `v2.4.1`:

https://flowbite.com/docs/components/datepicker/#max-and-min-dates

Cheers,
Zoltan
