### ISSUE TITLE
sha512 checksum React App

### ISSUE THREAD

**Issue by iamkaarp** [themesberg/flowbite#169]
**Describe the bug**
When running npm ci on both dev and production machine I get
npm ERR!
code EINTEGRITY
ERR! sha512-3hN7NagrayvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg== integrity checksum failed when using sha512: wanted sha512-3hN7NagrayvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg== but got sha512-3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==. (7442 bytes)

**To Reproduce**
1. npm install flowbite flowbite-react
2. npm ci

**Expected behavior**
successfully built

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  node v14.18.1 npm v6.14.15

**Build server (please complete the following information):**
 - OS: Probably AWS Linux
 - Docker

**Comment by zoltanszogyenyi** [comment]
Hello @iamkaarp,

Please refer to the [Flowbite React](https://github.com/themesberg/flowbite-react) repository for React usage.
