### ISSUE TITLE
What happened to the Nextjs starter kit? It was created weeks ago but now i couldnt find it anymore

### ISSUE THREAD

**Issue by xiaolin911211** [themesberg/flowbite#171]
What happened to the Nextjs starter kit? It was created weeks ago but now i couldnt find it anymore

**Comment by zoltanszogyenyi** [comment]
Hey @xiaolin911211,

Please check out this repository: https://github.com/tulupinc/flowbite-next-starter

We'll later add it to the main library as an integration guide.
