### ISSUE TITLE
About npm `import 'flowbite'` related issues

### ISSUE THREAD

**Issue by daxiongYang** [themesberg/flowbite#182]
When importing the js library through npm `import 'flowbite'`.

1. Is it optional? Like: `import { Modal } form 'flowbite'` . Although, I can
````
import Accordion from 'flowbite/src/components/accordion'
import Collapse from 'flowbite/src/components/collapse'
import Carousel from 'flowbite/src/components/carousel'
import Dismiss from 'flowbite/src/components/dismiss'
import Dropdown from 'flowbite/src/components/dropdown'
import Modal from 'flowbite/src/components/modal'
import Tabs from 'flowbite/src/components/tabs'
import Tooltip from 'flowbite/src/components/tooltip'
````
But I feel so innocent! !

2. Can you provide a namespace instead of directly `window.Modal = Modal;` to bind the Class to the window object?

**Comment by zoltanszogyenyi** [comment]
Hello @daxiongYang,

Since `v1.5.5` you can now import `flowbite` and then use something like `flowbite.Modal` instead of the window object.

Cheers,
Zoltan
