### ISSUE TITLE
Problem with sidebar not working

### ISSUE THREAD

**Issue by spacerobotTR** [themesberg/flowbite#185]
I went through the installation for a rails 7 project. Everything seems to be working fine, but when trying to duplicate the pro version dashboard page, the sidebar menu does not work. All other javascript works fine. When I set the browser to mobile mode the sidebar disappears, but the toggle bars do not do anything when clicked. Is there something I need to do or configure for this that is not in the flowbite.js file?

**Comment by zoltanszogyenyi** [comment]
Hey @spacerobotTR,

Are you sure the JavaScript is correctly included?

With the pro version you have some additional JS for the charts and the sidebar toggle to include for them to work.

**Comment by spacerobotTR** [comment]
Yes sorry. I thought it was all included with the flowbite js. I ended up working in the sidebar javascript, and made some changes for turbo/hotwire and got it to work!
