### ISSUE TITLE
Carousel infinite slide interval 

### ISSUE THREAD

**Issue by DamienJolly** [themesberg/flowbite#186]
It would be really good for the infinite carousel slider to have configurable interval speed. 
Maybe even with a custom attribute `data-carousel-interval="2000ms"`

**Comment by bmartus** [comment]
It looks like this works .. I added a 7 second interval to my outer wrapper and it is cycling thru them every 7 seconds.

```
<div class="relative" data-carousel="slide" data-carousel-interval="7000" id="slide">
 .. snip ..
</div>
```

**Comment by phadaphunk** [comment]
This would have been amazing in the .. doc 👁️ 👁️

**Comment by eugenefvdm** [comment]
@phadaphunk I've created a pull request and updated the docs:
https://github.com/themesberg/flowbite/pull/1079
Hopefully @zoltanszogyenyi will find it in order.
