### ISSUE TITLE
modal not working

### ISSUE THREAD

**Issue by WenderRocha** [themesberg/flowbite#197]
Modal not working in laravel with vite

**Comment by zoltanszogyenyi** [comment]
Hello @WenderRocha,

Please give more context and a code example for better debugging and reproduction.

Thanks!

**Comment by normandanielmq** [comment]
Same here, parameter userOptions is expected for a modal so it crashes on undefined.

**Comment by curtgrimes** [comment]
I think this is related to #231. See https://github.com/themesberg/flowbite/issues/231#issuecomment-1288152356
