### ISSUE TITLE
Commitizen dependency abandoned, has critical security bug

### ISSUE THREAD

**Issue by jshnaidman** [themesberg/flowbite#218]
Hi. This project has a dependency on commitizen which in turn has a dependency on minimist 1.2.5. Unfortunately minimist 1.2.5 has a critical security vulnerability: https://github.com/advisories/GHSA-xvch-5gv4-984h

Either the minimist dependency should be overridden or there should be a migration to an active commitizen fork, see https://github.com/commitizen/cz-cli/issues/914#issuecomment-1131383383

**Comment by kdmcguire** [comment]
Commitizen releases have restarted, and minimist is updated to 1.2.6 in [4.2.5](https://github.com/commitizen/cz-cli/releases/tag/v4.2.5).

**Comment by jshnaidman** [comment]
Ah perfect, it was restarted merely hours after my post. 

Also I realize that I should have posted this to flowbite-react not flowbite, apologies.
