### ISSUE TITLE
tab active class error

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#222]
**Describe the bug**
clicking on the first tabs (except the last one) the tab is colored in the edges incorrectly, all the edges should be colored.

**Screenshots**
![image](https://user-images.githubusercontent.com/193969/179555572-5f0a2efa-3df0-4c23-bfae-ff147038e204.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 103

**Comment by zoltanszogyenyi** [comment]
Thanks @KinG-InFeT for the report and @CH4R4F for the solution, I'll check it out and merge it soon.

**Comment by borhansahed** [comment]
Could I work on it?

**Comment by zoltanszogyenyi** [comment]
This has been fixed for the `v2.3` release via https://github.com/themesberg/flowbite/pull/632. Thanks!
