### ISSUE TITLE
Drawer seems missing in the last release dist file

### ISSUE THREAD

**Issue by alorence** [themesberg/flowbite#225]
**Describe the bug**
After updating to 1.5.0, I was not able to use the new Drawer component.
While it is present in node_modules/flowbite/src/components/drawer.js, it does not seems to be included in node_modules/flowbite/dist/flowbite.js.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser N/A
 - Version 1.5.0

**Additional context**
I use pnpm as package installer, not sure if the same issue appear with npm our yarn

**Comment by zoltanszogyenyi** [comment]
Hey @alorence,

Thanks for letting me know.

Big "whoopsie" from my part :)

You can get the Drawer JS starting from v1.5.1.

If something seems off, please let me know!
