### ISSUE TITLE
Alerts with list

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#227]
**Describe the bug**
New example of alerts appeared: `Alerts with list`.

I don't understand why Flowbite.com does not follow it's own coloring standard.
All alerts examples use the flowing colors:
`bg-blue-100 text-blue-700 dark:bg-blue-200 dark:text-blue-800`
`bg-red-100 text-ted-700 dark:bg-red-200 dark:text-red-800`
and the newly added example introduces 
`bg-blue-50 text-blue-900`
`bg-red-50 text-red-900`

**Why??** I thought framework is to standardize the look and feel. It's up to the user to follow the rules or not, but framework should not deviate.

**Expected behavior**
Alerts with lists should follow the color palette introduce at the sections: Defalt alert, Alerts with icons

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

You're right, until further notice I'll add the same color configuration as the other alert components.

@robert1508 please check this out for future reference.
