### ISSUE TITLE
Flowbite js plugin does not work in Vue 3

### ISSUE THREAD

**Issue by MarcVegas** [themesberg/flowbite#231]
**What happened**
There seems to be an issue when using the flowbite plugin package in Vue apps or specifically in this case, a Vue 3 app. Components such as dropdowns and modals just won't work. I made sure to add and import the necessary lines in both the tailwind config and main.js file. Refreshing the browser and restarting the app using `npm run dev` fails to fix issue. When hovering over the plugin in the tailwind config file it gives the following warning

![VS code warning message](https://drive.google.com/uc?id=1-4eHdBwQFshbUV15vQfcJdQQ0VRMrymC)

This issue was posted on stackoverflow but the only slightly helpful answer I found was to link flowbite using unpkg which I do not find particularly ideal as it does not fully solve the problem.

**Desktop**
 - OS: Win10
 - Brave, Chromium browser

**Addendum:**
The same issue occurs when tested in an Incognito window and in Firefox. Clearing the cache also doesn't do anything

**Comment by pl-jay** [comment]
i had the same issue with Flowbite TailwindCSS with Vue 3 Vite project. I thought it's something wrong with OS(Ubuntu 22.04).

**Comment by arajdon** [comment]
Same issue for me. I've followed the instructions given on flowbite for vue.

Something that I've noticed, the instruction states: "Configure the template paths inside the tailwind.config.**js** file:"

The file generated by `tailwindcss init -p` is tailwind.config.**cjs** - don't know if this makes any difference.

**Comment by MarcVegas** [comment]
> this could help [tailwindlabs/tailwindcss-forms#18](https://github.com/tailwindlabs/tailwindcss-forms/issues/18),
> 
> Or this https://stackoverflow.com/questions/72152573/why-my-tailwind-components-library-flowbite-is-not-working
> 
> by the way, using CDN worked for me.

Thanks for pointing this out. This is not a framework specific issue so I hope this gets fixed soon. For anyone pulling their hair out because of this problem and looking for a solution. Unfortunately, there is no @types/flowbite package published yet at the time of this writing to we can't npm install out way out of this but I found there 2 solutions that will hopefully work. Please take note that I assume that you use typescript in your project.

1. Use the unpkg CDN that has the flowbite plugin as @pl-jay has pointed out. I tried this one and it works initially but somehow stops working when used with vue-router. Will update this one if I find a solution
2. Add a globat.d.ts file in the root directory of your project. and add the this line `declare module 'flowbite/plugin'` or `declare module './node_modules/flowbite/plugin.js'`.

You could also try setting your `tsconfig.json` to make typescript tolerate parameters without declaring their type using the code snippet below. I stole this one from [this stackoverflow post](https://stackoverflow.com/questions/47848778/parameter-implicitly-has-an-any-type)
```
// disable this rule:
// "strict": true,

// enable this rule:
"noImplicitAny": false
```

Please comment if you found any mistakes in this. I hope this helps

**Comment by MarcVegas** [comment]
> Same issue for me. I've followed the instructions given on flowbite for vue.
> 
> Something that I've noticed, the instruction states: "Configure the template paths inside the tailwind.config.**js** file:"
> 
> The file generated by `tailwindcss init -p` is tailwind.config.**cjs** - don't know if this makes any difference.

The file extension won't cause an issue in this case. See @pl-jay comment or new comment in this issue and see if one of the solutions works for you. Hope it helps

**Comment by pl-jay** [comment]
Using CDN actually didn't fixed the main issue for me, still flowbite components are not usable inside the project. 

I only needed the date picker to use inside a form but I cannot the drop-down won't work, but when the code put directly within the 
<template> tags it works. I don't whether this is importing issue or not.

Have to go with the workaround suggest by @MarcVegas to fix the npm package importing issue.

**Comment by oleg-agapov** [comment]
Can confirm, as of now (Oct 2) the official way of integration doesn't work with Vue 3.

Had to go with CDN inclusion directly to HTML, and this way it works.

The option with creating `globat.d.ts` file didn't work in my case, dunno why.

**Comment by curtgrimes** [comment]
I think this happens because the Flowbite JS [only runs once on DOM ready](https://github.com/themesberg/flowbite/blob/main/src/components/modal.js#L156), and elements like a button to trigger a modal might not exist at that point.

For now I've done this in a Vue component:

```
onMounted(() => {
  import("flowbite");
});
```

**Comment by potkot** [comment]
Faced the same problem. I am using vue-router. 
The components in the routes were specified like this:
`component: () => import('../components/auth/TheLoginPage.vue'),`
The flowbite dynamic components worked when I changed the component in the route to:
```
import TheLoginPage from '../components/auth/TheLoginPage.vue'
component: TheLoginPage,

**Comment by hurradieweltgehtunter** [comment]
> Hey everyone,
> 
> I think that the best solution will be to use the dedicated [Flowbite Vue](https://github.com/themesberg/flowbite-vue) library because it is based on native Vue components instead of data attributes and event listeners.

Unfortunately the Flowbite Vue Lib offers only a fraction of components :( 
Really looking forward to it but for now I have to switch back to my old css framework :(

**Comment by zoltanszogyenyi** [comment]
Hey peeps,

We're super close to launching Flowbite v1.6.0 which will support Vue 3 programatically.

Here's a starter repo using a temporary release: https://github.com/themesberg/flowbite-vue-starter

**Comment by zoltanszogyenyi** [comment]
Hello everyone,

The v1.6.0 is out and there's a new setup guide and the Flowbite Vue starter as well: https://flowbite.com/docs/getting-started/vue/

Cheers,
Zoltan

**Comment by Khisrav** [comment]
For me flowbite js didnt work too, reason was lazy importing components in vue router

**Comment by hanaameri** [comment]
I fixed this problem by adding "import  flowbite" in the main.js file

**Comment by hanaameri** [comment]
I fixed this problem by adding "import  flowbite" in the main.js file

**Comment by YusronAminullah** [comment]
In file main.js you add this :

**Comment by YusronAminullah** [comment]
In file main.js you add this : 

```
import 'flowbite/dist/flowbite.js';
import 'flowbite/dist/flowbite.css';
import './index.css'
```

And in file tailwind.config.js you add this : 

```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    './node_modules/flowbite/**/*.{js,jsx,ts,tsx}'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('flowbite/plugin')
  ],
}
```
If you use vite. Open vite.config.js and add this : 

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import flowbite from 'flowbite/plugin'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), flowbite()],
})
```
Open file where you add component flowbite. In this, i use sidebar dropdown from flowbite. in some cases it may be the same : 

in <script> :

```
import Sidebar from './Sidebar.vue';
import { onMounted } from 'vue';
import { Dropdown } from 'flowbite';

onMounted(() => {
  // Initialize all dropdowns
  const dropdownElements = document.querySelectorAll('[data-dropdown-toggle]');
  dropdownElements.forEach(triggerEl => {
    const targetEl = document.getElementById(triggerEl.getAttribute('data-dropdown-toggle'));
    new Dropdown(targetEl, triggerEl);
  });
});
```

And in <template> : 

`<Sidebar />`
