### ISSUE TITLE
Build a new range slider component

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite#24]
We'll build the component based on this design.

<img width="752" alt="Screenshot 2021-12-03 at 15 37 04" src="https://user-images.githubusercontent.com/8052108/144611414-a7d69135-d30e-4437-928f-c38690d3b3c5.png">

**Comment by zoltanszogyenyi** [comment]
<img width="752" alt="Screenshot 2021-12-03 at 15 37 04" src="https://user-images.githubusercontent.com/8052108/144611414-a7d69135-d30e-4437-928f-c38690d3b3c5.png">

We'll build the component based on this design.

**Comment by areski** [comment]
Could you clarify if range with 2 handles are supported?
<img width="170" alt="image" src="https://user-images.githubusercontent.com/53455/225000784-6e212e76-55d6-4b86-986c-d473f53e08e0.png">

**Comment by mengqing** [comment]
<img width="660" alt="Screenshot 2024-02-25 at 10 50 09 pm" src="https://github.com/themesberg/flowbite/assets/929022/a710a7cb-2924-436a-b7d7-47effa52826a">

Don't think this has been built, can you confirm? Thanks

**Comment by BrekiTomasson** [comment]
Seconding this, an option with two handles should be supported - or, if it is, documented.
