### ISSUE TITLE
Html Snippet available

### ISSUE THREAD

**Issue by c0ncentus** [themesberg/flowbite#240]
**Is your feature request related to a problem? Please describe.**
My problem is: I dont want copy/paste and waste time to navigate and read ... just "ctrl" and "space"
and have a component to render and customizable

**Describe the solution you'd like**
snippet file to download in the official doc for making on our own concerning command system

**Describe alternatives you've considered**
snippet display in the official doc

**Additional context**
being more productive, MVP fast with react or pure html ...

**Comment by zoltanszogyenyi** [comment]
Hello @c0ncentus,

This is an interesting idea. We might actually offer a downloadable ZIP for all the components on a single page.
