### ISSUE TITLE
Classes for disappearing objects

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#243]
**Describe the bug**
Classes for making the visibility switch for popover, tooltip, modal and dropdown are inconsistent. 

**To Reproduce**
Classes used for show/hide floating elements:
- popover, tooltip: visible/invisible, opacity-100/opacity-0
- modal, dropdown: hidden, bloc/flex

**Expected behavior**
Any reason for that distinction?

**Additional context**
Working on `flowbite-svelte` and trying to abstract behavior.

**Comment by zoltanszogyenyi** [comment]
Hello @jjagielka,

The reason for this is that some of the elements have a fade-in / fade-out effect.

On the other hand, I believe that for the v2.0 launch we will introduce custom animations which will mean an overhaul over these classes.

**Comment by jjagielka** [comment]
**Note!** HTML now support `hidden` as `HTMLElement` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
