### ISSUE TITLE
Not Working flowbite at laravel (Inertia+Jetstream) Project

### ISSUE THREAD

**Issue by MohammadRahimiAngiz** [themesberg/flowbite#250]
hi
i create new project in laravel with jetstream & inertia. Unfortunately not working megamenu component
best regard

**Comment by MohammadRahimiAngiz** [comment]
not working flowbite.js with laravel vite & Inertia & Vue js 3

**Comment by q4q0** [comment]
same issue here.
it doesn't work....

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

Have you tried the new init functions for the data attributes?

Here's an example: https://flowbite.com/docs/getting-started/vue/#data-attributes

Cheers,
Zoltan
