### ISSUE TITLE
Inaccurate documentation / Svelte

### ISSUE THREAD

**Issue by ollydixon** [themesberg/flowbite#252]
Trying to get access to the drawer object, have the following code in Svelte.

```
<script lang="ts">
    import { Drawer } from 'flowbite-svelte'
    import { onMount } from 'svelte'
    import CrossBtn from '../../assets/cross-btn.svelte'

    let drawer: Drawer

    onMount(async () => {
        const targetEl = document.getElementById('root-drawer')
        // options with default values
        const options = {}
        drawer = new Drawer(targetEl, options)
    })

    function hideDrawer() {
        drawer.hide()
    }
</script>
```

But it complains that this is in-fact incorrect, making the drawer unusable.

Complaints from the TS
<img width="593" alt="Screenshot 2022-08-24 at 16 13 56" src="https://user-images.githubusercontent.com/6940726/186442037-ea2e941b-5df7-4f41-b0bc-1f7b5a482404.png">

Documentation says
<img width="502" alt="Screenshot 2022-08-24 at 16 14 01" src="https://user-images.githubusercontent.com/6940726/186442158-1d9822b0-9fc7-49cc-92c0-87ae4f1665af.png">

Safari console log says
<img width="656" alt="Screenshot 2022-08-24 at 16 15 17" src="https://user-images.githubusercontent.com/6940726/186442169-a345cc6e-055c-4314-b463-40f824c85902.png">

**Comment by zoltanszogyenyi** [comment]
Issue closed because it was moved to the Flowbite Svelte repo.
