### ISSUE TITLE
Datepicker dropdown floating at the top left of screen

### ISSUE THREAD

**Issue by djelusive** [themesberg/flowbite#254]
flowbite@1.5.2/dist/flowbite.min.css
flowbite@1.5.2/dist/flowbite.js
flowbite@1.5.2/dist/datepicker.js

While using the datepicker plugin within Laravel 8, I've noticed a recent issue where the dropdown floats at the very top left of the screen.

I have been able to resolve this by changing line 1755 within the datepicker.js file. 

Changing this:
`elementClass === 'dropdown' ? element.classList.add('dropdown', 'absolute', 'top-0', 'left-0', 'z-50', 'pt-2') : null;`

To:
`elementClass === 'dropdown' ? element.classList.add('dropdown', 'absolute', 'z-50', 'pt-2') : null;`

Simply removing 'top-0' and 'left-0' because while looking at the element in the console it also shows an additional css style that these parameters are overwriting:
`style="top: 422px; left: 621.333px;"`

**Comment by zoltanszogyenyi** [comment]
Thanks, @djelusive for the fix! I'll get this addressed in the `v1.6.0` release.

**Comment by 0Chan-smc** [comment]
Also waiting for this issue to be resolved! Thanks in advance...

**Comment by zoltanszogyenyi** [comment]
Fixed with `v2.4.1`:

https://flowbite.com/docs/components/datepicker/

**Comment by rubenkuipers** [comment]
@zoltanszogyenyi I'm running into the exact same issue on `v2.5.2` of the javascript api. I see that the datepicker-dropdown gets assigned `top-0 left-0` again.
