### ISSUE TITLE
Buttons page freezes and has no response

### ISSUE THREAD

**Issue by UmbrellaCrow612** [themesberg/flowbite#257]
**Describe the bug**

Visiting the buttons page results in page freeze and error

https://flowbite.com/docs/components/buttons/

**To Reproduce**
1. Go to 'https://flowbite.com/docs/components/buttons/'
2. See error

**Expected behavior**

For buttons to load and page not to freeze 

**Screenshots**

**Desktop (please complete the following information):**
 
MacOs version 12.5.1
Chrome
Version 104.0.5112.101 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hello @UmbrellaCrow612,

Thanks for reporting.

Does this always happen or only a couple of times?

I couldn't reproduce myself I'm afraid.

**Comment by UmbrellaCrow612** [comment]
Hi it seems to be a chrome extension i had, i removed it and it works now, i will close the issue now.
