### ISSUE TITLE
how I can use flowbite in react without flowbite-react library

### ISSUE THREAD

**Issue by itsaboutcode** [themesberg/flowbite#258]
I did not find any documentation out there which help me use flowbite in reactjs project without flowbite-react library. Just wondering if someone can guide me on how we can do that.

Thanks

**Comment by CH4R4F** [comment]
If you're using `create-react-app` you should install tailwindcss by [following tailwindcss guide](https://tailwindcss.com/docs/guides/create-react-app)
then install flowbite [following the official docs](https://flowbite.com/docs/getting-started/quickstart/)
now start the react server and use any component you want :D 

**Dont's forget to configure the tailwind.config.js file :)**
