### ISSUE TITLE
looking to use mui with tailwind css

### ISSUE THREAD

**Issue by cadentic** [themesberg/flowbite#270]
I'm always frustrated when i tried to use tailwind with naterial-ui 

**Describe the solution you'd like**
i want to use tailwind with material-ui 
`<Card sx={{ flexDirection: 'row', maxWidth: 545, borderRadius: "20px", spacing: "125px", boxShadow: "7px", alignItems: 'stretch' , hover:bg - grey - 500 }} elevation={4} position="relative" >
`
**Describe alternatives you've considered**
need to get into something else eg. styled-components

**Comment by clementmas** [comment]
This is not a Flowbite issue. Are you in the wrong repo?

**Comment by zoltanszogyenyi** [comment]
Hey @cadentic,

You can check out [Flowbite React](https://github.com/themesberg/flowbite-react) as an alternative to Material UI + Tailwind CSS.
