### ISSUE TITLE
modal & dropdown menu not working.

### ISSUE THREAD

**Issue by q5p0q5p** [themesberg/flowbite#284]
interia js & laravel 9

**Comment by KinG-InFeT** [comment]
can you write a html with example code?

**Comment by yiyasha15** [comment]
not working for me too..

**Comment by zoltanszogyenyi** [comment]
Hello @q5p0q5p, @KinG-InFeT, @yiyasha15,

Can you please provide more context for this issue?

Thanks!

**Comment by KinG-InFeT** [comment]
this is a test: https://jsfiddle.net/1kosebzL/1/ but works correctly, @q5p0q5p can you explain the problem?
