### ISSUE TITLE
Using the dialog element for alert, modal or other subwindow.

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#292]
We had a dicussion in Flowbite-Svelte, https://github.com/themesberg/flowbite-svelte/issues/311 about using the [dialog HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).

> The <dialog> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow.

For the next version of Flowbite, how about start using the `dialog` element?

**Comment by zoltanszogyenyi** [comment]
Hello @shinokada,

I'll have a good look at this. Thanks for reporting!
