### ISSUE TITLE
Drawer backdrop not clearing when click outside of drawer to close

### ISSUE THREAD

**Issue by dmbrooking** [themesberg/flowbite#293]
**Describe the bug**
I copied and pasted the code from https://flowbite.com/docs/components/drawer/#drawer-navigation and in Chrome, when I click the button to open the drawer, I see that it creates two backdrops.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/128946/192066815-944f958c-89da-422c-8bb5-ded32eafc185.png">

When I close the drawer by clicking outside of the drawer, only one backdrop goes away so it leaves the rest of the page dark and unclickable.

I checked in Safari and it does work there.

**To Reproduce**
1. Take the example code here: https://flowbite.com/docs/components/drawer/#drawer-navigation
2. Copy and paste it into a page
3. Click to open the drawer, click outside of the drawer to close it

**Expected behavior**
I'm expecting when you click outside of the drawer, the backdrop goes away completely.

**Screenshots**
Before clicking:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/128946/192067133-68fd40bc-b413-4baf-aa96-4dcbc583c173.png">

After clicking:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/128946/192067207-47696083-504e-4b89-8ee9-48227c53a1bd.png">

After clicking outside drawer:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/128946/192067228-e89889fd-70a8-4898-9f96-bcc1f48f57b7.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 105.0.5195.125

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hello @dmbrooking,

Thanks for reporting.

Are you sure there is only one drawer present on the page? Is there an online demo of your code that I can check out?

Thanks!

**Comment by zoltanszogyenyi** [comment]
Hey @saxjonas,

As long as there is only one drawer open at a time with different id's this shouldn't happen.

Or is there a scenario where you actually want to open two drawers at the same time?

Cheers,
Zoltan

**Comment by saxjonas** [comment]
It seems like my vue code might be double rendering the sub component I'm using the drawer in, so I think I'm at fault here. I only get one instance of the drawer in the DOM, but I believe it might have instantiated it twice. Is there anyway to check if there's already a drawer with the same ID? Obviously I'm going to try to fix the underlying issue, but just wanted to know if there's some internal checks that you can use when calling initDrawer in onMounted.

**Comment by clementmas** [comment]
I'm also getting the same issue when upgrading from Flowbite 1.5.5 to 1.6.2.

```js
import { initDrawers } from 'flowbite';

window.addEventListener('load', initDrawers); // doesn't work anymore
// creates 2 backdrop divs
```

```js
import 'flowbite'; // works
```

I think manually loading components should be supported and documented.

**Comment by dosstx** [comment]
Getting this too. Anyone figure it out yet?

**Comment by CallmeSetia** [comment]
> I'm also getting the same issue when upgrading from Flowbite 1.5.5 to 1.6.2.
> 
> ```js
> import { initDrawers } from 'flowbite';
> 
> window.addEventListener('load', initDrawers); // doesn't work anymore
> // creates 2 backdrop divs
> ```
> 
> ```js
> import 'flowbite'; // works
> ```
> 
> I think manually loading components should be supported and documented.

thankss, solved by change 

`
import { onMounted } from 'vue'
import { initFlowbite } from 'flowbite'

export  default {
  setup() {
    onMounted(() => {
      initFlowbite();
    })
  }
}
`
to 
`
import { onMounted } from 'vue'
import 'flowbite'

export  default {
  setup() {
    onMounted(() => {
      // initFlowbite();
    })
  }
}
`

**Comment by ngyngcphu** [comment]
Hi all,
I did this way and it worked.
```sh
import { useEffect, useRef } from 'react';
import { Drawer } from 'flowbite';
...
const drawerRef = useRef<HTMLDivElement>(null);
useEffect(() => {
    new Drawer(drawerRef.current);
  }, [])
...
<div ref={drawerRef} id="drawer-navigation" class="fixed top-0 left-0 z-40 w-64 h-screen p-4 overflow-y-auto ... >
...
```

**Comment by deleonjulio** [comment]
This issue also exist on React.

**Comment by twent** [comment]
Why this issue is closed? I has the same issue with Vue 3.2.41 + Flowbite 1.8.1

**Comment by rlongre** [comment]
Seems this is now being tracked in #589

**Comment by DevVerma07** [comment]
this issue is still exist please give solution to fix it.

**Comment by bellps** [comment]
Hello, I'm facing this issue too, even with the new version (using 2.5.1)

**Comment by PashaTyulnev** [comment]
Check in the browser console if the "open menu hamburger" - Button have 2 events. If yes, then you load flowbite twice. For example I had loaded it via cdn and from node_modules.

**Comment by bellps** [comment]
@PashaTyulnev thanks, I'll check that. Also, one question, my hamburger button is removed then added again to the screen multiple times, could that cause any trouble?

**Comment by NDTChan** [comment]
I'm using Astro 5.2.2, Flowbite 3.1.1, and Tailwind CSS 4.0.3. To resolve the drawer backdrop issue, I need to use the JavaScript behavior of the Drawer. Additionally, make sure to remove all data-drawer-* attributes from both the menu button and the drawer component.


```
<button
    id="btn-drawer-navigation"
    type="button"
    class="ml-1 inline-flex cursor-pointer items-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:ring-2 focus:ring-gray-200 focus:outline-none xl:hidden dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd">
        </path>
    </svg>
</button>
```


```
<div
    id="drawer-navigation"
    class="fixed top-0 right-0 z-40 h-screen w-80 translate-x-full overflow-y-auto bg-white p-4 dark:bg-gray-800"
    tabindex="-1">
    <h5
        id="drawer-navigation-label"
        class="text-base font-semibold text-gray-500 uppercase dark:text-gray-400">
        Menu
    </h5>
    <button
        type="button"
        class="absolute end-2.5 top-2.5 inline-flex h-8 w-8 items-center justify-center rounded-lg bg-transparent text-sm text-gray-400 hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-white">
        <svg
            class="h-3 w-3"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 14 14">
            <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6">
            </path>
        </svg>
        <span class="sr-only">Close menu</span>
    </button>
    <div class="overflow-y-auto py-4">
        <ul class="space-y-2 font-medium">
            {
                Object.entries(categories).map(([key, value]) => {
                    let categoryHref = `/${key}`;
                    return (
                        <li>
                            <a
                                id={`drawer-nav-${key}`}
                                href={categoryHref}
                                class="group dark:hover:bg-gray-70 text-primary-700 flex items-center rounded-lg p-2 hover:bg-gray-100 dark:text-white">
                                <span class="ms-3">{value}</span>
                            </a>
                        </li>
                    );
                })
            }
        </ul>
    </div>
</div>
```
And this is my script code:

```
<script>
    import { Drawer } from "flowbite";
    import type { DrawerInterface } from "flowbite";

    function initDrawer() {
        const $drawer = document.getElementById("drawer-navigation");
        const options = {
            placement: "right",
            backdrop: true,
            bodyScrolling: false,
            edge: false,
            edgeOffset: "",
            backdropClasses: "bg-gray-900/50 dark:bg-gray-900/80 fixed inset-0 z-30"
        };

        return new Drawer($drawer, options);
    }

    function drawerEventRelated(drawer: DrawerInterface) {
        const $btnDrawer = document.getElementById("btn-drawer-navigation");
        $btnDrawer?.addEventListener("click", () => {
            drawer.show();
        });

        const $drawerNavs = document.querySelectorAll('[id^="drawer-nav-"]');
        $drawerNavs.forEach(($drawerNav) => {
            $drawerNav.addEventListener("click", () => {
                drawer.hide();
            });
        });
    }

    document.addEventListener("astro:page-load", () => {
        // JS for mobile drawer navigation
        drawerEventRelated(initDrawer());
    });
</script>
```

**Comment by sdklab007** [comment]
It wasn't still working for me. This is how I resolved it:

```
const drawer = FlowbiteInstances.getInstance('Drawer', 'drawer-schedule-meeting');
drawer.hide();
const backdropDiv = document.querySelector('div[drawer-backdrop]');
if (backdropDiv) {
        backdropDiv.className = '';
}
```
