### ISSUE TITLE
DatePicker options

### ISSUE THREAD

**Issue by loranger** [themesberg/flowbite#30]
Hello,

I cant figure out how I can pass option to the datepicker, using javascript.

I tried
```javascript
new Datepicker(datepickerEl, {
    autohide: true,
    format: 'mm/dd/yyyy',
});
```

But it does not work. My Datepicker is displayed and works but I cannot change any option using JS declaration.
What did I miss ?

**Comment by zoltanszogyenyi** [comment]
Hey @loranger,

Did you install and include the datepicker plugin following this?

https://flowbite.com/docs/plugins/datepicker/#javascript

**Comment by loranger** [comment]
Thanks for your reply !

In order to reply, I tried to add some other options, such as title, and it worked. 
So I was writing the issue only exists with the date format, until I realized I needed to change the format in order to use another format.

My bad.
Sorry for the noise, and thank again for your support
