### ISSUE TITLE
Flowbite doesn't work as follow setup from documentation

### ISSUE THREAD

**Issue by nguyentienlinh2611** [themesberg/flowbite#303]
**Describe the bug**
I follow this instruction [https://flowbite.com/docs/getting-started/vue/](https://flowbite.com/docs/getting-started/vue/) and setup my new project. But seem flowbite doesn't working until I add script tag to import flowbite from html file.

**Comment by volp99** [comment]
Hey @nguyentienlinh2611, which version of Vue are you using?

**Comment by nguyentienlinh2611** [comment]
I'm using vue 3, just follow the document, then add a button to pop up the modal, but it does not work till I add script flowbite at the end of body element on html file

**Comment by volp99** [comment]
Did you try to follow this documentation?
https://flowbite-vue.com/pages/getting-started.html

**Comment by nguyentienlinh2611** [comment]
I did, but it still did not work. I see some people have the same problem as me [https://stackoverflow.com/a/74041105](https://stackoverflow.com/a/74041105). Is this an omission in the documentation?

**Comment by zoltanszogyenyi** [comment]
Hey @nguyentienlinh2611 @volp99,

Please refer to this repository if you want to use Flowbite with Vue 3. It's currently still in progress, but it's the best way to use it if you want to have the interactive components work with routers.

https://github.com/themesberg/flowbite-vue

Thanks!

**Comment by zoltanszogyenyi** [comment]
I'll keep the issue open because we will also update the our own docs page for Vue 3.

**Comment by littledot** [comment]
I encountered this issue as well. I followed the Vue-specific docs so I didn't add the script tag. If the script tag is important it should be pasted on framework-specific page as well.

**Comment by frasza** [comment]
For me it only works with version 1.5.0

**Comment by zoltanszogyenyi** [comment]
Hello everyone,

We have updated the Flowbite + Vue 3 setup guide: https://flowbite.com/docs/getting-started/vue/

Cheers,
Zoltan
