### ISSUE TITLE
Flowbite and Turbo Rails 7 with import map

### ISSUE THREAD

**Issue by VarProg** [themesberg/flowbite#305]
Please help me, how to use Flowbite and Turbo Rails 7 with import map?
I use Flowbite v.1.5.3 as here https://flowbite.com/docs/getting-started/rails/
and tailwindcss

I change "DOMContentLoaded" on "turbo:load" in dist/flowbite.js and in vendor/javascript/flowbite.js, but it's not work for me, my scripts work only if reload page

**Comment by mwalkowiak** [comment]
for me anything above `1.5.0` doesn't work as I was playing with Rails 7 importmap setup

**Comment by qirpi** [comment]
> Please help me, how to use Flowbite and Turbo Rails 7 with import map? I use Flowbite v.1.5.3 as here https://flowbite.com/docs/getting-started/rails/ and tailwindcss
> 
> I change "DOMContentLoaded" on "turbo:load" in dist/flowbite.js and in vendor/javascript/flowbite.js, but it's not work for me, my scripts work only if reload page

I think you may need to pin an earlier flowbite version — like @mwalkowiak said the fix outlined in #88 only works on flowbite versions up to `1.5.0`, so try running the following in your rails project folder:

`./bin/importmap pin flowbite@1.5.0` --download`

Then make sure to go back and replace all the `DOMContentLoaded` in `vendor/javascript/flowbite.js` with `turbo:load`, like before, as the file gets replaced by the above command.

Hope that helps!
