### ISSUE TITLE
Flowbite DatePicker Requires Adding Classes to `tailwind.config.js` Safe List

### ISSUE THREAD

**Issue by rdotchin** [themesberg/flowbite#306]
**Describe the bug**
We are currently utilizing the flowbite datepicker in a nuxt project that has `tailwindcss^3.1.8` via `@nuxtjs/taiwlindcss`. For the DatePicker component to work it requires adding `hidden` and `grid-cols-7` to our `tailwind.config.js` `safelist`.

**Expected behavior**
The Ability to utilize the DatePicker component without having to adjust our applications `tailwindcss` `safelist`

**Screenshots**
Without `safelist` additions:
<img width="981" alt="Screen Shot 2022-10-11 at 2 30 46 PM" src="https://user-images.githubusercontent.com/19737869/195171305-7299f2ab-0bf8-45e4-abf7-c6ae6c7b0d77.png">

With `safelist` additions:
<img width="983" alt="Screen Shot 2022-10-11 at 2 31 40 PM" src="https://user-images.githubusercontent.com/19737869/195171474-301a570d-9fba-44f0-b7f3-b64239a47679.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 105.0.5195.125 

**Additional context**

**Comment by dancaron** [comment]
Also experiencing this issue.

**Comment by zoltanszogyenyi** [comment]
This will be addressed in the `v1.6.0` update

**Comment by TeachMeHowToUse2FA** [comment]
Confirm this bug.

**Comment by specimen151** [comment]
Perhaps this is because I'm using Tailwind with "compiler" and Flowbite with CDN, but at least what I have to do is to add even more classes to the safelist (the screenshot for the OP is not how the datepicker should look, there is a lot of margin/padding missing):

'hidden', 'grid-cols-7', 'w-64', 'mb-1', 'grid', 'bg-blue-700', 'leading-9'

Also I've noted that the component add both text-gray-900 and text-gray-500 to the dates outside the current month.

**Comment by archonic** [comment]
I installed the datepicker from the NPM package and did not have to add any safe list classes.

**Comment by specimen151** [comment]
I used CDN.

tir. 14. mar. 2023 kl. 02:12 skrev Archonic ***@***.***>:

**Comment by rootchips** [comment]
Same issue here after build static for production `npx nuxi generate` but works on local `npx nuxi dev`. How do you guys resolve this? For quick trick.

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

If you install Flowbite v2.0 does this issue still occur?

I've added the classes into our plugin file to automatically safelist them.

Cheers,
Zoltan

**Comment by javierfigueroacl** [comment]
Just in case someone is looking at this on 2025 and using react, you need to also upgrade `flowbite-react` to > `0.11.0` on top of `flowbite` > 2 for the issue to be resolved.
