### ISSUE TITLE
[Docs bug] example code for modals use different classes than in reality

### ISSUE THREAD

**Issue by the-overdriven** [themesberg/flowbite#310]
If someone copy-pastes the example code from https://flowbite.com/docs/components/modal/ it will produce different result than in your docs.

Modal classes in reality:` overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 md:inset-0 h-modal md:h-full justify-center items-center flex`

Modal classes from your html code: `fixed h-modal left-0 md:h-full md:inset-0 overflow-x-hidden overflow-y-auto right-0 top-0 z-50`

Classes written in HTML section are not going to center the modal.

**Comment by zoltanszogyenyi** [comment]
Fixed for the `v1.5.4` update via the https://github.com/themesberg/flowbite/commit/c699f09850cd0cca2878c333eaf2462afa7bfaff commit.
