### ISSUE TITLE
Javascript error on data-dropdown-placement

### ISSUE THREAD

**Issue by balex25** [themesberg/flowbite#313]
**Describe the bug**
When I set data-dropdown-placement to bottom-right | bottom-left, as I want the dropdown menu to go down of button, and don't get position on center.

Console log error: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')".

**To Reproduce**
1. Make a dropdown
2. Set data-dropdown-placement="bottom-right" on dropdown open button.
4. See error in the console.

**Expected behavior**
The dropdown should work as right-start or left-start.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version latest

**Comment by zoltanszogyenyi** [comment]
Hello @balex25,

Thanks for reporting - I'll check this out for the next update.

**Comment by zoltanszogyenyi** [comment]
Hey @balex25,

Please use `bottom-start` or `bottom-end` instead of `bottom-left` or `bottom-right`.
