### ISSUE TITLE
DOCS: Operators barely visible in Dark Mode Switcher Code Snippet

### ISSUE THREAD

**Issue by AyanavaKarmakar** [themesberg/flowbite#323]
**Describe the bug**
The operators in this [code snippet](https://flowbite.com/docs/customize/dark-mode/#dark-mode-switcher) are barely visible in dark mode, as compared to other code snippets.

**To Reproduce**
1. Go to 'https://flowbite.com/docs/customize/dark-mode/#dark-mode-switcher'
2. Click on the `Toggle Dark Mode` button

**Expected behavior**
The operators should be visible like in other code snippets in dark mode.

**Screenshots** 

![CodeSnippetinDarkModeBarelyVisible](https://user-images.githubusercontent.com/89210438/199660547-c3d32c51-c171-4270-821e-89ce987482a9.png) 

![CodeSnippetLightMode](https://user-images.githubusercontent.com/89210438/199663147-70e9d30a-c3c8-4616-a7ee-fe7b1429effb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.45.118 Chromium: 107.0.5304.91

**Additional context**
Other code snippets with operators in dark mode look fine. For example, 

![CodeSnippetinDarkModeVisible](https://user-images.githubusercontent.com/89210438/199661386-56520aaa-889d-4cfe-a68b-229d7ba20bce.png)

**Comment by zoltanszogyenyi** [comment]
Hello @AyanavaKarmakar,

Thanks for the issue. I'll have this fixed for the `v1.5.4` release today.
