### ISSUE TITLE
dropdown is not working on dynamically create content using jquery

### ISSUE THREAD

**Issue by ajayexpert** [themesberg/flowbite#331]
**Describe the bug**
I have added one element using jquery that has a dropdown but it's not working, when I am clicking on the button it's not showing the dropdown. 

I am using CDN to add flowbite js.

**Comment by zoltanszogyenyi** [comment]
Hello @ajayexpert,

I need some code and live examples to be able to pin-point the issue.

**Comment by zoltanszogyenyi** [comment]
Please re-open if issue persists, but with examples to be able to reproduce.
