### ISSUE TITLE
"carousel" doesn't work if we set up a slide divided by 3 items

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#332]
**Describe the bug**
if you set the slide with 3 elements (or in any case greater than 1) the component is not able to go forward from slide to slide.

**To Reproduce**
Demo code: https://jsfiddle.net/vincenzo_hpo/18pgrdm7/6/

**Comment by zoltanszogyenyi** [comment]
Hey @KinG-InFeT - this should be fixed with the new `v2.3` release.

**Comment by KinG-InFeT** [comment]
> Hey @KinG-InFeT - this should be fixed with the new `v2.3` release.

sfortunately no, this is same example with latest public release (2.2.1) https://jsfiddle.net/vincenzo_hpo/18pgrdm7/7/ , same problem

**Comment by zoltanszogyenyi** [comment]
v2.3 is not live yet, but the changes are commited on the main branch.

**Comment by KinG-InFeT** [comment]
> v2.3 is not live yet, but the changes are commited on the main branch.

so before closing the task we first want to check with the example whether the bug has been resolved or not? shall we wait for him to publish version 2.3 so as to update the example with the bug and, if it has been resolved, close the task? so we are sure

**Comment by zoltanszogyenyi** [comment]
Re-opened before the publish has been made.

**Comment by zoltanszogyenyi** [comment]
Release has been made public https://flowbite.com/docs/components/clipboard/

**Comment by KinG-InFeT** [comment]
> sfortunately no, this is same example with latest public release (2.2.1) https://jsfiddle.net/vincenzo_hpo/18pgrdm7/7/ , same problem

sfortunately the bug persist with new release 2.3 https://jsfiddle.net/vincenzo_hpo/18pgrdm7/7/ , same problem
