### ISSUE TITLE
How to import flowbite.js locally and keep it across all routes

### ISSUE THREAD

**Issue by Lucasvo1** [themesberg/flowbite#336]
I am trying to import the flowbite.js script into my next.js project. The only way I can have it work somewhat is via CDN in _app.js but after hot-reloading the script does not work anymore.

**Comment by zoltanszogyenyi** [comment]
Hey @Lucasvo1,

Please refer to the [Flowbite React](https://github.com/themesberg/flowbite-react) library if using Next.js or React and you can also check out the official [Flowbite + Next JS integration guide](https://flowbite.com/docs/getting-started/next-js/).

If the issue still persists then please open up an issue on the Flowbite React library. Thanks!
