### ISSUE TITLE
Can i customize active tab's background color, text color or other css?

### ISSUE THREAD

**Issue by astrexxx** [themesberg/flowbite#338]
I am using the interactive tabs component but i want to customize the active tab, how can i achieve it?
[interactive tabs in docs](https://flowbite.com/docs/components/tabs/#interactive-tabs)

**Comment by zoltanszogyenyi** [comment]
Hey @astrexxx,

You can do that by either using the JS API options like `activeClasses` and `inactiveClasses` from here: https://flowbite.com/docs/components/tabs/#javascript-behaviour
