### ISSUE TITLE
Nested lists don't indent properly

### ISSUE THREAD

**Issue by rafabulsing** [themesberg/flowbite#347]
Nested lists don't indent properly. They should indent by default, but when including Flowbite, all items are shown with 0 indentation, as if it was a flat list.

**To Reproduce**

```html
<html>
    <head>
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
    </head>
    <body>
        <ul>
            <li>
                <span>A</span>
            </li>
            <li>
                <span>B</span>
                <ul>
                        <li>
                            <span>B1</span>
                        </li>
                        <li>
                            <span>B2</span>
                        </li>
                </ul>
        </ul>
    </body>
</html>
```

**Expected behavior**
The list show be correctly indented.

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/40143958/204899276-77397bd9-5bfd-43bc-acbc-46c482006108.png)

Expected (simply commented out the stylesheet line):
![image](https://user-images.githubusercontent.com/40143958/204899101-0aa4712c-469f-45be-9191-dd01e4f42f89.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version 107 (for both, interestingly enough)

**Additional context**

I suspect that this is a known issue, because the [docs](https://flowbite.com/docs/typography/lists/#nested-1)  explicitly sets a left padding on the example for nested lists.

While this works for static examples, it is not practical when dealing with arbitrary levels of nesting. It really should work by default.

**Comment by zoltanszogyenyi** [comment]
Hello @rafabulsing,

Thanks for opening up the issue. The reason why it does not nest is that Tailwind CSS automatically removes the nesting and spacing classes from lists by default. On the other hand, we have some [nested list examples on Flowbite](https://flowbite.com/docs/typography/lists/#nested-1) that you can use.
