### ISSUE TITLE
Grid columns over 6 not working

### ISSUE THREAD

**Issue by stsrki** [themesberg/flowbite#351]
If I try to define grid columns with any number over `grid-cols-6`, it doesn't get applied. Based on the Tailwind documentation this should work.

---

**`grid-cols-12` NOT working** (shows as only one column)

![image](https://user-images.githubusercontent.com/900302/205925531-5d1e0211-b861-4a80-8d84-83eb399532df.png)

---

**`grid-cols-6` working**

![image](https://user-images.githubusercontent.com/900302/205926132-0d468849-913f-47ac-b560-c7bb9424cf43.png)

**Comment by stsrki** [comment]
Please ignore. It is working. I failed to understand that I also need to include `<script src="https://cdn.tailwindcss.com"></script>` from the guide on https://flowbite.com/docs/getting-started/quickstart/

**Comment by aleksboch** [comment]
I would like to reopen this issue as it's still ongoing with using tailwindcss and flowbite as a package and building locally. 

Selectors like lg:grid-cols-4 work, however lg:grid-cols-6 and lg:grid-cols-12 do not as the specificity of other sm/md grid col selectors are higher
