### ISSUE TITLE
[Bug and Solution] Weird bug with examples in checkbox, radio, dropdowns (White outline on focused radio and checkbox elements)(ring-offset-gray-700)

### ISSUE THREAD

**Issue by namrog84** [themesberg/flowbite#354]
**Describe the bug**

This is how I see it on your example page
![image](https://user-images.githubusercontent.com/1614040/206404072-8e528513-d54f-44bf-b184-e2b0a4440929.png)

And this is how I see it when I copy/paste the exact same code into my page on my own site
![image](https://user-images.githubusercontent.com/1614040/206404211-4529677b-ec8b-4ab7-b060-82028f009bbb.png)

0 code changes, and I've tried a relative empty/clean project with no unusual overrides happening anywhere else. 

I've spent soooo many hours trying to figure out what the heck was going on. I finally tracked down the 'issue'.

In both your 'html' code for the various things, and on the html itself you use `dark:ring-offset-gray-700`

However, the way to fix it on my end is to do `dark:focus:ring-offset-gray-700` or just `focus:ring-offset-gray-700` since I'm not using dark mode code.

My suggested fix is to update your 4 examples here to be the dark:focus:ring-offset-gray-700, since I think that's whats intended here?
4 locations of it in the readme, not sure where your website code is or if it references the md directly. 

https://github.com/themesberg/flowbite/search?q=ring-offset-gray-700*

I am not sure if there is some other setting that is causing some weird behavior, but I know that simple change made fixed it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 107+

**Additional context**

**Comment by namrog84** [comment]
Not sure if there is some other subtle override happening somewhere else, like in a tailwind.config.js or something, so other ideas are welcome too.

**Comment by zoltanszogyenyi** [comment]
Hey @namrog84,

Did you install Flowbite as a plugin inside your `tailwind.config.js` file?

Generally that is where we add these pseudo classes.

Cheers,
Zoltan

**Comment by namrog84** [comment]
My plugins in my tailwind.config.js looks like this

```
plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('flowbite/plugin'),
  ],
```

**Comment by zoltanszogyenyi** [comment]
Hey @namrog84,

The Flowbite plugin already adds styles for the form pseudo elements - what happens if you remove the official @tailwindcss/forms plugin? Or do you use something essential from there?

**Comment by CorwinDev** [comment]
Hi @zoltanszogyenyi,

@namrog84 is indeed right.

![image](https://user-images.githubusercontent.com/88144943/210863012-a67c96ea-360a-47a5-bf6c-c65432df7a80.png)

Tailwind playgroud: https://play.tailwindcss.com/ljnQ8F3gvi

As @namrog84 suggested `dark:focus:ring-offset-gray-700` fixes this!

**Comment by zoltanszogyenyi** [comment]
Thanks @CorwinDev for the input - seems like we have to update all our occurences in the docs.

**Comment by zoltanszogyenyi** [comment]
Fixed in https://www.producthunt.com/golden-kitty-awards.
