### ISSUE TITLE
Full width tabs only 3 of 4 sides on main site?

### ISSUE THREAD

**Issue by namrog84** [themesberg/flowbite#355]
**Describe the bug**
Doesn't show ring on all 4 sides.

**To Reproduce**

https://flowbite.com/docs/components/tabs/#full-width-tabs
![image](https://user-images.githubusercontent.com/1614040/206810567-82067831-ae10-4d3d-b94f-73e54679b311.png)

Notice the focus doesn't cover the right hand side, but only the top, left, and bottom.

How do I make this exact thing cover the right hand side too?

**Expected behavior**
To see the outline on all 4 sides

**Screenshots**
See above included screenshots

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 107

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hello @namrog84,

Thanks for the report - this will get fixed.
