### ISSUE TITLE
error console and not run modal!

### ISSUE THREAD

**Issue by juza66** [themesberg/flowbite#356]
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at flowbite.js:3054:29
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.initModal (flowbite.js:3051:52)

**Comment by juza66** [comment]
<button type="button"  data-modal-toggle="createDoctorModal" class=" bg-blue-600 transition-all hover:bg-blue-700 py-2 px-4 rounded-full text-xs text-white flex justify-center items-center ml-4">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                     <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                  </svg>                   
                  <span class="mr-2">ایجاد پزشک جدید</span>
               </button>

<div id="createDoctorModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full" >
   <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
       
       <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
           
           <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
               <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                   ایجاد پزشک جدید
               </h3>
               <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 mr-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="createDoctorModal">
                   <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                   <span class="sr-only">Close modal</span>
               </button>
           </div>
           <livewire:admin.doctor.create :key="now()->timestamp" />
       </div>
   </div>
</div>

**Comment by zoltanszogyenyi** [comment]
Hello @juza66,

Can you please give more context for this? Thanks!
