### ISSUE TITLE
Accordion, Dropdown, Modal, dst. not working in jquery laravel, how to solve it?

### ISSUE THREAD

**Issue by Khanif363** [themesberg/flowbite#373]
function updateResults(results) {
                        // Clear the previous search results
                        $('#search-results').empty();

                        // Loop through the search results
                        results.forEach(function(result) {
                            // Create the HTML for the search result
                            var resultHTML = `<h2 id="accordion-catalog-head-${result.id}">
                            <button type="button"
                                class="flex items-center justify-between w-full py-5 font-medium text-left border-b text-gray-500 border-gray-200 dark:border-gray-700 dark:text-gray-400"
                                data-accordion-target="#accordion-catalog-body-${result.id}" aria-expanded="true"
                                aria-controls="accordion-catalog-body-${result.id}">
                                <span>${result.title}</span>
                                <span data-accordion-icon
                                    class="w-6 h-6 rotate-180 shrink-0 flex justify-center items-center">
                                    <i class="fas fa-angle-down"></i>
                                </span>
                            </button>
                        </h2>
                        <div id="accordion-catalog-body-${result.id}" class="hidden"
                            aria-labelledby="accordion-catalog-head-${result.id}">
                            <div class="py-5 font-light border-b border-gray-200 dark:border-gray-700">
                                <p class="mb-2 text-gray-500 dark:text-gray-400">${result.information}</p>
                            </div>
                        </div>`;

                            // Append the search result HTML to the search results container
                            $('#search-results').append(resultHTML);
                        });
                    }

**Comment by zoltanszogyenyi** [comment]
Hello @Khanif363,

Thanks for reporting the issue.

It's a bit hard to understand what should happen here and what the issue is - can you please post an online example?

Cheers,
Zoltan
