### ISSUE TITLE
Modal backdrop classes doesn't work 

### ISSUE THREAD

**Issue by Ravikisha** [themesberg/flowbite#374]
# Bug in Flowbite Modal

## version:  1.5.5

I raise an issue in flowbite model in laravel project that in `options` in Class `Modal` has a `backdropClasses` that should have changed by defining the options but it is not working. after that, I tried in the vite dev environment, but it was still not working. Default classes are attached to the backdrop and I can't find any solution.

**Comment by zoltanszogyenyi** [comment]
Hello @Ravikisha,

For the `v1.6.0` update I can confirm that it works and I think that for `v1.5.5` should work too as I made no breaking changes. Make sure that the options object is passed correctly and that the modal is initiated.

Here's an example:

TypeScript / JavaScript example: https://github.com/themesberg/tailwind-typescript-starter/blob/main/src/modal.ts
HTML markup example: https://github.com/themesberg/tailwind-typescript-starter/blob/main/examples/modal.html

Everything that you change inside the `backdropClasses` key value pair will be changed, for example updating `bg-gray-900` to `bg-red-900`.
