### ISSUE TITLE
Node Express EJS Template Engine can not get Flowbite JavaScript

### ISSUE THREAD

**Issue by mhasanmeet** [themesberg/flowbite#375]
**Describe the bug**
I am using Flowbite in my Node Express project where I'm using Flowbite as Tailwind Plugin. But, Node Express EJS Template Engine can not get Flowbite JavaScript. It can not dismiss the alert element, and more where JS needs to work. 

**To Reproduce**
1. Install Flowbite, add ```"./views/**/*.ejs"``` in tailwind config file, add ```require('flowbite/plugin')``` in tailwind config file
2. add flowbite JavaScipr file in ejs footer
3. added flowbite component 
4. compile tailwind and JavaScript is not working

**Expected behavior**
When clicking in Alert components close dismissal, the component should be removed from the view file 

**Screenshots**
![image](https://user-images.githubusercontent.com/24842666/209810913-efa53eda-4696-4e15-8f36-9a9d028658eb.png)
![image](https://user-images.githubusercontent.com/24842666/209810954-c2e3870c-b8c5-47d7-a015-b1fe3ea3fc98.png)
![image](https://user-images.githubusercontent.com/24842666/209810982-e39c6aa4-3bef-4837-a341-2a2a026a53e8.png)
![image](https://user-images.githubusercontent.com/24842666/209811035-902517d7-a73d-4545-9aa8-c2a9a1159daa.png)
![image](https://user-images.githubusercontent.com/24842666/209811108-119fe91c-b39e-4647-9907-d749025d677c.png)
![Screenshot_4](https://user-images.githubusercontent.com/24842666/209811342-31fdcf50-b6b0-47d3-8456-59fb833147dc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 108

**Comment by zoltanszogyenyi** [comment]
Hello @mhasanmeet,

Thanks for describing the issue with examples - we have recently launched `v1.6.0` for Flowbite. Can you please upgrade and see if the issues persist? We've made lots of improvements to the JS dist files.

**Comment by zoltanszogyenyi** [comment]
I'll close this issue until further notice @mhasanmeet. Feel free to re-open it if the issue persists.
