### ISSUE TITLE
Display a notification message globally.

### ISSUE THREAD

**Issue by ayushete02** [themesberg/flowbite#380]
**How it is used**
To display a notification message at any of the four corners of the viewport. Typically it can be used in the following cases:

A notification with complex content.
A notification providing a feedback based on the user interaction. Or it may show some details about upcoming steps the user may have to follow.
A notification that is pushed by the application.

**Comment by zoltanszogyenyi** [comment]
Hello @ayushete02,

Currently we have the [toast component](https://flowbite.com/docs/components/toast/) which has a pretty similar function as to what you're describing, but we do need to work on the JS API capabilities (ie. showing it programatically not just dismissing it).

We have a few issues opened up for this - if the toast component that I've described here does not meet your expectations please re-open the issue with some examples and screenshots of what you'd like to see.

Cheers,
Zoltan
