### ISSUE TITLE
Allow active/inactive class overrides for tabs

### ISSUE THREAD

**Issue by lizabbey** [themesberg/flowbite#381]
**Is your feature request related to a problem? Please describe.**
The accordion component allows for overrides of active and inactive classes but the tab component does not. This requires rewriting a good portion of the js to initialize with alternate styling.

**Describe the solution you'd like**
I would like to pass options to the tabs component to set custom active and inactive classes.

**Describe alternatives you've considered**
I'm currently initializing with js resulting in duplicated code.

**Comment by zoltanszogyenyi** [comment]
Hey @lizabbey,

This feature request makes a lot of sense - so we'll add it to our roadmap.

Thanks!

**Comment by DontPlayTheGame** [comment]
> The accordion component allows for overrides of active and inactive classes but the tab component does not. This requires rewriting a good portion of the js to initialize with alternate styling.
> 

You don't need to rewrite the js. 
Just use a stronger CSS selector to overwrite. 
---- 
The main problem is with the tab component, that flowbite adds the default css classes anyway. 
---- 
You can add your own class, and flowbite will put your class somehere (that's the problem!) into the class list. 
Initialize a new tab with; 
const options = {
				defaultTabId: 'my-default-tab',
				activeClasses: 'my-tab-item-active',
				inactiveClasses: 'my-tab-item',
				onShow: () => {}
			};

This will put the "my-tab-item-active" and "my-tab-item" somewhere into the class list:
<button class="inline-block p-4 border-b-2 rounded-t-lg **my-tab-item-active** text-blue-600 hover:text-blue-600 dark:text-blue-500 dark:hover:text-blue-500 border-blue-600 dark:border-blue-500" ....  >
Use now #my-page-id .my-tab-item-active { ... } to overwrite the weaker class definitions from flowbite.

**Comment by karpushchenko** [comment]
@DontPlayTheGame I don't think adding styles with #id selectors is a good solution for us. 
Currently, custom inactiveClasses are added together with default classes and it doesn't work fine for me if I have similar class types, like text colors and font weights

**Comment by zoltanszogyenyi** [comment]
Hey everyone! The next release for `v2.3` will include two new data attributes that will allow you to update the active and inactive classes using Tailwind CSS classes (https://github.com/themesberg/flowbite/commit/55f568773a1bfc7a5ba189556f84b56cd1db9f8e):

<img width="873" alt="Screenshot 2024-02-07 at 12 52 11" src="https://github.com/themesberg/flowbite/assets/8052108/0b1c899d-ec85-4af2-840e-9ced2c103899">

Cheers,
Zoltan
