### ISSUE TITLE
Determine if Escape key closes the modal or not. 

### ISSUE THREAD

**Issue by cratag** [themesberg/flowbite#392]
I'm using the [default modal](https://flowbite.com/docs/components/modal/) and I set the modal to static:

```
const twoFactorModal = new Modal(modalEl, {
  placement: 'center',
  backdrop: 'static'
});
```

Unfortunately it hides when pressing the Escape key. I would like to choose if I want this to occur.

I 'fixed' it as such:
```
    const twoFactorModal = new Modal(modalEl, {
        placement: 'center',
        backdrop: 'static',
        onHide: () => {
            twoFactorModal.show()
        },
    });
```
but I believe some function on your side would be cleaner.

**Comment by zoltanszogyenyi** [comment]
Hello @cratag,

I think we could introduce a new option such as `closable: {true|false}` because static actually refers to what happen when you click on the backdrop element.

I'll introduce this in `v1.6.2` most likely.

Cheers,
Zoltan

**Comment by Overx** [comment]
I have the same happening with the drawer, any solution?

**Comment by desprit** [comment]
Any plans on making this part customizable?
https://github.com/themesberg/flowbite/blob/main/src/components/drawer/index.ts#L66
