### ISSUE TITLE
Write Remix integration guide

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite#393]
**Is your feature request related to a problem? Please describe.**

Write an integration guide on the official documentation for using Remix, Tailwind CSS, and Flowbite.

**Describe the solution you'd like**

Create a new `remix.md` file and based on the structure of other integration guides (ie. [TypeScript](https://flowbite.com/docs/getting-started/typescript/)) write a guide using this structure:

1. Introduction to Remix & what companies use it
2. Create a new Remix project
3. Install and configure Tailwind CSS with Remix
4. Install and configure Flowbite
5. Showcase Flowbite components and example
6. Starter project repository with MIT License

**Describe alternatives you've considered**

None.

**Additional context**

The Remix guide should most likely be based on [Flowbite React](https://github.com/themesberg/flowbite-react) rather than the main library for obvious reasons.

@tulup-conner created a [Remix starter](https://github.com/tulupinc/flowbite-remix-starter) a while ago but I'm not sure if it works with the latest version of Flowbite React - has to be verified.

**Comment by tulup-conner** [comment]
It works yeah, I use this configuration for my startup

**Comment by zoltanszogyenyi** [comment]
Hey @tulup-conner,

The guide shouldn't be for the vanilla library - it should be based on Flowbite React.

So if your starter configuration works then there's no need to build a starter anymore, just write the integration guide!

**Comment by zoltanszogyenyi** [comment]
I'll take on this one 😈

@tulup-conner I'll use your starter for reference - I might ping you if there's a need for an update.

Cheers,
Zoltan
