### ISSUE TITLE
Write Blazor .NET integration guide

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite#395]
**Is your feature request related to a problem? Please describe.**

Write an integration guide on the official documentation for using [Blazor](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor), Tailwind CSS, and Flowbite.

**Describe the solution you'd like**

Create a new `blazor.md` file and based on the structure of other integration guides (ie. [TypeScript](https://flowbite.com/docs/getting-started/typescript/)) write a guide using this structure:

1. Introduction to Blazor & what companies use it
2. Create a new Blazor project
3. Install and configure Tailwind CSS with Blazor
4. Install and configure Flowbite
5. Showcase Flowbite components and example
6. Starter project repository with MIT License

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by zoltanszogyenyi** [comment]
Hey @CatherineKiiru,

That would be more than awesome! Together with @tdashworth we've started a [Flowbite Blazor](https://github.com/themesberg/flowbite-blazor) library which would be more than suitable to have a standalone integration based on the core UI components from Flowbite - so the current guide should at least specify that library.

Otherwise, you can start working on this issue by first writing a guide on how to create a new Blazor project, how to install Tailwind CSS, how to install Flowbite and showcase the usage of some of the components from Flowbite.

A starter repository would also be useful!

Cheers,
Zoltan

**Comment by CatherineKiiru** [comment]
Thank you, I'll work on it. Do you have a deadline preference?

**Comment by zoltanszogyenyi** [comment]
Hey @CatherineKiiru,

Take your time, there's no rush or deadlines :)

Cheers,
Zoltan

**Comment by CatherineKiiru** [comment]
> Any timeline to have this in place? Thanks in advance.

I am working on it and plan to complete this guide in June.

**Comment by famda** [comment]
I was really hoping that I was able to setup a base project to start working on critical project with flowbite.

Did you find a way to init flowbite on a blazor wasm project?

If you do, you could share some details here and I can do the rest of the heavy lifting on the blazor side.

Thanks in advance.

**Comment by jsukhabut** [comment]
@famda  I follwed these steps to setup my project for Tailwinds
https://www.youtube.com/watch?v=enE3omOdzZc

I am trying to integrate flowbite now.

@CatherineKiiru  if you have anything please share.

**Comment by CatherineKiiru** [comment]
Hi @jsukhabut I'll share once I am done
