### ISSUE TITLE
[Modal] Reinit dynamic button with data-modal-target attribute to open a modal

### ISSUE THREAD

**Issue by jloguercio** [themesberg/flowbite#403]
I have buttons in a list created dynamically that using data-modal-target attribute to open a certain modal with some information.

After the list is updated the buttons stop working.

Theres a way to re-attach the event to the buttons?

Regards

**Comment by dev-charles15531** [comment]
Is your modal also created dynamically?

**Comment by jloguercio** [comment]
> Is your modal also created dynamically?

No

**Comment by jloguercio** [comment]
> Is your modal also created dynamically?

No, just a single modal

**Comment by dev-charles15531** [comment]
Can i see this list, and how you're updating it?

**Comment by jloguercio** [comment]
its just a simple list 

`<button
                                    data-id="{{ $id }}"
                                    data-modal-target="folderEdit"
                                    data-modal-toggle="folderEdit"
                                    type="button"
                                    class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded-l active:z-1 focus:z-1 -mr-px border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                                    <i class="fa-solid fa-pencil fa-fw"></i>
                                </button>
                                <button
                                    data-id="{{ $id }}"
                                    data-modal-target="folderEdit"
                                    data-modal-toggle="folderEdit"
                                    type="button"
                                    class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded-l active:z-1 focus:z-1 -mr-px border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                                    <i class="fa-solid fa-pencil fa-fw"></i>
                                </button>
                                <button
                                    data-id="{{ $id }}"
                                    data-modal-target="folderEdit"
                                    data-modal-toggle="folderEdit"
                                    type="button"
                                    class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded-l active:z-1 focus:z-1 -mr-px border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                                    <i class="fa-solid fa-pencil fa-fw"></i>
                                </button>
                                <button
                                    data-id="{{ $id }}"
                                    data-modal-target="folderEdit"
                                    data-modal-toggle="folderEdit"
                                    type="button"
                                    class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded-l active:z-1 focus:z-1 -mr-px border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                                    <i class="fa-solid fa-pencil fa-fw"></i>
                                </button>`
                                
                                Updated vía simple AJAX

**Comment by jloguercio** [comment]
Its just a simple list in a foreach updated via ajax


`@foreach($ids as $id)
<button
                                    data-id="{{ $id }}"
                                    data-modal-target="folderEdit"
                                    data-modal-toggle="folderEdit"
                                    type="button"
                                    class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded-l active:z-1 focus:z-1 -mr-px border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                                    <i class="fa-solid fa-pencil fa-fw"></i>
                                </button>
@endforeach`

**Comment by dev-charles15531** [comment]
I tried creating a code similar to yours and encountered the same issue. But i got around it and had it work by using javascript to toggle the modal instead of the normal element attribute method.
This should be workable as i see you're using laravel

**Comment by Kenura-R-Gunarathna** [comment]
THank you @dev-charles15531. Your solution really helped me to save time.

**Comment by zoltanszogyenyi** [comment]
Hey peeps,

Flowbite v2.0 now introduces a new Instances Manager which allows you to access the instance of the object that are created via data attributes. Please read more about this here:

https://flowbite.com/docs/getting-started/javascript/
https://github.com/themesberg/flowbite/releases/tag/v2.0.0

Cheers,
Zoltan
