### ISSUE TITLE
Inconsistency of the new Indicator component

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#408]
**Describe the bug**
No consistency within the examples of the `Indicator` component:
- colors
- positioning
- purpose

## Colors
[Default indicator](https://flowbite.com/docs/components/indicators/#default-indicator) defines 9 different colors of the indicators, that are not reused in the few following examples.
- `bg-teal-400` vs. `bg-teal-500` just in the next example
- `bg-green-400` vs. `bg-green-500` and `bg-red-400` vs. `bg-red-500` in Status indicator
- `bg-blue-200` vs `bg-blue-500` in Stepper indicator

**Expected behavior**
Flowbite should define a certain palette of colors and keep that through out the components so they look consistent when put one next to the other.

## Position
Section [Indicator position](https://flowbite.com/docs/components/indicators/#indicator-position) gives the hints how to use `translate-{x|y}-{number}` classes to position the indicator on top of it's parent.

However, neither [Indicator count](https://flowbite.com/docs/components/indicators/#indicator-count) nor [Status indicator](https://flowbite.com/docs/components/indicators/#status-indicator) examples don't follow those rules. Those use the ad-hoc `top`, `left`, `right` classes that have to be fine tuned each time you play with the size of indicator or it's parent.

**Expected behavior**
Unified and consistent way of positioning the indicators on the borders of their parents.

## Purpose
What is the indicator component? Initially you have an impression that indicator is a colorful dot, sometimes with some element inside, that is positioned around other elements to show some secondary information.

However in [Loading indicator](https://flowbite.com/docs/components/indicators/#loading-indicator) we find out that it's no different from the Badge and in [Spinner indicator](https://flowbite.com/docs/components/indicators/#spinner-indicator) we learn it's just another name for the Spinner.

**Expected behavior**
Move the Badge and the Spinner examples to the appropriate component sections.

---

_Flowbite - consistently inconsistent._

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

Thanks for reporting this issue and being one of the active contributors of Flowbite Svelte.

I've reached out to @robert1508 (designer of Flowbite) and indeed your remarks about the difference in colors is true so we'll patch this up for the next minor release.

Regarding the positioning, indeed in the latest version of positioning we tried to use translate instead of just `top` or `right` and we will update all of these positioning to mostly use the `translate` method as it is a preferred way to position elements without having to tweak with the absolute positioning (translate allows us to center the component in question regardless of the size of it).

If there are any other inconsistencies that you've seen please report them and we'll sort them out - the library grew quite a bit in size and sometimes it's hard to track these differences from one component to another as we decouple them from a standard single CSS file.

Cheers,
Zoltan

**Comment by jjagielka** [comment]
Yes, there are more inconsistencies. Even the button used at that indicator example is not any of the buttons defined in the buttons section: `p-3` used instead of `px-5 py-2.5` so the size is strange.

I contribute to `flowbite-svelte` and when building there the library of component those inconsistencies make my life difficult. I've already flag you few of those, but I will report more, be sure. :)

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

We are currently doing a revamp of some things that we also identified and will try to bring consistency across all of the components based on the Figma design system.

That and for future components we’ll take this into account in a more rigorous manner.

Cheers,
Zoltan

**Comment by jjagielka** [comment]
Another note about `Indicator`. 

Before it was introduced there was [Notification badge](https://flowbite.com/docs/components/badge/#notification-badge). So now we have identical examples in two places: once called `badge`, once `indicator`.

**Comment by jjagielka** [comment]
But the [Notification badge](https://flowbite.com/docs/components/badge/#notification-badge) example shown in the `badge` section is not consistent with color palette of other badges, in the dark mode it does not change colors, it is floating and has no padding. 

>  _"If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck."_

That example does not pass the duck test. Bottom line: it's not a badge.

**Comment by robert1508** [comment]
Issues related to color inconsistencies have been resolved.

**Comment by jjagielka** [comment]
Default indicator: `bg-green-500`
Status indicator: `bg-green-400`

**Comment by zoltanszogyenyi** [comment]
@jjagielka updated to `bg-green-500` - this should be all.
