### ISSUE TITLE
Tooltip not showing intermitently

### ISSUE THREAD

**Issue by mlevit** [themesberg/flowbite#411]
**Describe the bug**
I'm utilising the tooltip function and I've noticed that ever second or third refresh the tooltips will stop working. Looking at the source code I noticed that the following element style is added programatiically to the tooltip on page load, but this isn't always done. When it fails the tooltips don't work:

```html
style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate(-28px, -23px);"
```

I recorded a [video](https://www.recordjoy.com/view/OS1KUNQymR4PWUgr5rXE) showing this behavior. The password is `life`.

**To Reproduce**
N/A

**Expected behavior**
The tooltip should show up on hover.

**Screenshots**
[Record video](https://www.recordjoy.com/view/OS1KUNQymR4PWUgr5rXE) with a password of `life`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 108.0.5359.124

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hello @mlevit,

Interesting bug, what tech stack are you using? Are you sure that the DOM is loaded before these tooltip initialization is attached to the trigger elements?

Cheers,
Zoltan

**Comment by mlevit** [comment]
Hey @zoltanszogyenyi. It's a single HTML page design basically. There's an input file that is read in and HTML elements are generated from the file.

I'm assuming now that that has something to do with this? Since the elements may not be present when Flowbite is loaded and therefore won't be initialised properly? If that is the case, what's the workaround? Can I defer the loading of the Flowbite script till after my JS has run?

**Comment by mlevit** [comment]
So I've added this

```html
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", () => {
    var headID = document.getElementsByTagName("head")[0];
    var newScript = document.createElement("script");
    newScript.type = "text/javascript";
    newScript.src =
      "https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.2/flowbite.js";
    headID.appendChild(newScript);
  });
</script>
```

which looks like has _maybe_ helped... but honestly could be a placebo.

**Comment by CorwinDev** [comment]
Hi @mlevit,

Could you try to include the flowbite js on the end of the body? Because right now its in the header.

**Comment by mlevit** [comment]
Ended up moving to Vue.js with Flowbite, all working well now :)
