### ISSUE TITLE
Navbar onToggle callback failed

### ISSUE THREAD

**Issue by 4o3F** [themesberg/flowbite#414]
**Describe the bug**
For Collapse `onToggle` callback function won't be called

**To Reproduce**
1. Create a new collapse for instance
```
new Collapse(userMenu.value, userMenuTrigger.value, {
    onExpand: () => {
      console.log('element has been expand')
    },
    onToggle: () => {
      console.log('element has been toggled')
    }
  });
```
2. click on it and `onToggle` won't be called while `onExpand` will be called

**Expected behavior**
`onToggle` function would be called

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [109.0.5414.74]

**Additional context**
After a quick view of source, I noticed in file `/src/components/collapse/index.ts` on L67 [(direct link)](https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L67) there's no call to the callback function

**Comment by zoltanszogyenyi** [comment]
Hey @LykorisR,

Thanks for the report and the PR - I'll check this out in the next few days and merge it. Will be released in `v1.6.3`.

Cheers,
Zoltan
