### ISSUE TITLE
Feature: Date range picker: Max/min date 

### ISSUE THREAD

**Issue by leoplct** [themesberg/flowbite#417]
**Is your feature request related to a problem? Please describe.**
The user is able to selected only a date within a specific range. Other days are disabled. For example, it must now allowed to selected a date in the future or earlier a certain date.

Example: https://www.daterangepicker.com/#options
- minDate: (Date or string) The earliest date a user may select.
- maxDate: (Date or string) The latest date a user may select.

**Describe the solution you'd like**
It must be specified at HTML level so it's customizable for user-specific range (server-rendered page, JS bundling).
```
<div date-rangepicker>
  <input datepicker-maxdate="2023-12-31" datepicker-mindate="2023-01-01" name="start" type="text" class="" placeholder="Select date start">
</div>
```

**Comment by aarushisoni** [comment]
Hi, is this issue still open?
I want to work on this issue; please assign me to this.

**Comment by tanami20** [comment]
@zoltanszogyenyi  - can we assign to @aarushisoni  - or is someone able to do this? I would love to have this feature. 
I've integrated using Laravel Jetstream but would prefer to stick with data tags.

**Comment by bk-one** [comment]
+1 on this

**Comment by eliasbraun** [comment]
Would be super helpful!

**Comment by AnatoleT** [comment]
Hi guys, is it already added to the component ? It would me super helpful :)

**Comment by tanami20** [comment]
Can we get this via the data tags? its essential for a date-time picker.

**Comment by tanami20** [comment]
Does anyone recommend something else if this function doesn't exist? it is very common to want to have this.

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

The max and min date settings are now available via the new Flowbite Datepicker API:

https://flowbite.com/docs/components/datepicker/#max-and-min-dates

Cheers,
Zoltan
