### ISSUE TITLE
How to fix cannot find module flowbite-datepicker/Datepicker unittest 

### ISSUE THREAD

**Issue by kraison1** [themesberg/flowbite#418]
I run unittest with commend npx jest (Reactjs)
but if run with npm run start can be used normally

First error :
 Test suite failed to run 
   error message: Cannot find module 'flowbite-datepicker/Datepicker'

Second error :
  TypeError: _datepicker.default is not a constructor

**Comment by zoltanszogyenyi** [comment]
Hey @kraison1,

My understanding is that you are trying to use the datepicker components with React.js.

Please check out this repository built by one of our community members to integrate it with React.js: https://github.com/OMikkel/tailwind-datepicker-react

Cheers,
Zoltan

**Comment by kraison1** [comment]
Thank you very much, I've been looking for a way to do it for hours.

ในวันที่ พฤ. 19 ม.ค. 2023 เวลา 23:14 Zoltán Szőgyényi <
***@***.***> เขียนว่า:
