### ISSUE TITLE
Long load times and slow interaction when several tooltip components on same page

### ISSUE THREAD

**Issue by anderslutzhoft** [themesberg/flowbite#419]
**Describe the bug**

When having eg. 10 individual tooltip components on the same page, page load times increases and hover interactions are slow.

Looping 100 items will crash the browser.

**To Reproduce**
Using the basic tooltip examples from documentation.
I'm using vue and using a v-for loop to create 10 items. Each button and tooltip have a unique id using the index of the v-for loop.

**Expected behavior**
Fast and smooth load times and interactions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser:  chrome + safari, safari being a bit faster.

**Comment by anderslutzhoft** [comment]
May not be relevant. After further testing, it might be related to the specific project I'm working on.

**Comment by anderslutzhoft** [comment]
I found a fix.
My issue was that I ran the initTooltip() on every instance of a sub-component approximately 100's of times.
Removing the init and placing it in a parent component solved the issue.

Sorry for potentially wasting anyone's time!

**Comment by zoltanszogyenyi** [comment]
Hey @anderslutzhoft,

Thanks for reporting a potential issue - no worries, perhaps somebody else will face this and reading your case will help them figure out the root of the problem faster.

I'll close this issue until further notice.

Cheers,
Zoltan
