### ISSUE TITLE
Alerts - inconsistency

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#423]
**Describe the bug**
A few inconsistencies in the updated `Alert` component:

## Yellow
- Light mode: `text-yellow-700` - in all cases - OK
- Dark mode: `dark:text-yellow-300` in few cases and `dark:text-yellow-400` in the others - why two versions

## Backgrounds
Alert backgrounds are set to `bg-{color}-100` in all examples apart from [Bordered alerts](https://flowbite.com/docs/components/alerts/#bordered-alerts) where those are set to `bg-{color}-50`. Do we need that anomaly? I think that with `100` it looks OK as well.

## Borders
Dark alert border is less contrasted then the others. And in fact it is `border-gray-200` while consistently it should be `border-gray-300`.

## Close buttons
[Dismissing](https://flowbite.com/docs/components/alerts/#dismissing) section define the close buttons as:
`dark:text-blue-400` and `dark:text-green-400`
and just in the following section [Border accent](https://flowbite.com/docs/components/alerts/#border-accent)
`dark:text-blue-300` and `dark:text-green-300`

## [Additional content](https://flowbite.com/docs/components/alerts/#additional-content)     
- text color: while yellow and green are consistent `text-{color}-700`, suddenly blue and red are `text-{color}-900`
- background colors, again strange `bg-{color}-50`
- button colors in dark mode not consistent with neither text nor with border (especially visible in `dark:red`)

---

_Flowbite - consistently inconsistent._

**Comment by zoltanszogyenyi** [comment]
Hello @robert1508,

You've made some adjustments to the alert component a few days ago - have these been addressed?

Cheers,
Zoltan

**Comment by robert1508** [comment]
A large part of them have already been solved, and I managed to finish the others now.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

I've pushed and deployed the changes made by @robert1508 - at a first glance I think the inconsistencies have been taken care of. Can you please check them and close the issue if there is nothing else to report?

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

I've verified these and can say that the inconsistencies have been resolved - feel free to re-open if I'm not correct.

- yellow color inconsistencies now all use `dark:text-yellow-300`
- background in light mode now all use `bg-{color}-50` most likely to increase contrast (@robert1508 correct me if I'm wrong)
- the border color has been increased to `bg-{color}-300` to increase contrast
- close button colors are now consistent between the two sections
- text colors on light mode now all use `text-{color}-800`

Cheers,
Zoltan

**Comment by jjagielka** [comment]
Hey @zoltanszogyenyi , @robert1508 

Thanks for those changes. Much more consistent now, although, in my humble opinion, changing background colors to 50 was not a good move. The backgrounds are too pale now and text is too much in contrast. Personally I liked those much better with `bg-{color}-100` and `text-{color}-700`.

---
Yellow and gray dark text color are different from the others. Probably on purpose, but I think that with 400 they would look equally good.
```js
const textColors = {
    blue: 'text-blue-800 dark:text-blue-400',
    red: 'text-red-800 dark:text-red-400',
    green: 'text-green-800 dark:text-green-400',
    yellow: 'text-yellow-800 dark:text-yellow-300',  // why not dark:text-yellow-400 ?
    gray: 'text-gray-800 dark:text-gray-300' // why not dark:text-gray-400 ?
}
```
I'm assuming that with other Flowbite colors (as used in badges: indigo, pink, purple) I should use the scheme `text-{color}-800 dark:text-{color}-400` rather then 300 version. Correct?

---
And finally the close buttons. 
Their behaviour is different here (in alerts) then in badges, toasts, drawer, modal.
Here, on hover only background changes, while in other places text color is boosted as well.

Close button text color is set to `text-{color}-500` and as such is different from the alert text color. Shouldn't it be inherited and changed only while hovered?
