### ISSUE TITLE
<Link> component left in Block documentation.

### ISSUE THREAD

**Issue by oliwerbig** [themesberg/flowbite#425]
**Describe the bug**
It's not a bug, just a Link component left in a Block-code, where a simple anchor tag should be.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://flowbite.com/blocks/marketing/faq/'
2. Click on 'Show code' of the default example
3. You can see two occurrences of Link instead of an anchor tag

**Expected behaviour**
It shouldn't contain components without a hint of what library it is imported from.

**Comment by zoltanszogyenyi** [comment]
Hey @oliwerbig,

Thanks for the notice - we'll update these two blocks soon.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
@oliwerbig fixed and deployed - thanks!
