### ISSUE TITLE
Import only components that I used

### ISSUE THREAD

**Issue by balex25** [themesberg/flowbite#433]
Hello,

How can I import only components that I used and not all from flowbite?

On old versions, I used this code:

 import "../node_modules/flowbite/src/components/tooltip.js";
 import "../node_modules/flowbite/src/components/popover.js";
 import "../node_modules/flowbite/src/components/tabs.js";

Regards,
Alex

**Comment by zoltanszogyenyi** [comment]
Hey @balex25,

Please try importing the components like this:

```
import { Modal } from 'flowbite';
```

Cheers,
Zoltan
