### ISSUE TITLE
new component: DateTimePicker

### ISSUE THREAD

**Issue by djohts** [themesberg/flowbite#435]
I'd like to see DateTimePicker component in Flowbite. Something like [Mui](https://mui.com/x/react-date-pickers/date-time-picker) has.

**Comment by vagkalosynakis** [comment]
Yes. I am not sure why it is not included since the [documentation itself for the DatePicker](https://flowbite.com/docs/plugins/datepicker/), literally starts with:

> Start receiving date and ***time*** data from your users.

It feels like they started implementing it but they just haven't finished it yet.

**Comment by apphancer** [comment]
The documentation is quite confusing. I was under the impression that the datepicker included the time part as the documentation mentions date and time in the very first line in its page. Looking into the rest of the page then I could not find any reference to time and had to try it out hoping I could get it to work.

**Comment by Xstoudi** [comment]
Any update on this one? Documentation is still misleading.

**Comment by zoltanszogyenyi** [comment]
We now have a timepicker component: https://flowbite.com/docs/forms/timepicker/.

**Comment by NathanVG** [comment]
@zoltanszogyenyi I was looking at the component docs and was wondering if there is an option for 24h clock or is AM/PM the only option?
