### ISSUE TITLE
datepicker listens to 'changeDate' instead of 'change'

### ISSUE THREAD

**Issue by fabiot21** [themesberg/flowbite#443]
**Describe the bug**
When using svelte with flowbite datepicker, I am trying to bind the value from the user input to the component. But the problem is that the datepicker.js handles onChangeDate instead of a standard DOM onChange. So typescript gives me error when implementing the function.

The ts error is:
```
Argument of type '{ name: string; type: "text"; class: string; placeholder: string; "on:changeDate": (e: any) => void; value: string; }' is not assignable to parameter of type 'HTMLProps<"input", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"on:changeDate"' does not exist in type 'HTMLProps<"input", HTMLAttributes<any>>'.ts(2345)
```

**To Reproduce**
1. Init a svelte project
2. import datepicker.js
3. use the input flowbite datepicker
4. try to handle user input using "on:changeDate={(e) => inputDate = e.target.value}"

**Expected behavior**
The expected behaviour is that datepicker.js listens to "change" instead of "changeDate"

**Additional context**
I might be wrong but flowbite-svelte should be having the same problem.

**Comment by puruzio** [comment]
@fabiot21 Have you found a work around?

**Comment by fabiot21** [comment]
nope, i ended up creating my own datepicker

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

We have made a big update to the datepicker API that allows you to change and set dates, amongst other things:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour

Cheers,
Zoltan
