### ISSUE TITLE
Install with Nuxt – safelist/css missing including backdrop for modals/drawer

### ISSUE THREAD

**Issue by timothymarois** [themesberg/flowbite#448]
**Describe the bug**

Backdrop CSS and other CSS is missing because of JIT, the safelist provided on flowbite is missing dozens of css

**To Reproduce**
1. go here https://flowbite.com/docs/getting-started/nuxt-js/
2. Flow steps
3. On app.vue add the modal example or drawer example. 

**Expected behavior**
Backdrop should work, it doesn't. other CSS is not included because of JIT

**Comment by zoltanszogyenyi** [comment]
Hey @timothymarois ,

I believe you can easily fix this by adding the Flowbite JS paths to `tailwind.config.js`:

```
module.exports = {

    content: [
        "./node_modules/flowbite/**/*.js"
    ]

}
```

Source: https://flowbite.com/docs/getting-started/quickstart/

Cheers,
Zoltan
