### ISSUE TITLE
Install with Nuxt – Backdrop on drawer doesnt go away, user needs to refresh

### ISSUE THREAD

**Issue by timothymarois** [themesberg/flowbite#449]
**Describe the bug**
Backdrop is stuck on drawer when clicking it to close the drawer 
The drawer does close, but backdrop does not go away

**To Reproduce**
1. Go to https://flowbite.com/docs/getting-started/nuxt-js/
2. Follow steps to install
3. Add a drawer example to app.vue

**Expected behavior**
Clicking the backdrop should remove the backdrop with closing the drawer

**Comment by zoltanszogyenyi** [comment]
Hey @timothymarois,

I think this has to do with https://github.com/themesberg/flowbite/issues/454 more or less as the backdrop methodology is the same as for the modal.

Cheers,
Zoltan

**Comment by timothymarois** [comment]
@zoltanszogyenyi This Might be true, when I submitted this one, I didn't find the other issue yet, so its most likely double backdrops going on and this issue is related to closing one backdrop by having the other still shown. I'll close this one.
