### ISSUE TITLE
Flowbite ignores tailwind prefixes

### ISSUE THREAD

**Issue by AstrisDev** [themesberg/flowbite#452]
**Describe the bug**
Collapse and other components don't work when tailwindcss prefix is set.

Issue [https://github.com/themesberg/flowbite/issues/132](https://github.com/themesberg/flowbite/issues/132) still not fixed.

**To Reproduce**
_Steps to reproduce the behavior:_

- Setup prefix in the tailwind.config.js:

```
module.exports = {
  prefix: "tw-",
  ...
}
```

- Create a navbar component https://flowbite.com/docs/components/navbar/
- Add prefixes to default styles
- Launch your app and see how button to show menu when display is small  is not working

**Expected behavior**
Components support custom prefixes

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome, Opera, etc
Additional context
Components have default tailwindcss classes hardcoded: [https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L36](https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L36)
[https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L46](https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L46)
[https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L57](https://github.com/themesberg/flowbite/blob/main/src/components/collapse/index.ts#L57)
 and there is no prefix injection there

**Comment by zoltanszogyenyi** [comment]
Hey @AstrisDev,

Thanks for your report - we actually have this in progress and probably will be deployed for `v1.7.0`.

https://github.com/themesberg/flowbite/issues/132

Cheers,
Zoltan
