### ISSUE TITLE
Svelte Flowbite.js interactivities

### ISSUE THREAD

**Issue by Andre7th** [themesberg/flowbite#456]
Thank for the project!
**Svelte** Integration Second Option Flowbite.js: I would like to say that, the Flowbite.js should work without needing to re-executed in every page...

**Comment by zoltanszogyenyi** [comment]
Hello @Andre7th,

Thanks for using the open-source Flowbite library!

I believe you're using Svelte so in my opinion it would be best if you used the dedicated library: [Flowbite Svelte](https://github.com/themesberg/flowbite-svelte).

Still - if you want to use the core library you might have to use the `init` functions to set up the data attributes.

Cheers,
Zoltan

**Comment by t-mish** [comment]
@zoltanszogyenyi What does it mean to set up the data attributes in this case?

**Comment by zoltanszogyenyi** [comment]
> @zoltanszogyenyi What does it mean to set up the data attributes in this case?

For example in Vue you can use the `onMounted` lifecycle method to hook onto the event when the component has been rendered at which point you can call the `initFlowbite()` function to set up the event listeners for the HTML elements that have the data attributes.

Here's a bit more info regarding this: https://flowbite.com/docs/getting-started/quickstart/#init-functions

**Comment by t-mish** [comment]
What about Sveltekit?
