### ISSUE TITLE
The utility `w-[calc(100%-theme('spacing[some_key][1.5]'))]` contains an invalid theme value and was not generated.

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#488]
[Banner component](https://flowbite.com/docs/components/banner/#marketing-cta-banner) uses `w-[calc(100%-2rem)]` in the first div. 
When I use this in a SvelteKit, it warns the following message:

```
The utility `w-[calc(100%-theme('spacing[some_key][1.5]'))]` contains an invalid theme value and was not generated.
```

**Expected behavior**

No warning.

**Screenshots**

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/147320/224865059-927e542e-b5fc-4726-a042-e9fbdca775bf.png">

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

Which version of Tailwind CSS is being used for Flowbite Svelte?

Cheers,
Zoltan

**Comment by shinokada** [comment]
```
"tailwindcss": "^3.1.5",
"flowbite": "^1.6.3",
```

**Comment by zoltanszogyenyi** [comment]
@shinokada it's weird because for our compilation process it doesn't throw a warning or error and it even applies the CSS.

Check this out: https://benborgers.com/posts/tailwind-calc

**Comment by shinokada** [comment]
Thanks. It doesn't show anymore in my local dev.

**Comment by TristanBrotherton** [comment]
I am getting this warning in my build as well. I'm using Tailwind CSS v3.3.2

**Comment by elliason** [comment]
I am also getting this warning while dev building next.js with tailwind. Using "tailwindcss": "3.3.2". This is my config:
`/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "../../packages/ui/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  plugins: [require("@tailwindcss/forms")],
  theme: {
    fontSize: {
      xs: ["0.8125rem", { lineHeight: "1.5rem" }],
      sm: ["0.875rem", { lineHeight: "1.5rem" }],
      base: ["1rem", { lineHeight: "1.75rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "2rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "3.5rem" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)"],
        mono: ["var(--font-roboto-mono)"],
      },
    },
  },
};
`

**Comment by Tucker-Eric** [comment]
@elliason Just ran into this and it looks like your config line `"../../packages/ui/**/*.{js,ts,jsx,tsx}",` is what's doing it. (I had a similar issue) and that is includes `../../packages/ui/node_modules` which has tailwind installed and [attempst to parse this comment](https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/defaultExtractor.js#L134) and fails.

I've updated my path to move the related package to a `src` directory  `"../../packages/ui/src/**/*.{js,ts,jsx,tsx}",` and it worked.

**Comment by andresgutgon** [comment]
Very helpful @Tucker-Eric thanks!

**Comment by tarun-themesbrand** [comment]
I am also facing the same issue.

`module.exports = {
    darkMode: ['class', '[data-mode="dark"]'],
    content: ["./src/**/*.{html,scss,js}"],
    important: true,
    theme: {
        screens: {
            xs: "100%",
            sm: '540px',
            md: '720px	',
            lg: '960px',
            xl: '1140px',
            '2xl': '1320px',
        },
        container: {
            padding: '0.625rem',
        },
        fontFamily: {
            primary: ['Public Sans', 'sans-serif'],
        },    
    },
}  `
