### ISSUE TITLE
Public getActiveItem for the carousel

### ISSUE THREAD

**Issue by gberaudo** [themesberg/flowbite#491]
There is currently no public way to retrieve current position of the carousel.
It makes the carousel a black box, unless one is OK to use the private `_getActiveItem` method.

This function could be made public.

Alternatively, a getter for the active position could be created.

In our application, we extend the carousel by displaying copyright information about the currently displayed image.

**Comment by zoltanszogyenyi** [comment]
Hey @gberaudo,

I have made the `getActiveItem()` method public via https://github.com/themesberg/flowbite/commit/9bc34575202738c7597a2a4036599f5c464e5f92.

Will be released for the `v2.3` version of Flowbite.

Thanks,
Zoltan
