### ISSUE TITLE
Flowbite data-dismiss-target not working with turbo_stream

### ISSUE THREAD

**Issue by miahabdu** [themesberg/flowbite#499]
Running into an issue when using turbo_stream.prepend for flash messages and flowbite toasts. I can dismiss a toast when the page initially loads, but cannot dismiss the toast when a partial is rendered through turbo_stream:

controller.rb

```
format.turbo_stream do
  flash.now[:notice] = "Action taken"
  render turbo_stream: turbo_stream.prepend("flash", partial: "layouts/flash")
  ...
end
```

_flash.html.erb
```
<% flash.each do |flash_type, message| %>
  <div id="toast-success" class="fixed flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 right-5 bottom-5 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Check icon</span>
    </div>
    <div class="ml-3 text-sm font-normal"><%= message %></div>
    <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" data-controller="dismiss" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
<% end %>
```

application.html.rb
```
<%= turbo_frame_tag id="flash" do %>
  <%= render "layouts/flash" %>
<% end %>
```
**Expected behavior**
When a partial is loaded through turbo_stream actions, the Dismiss functionality continues to dismiss the Toast notification

**Comment by zoltanszogyenyi** [comment]
Hey @miahabdu,

Did you include the Turbo specific CDN or JS file as described in our official [Ruby on Rails 7](https://flowbite.com/docs/components/dropdowns/) guide?

There's a special `flowbite.turbo.js` file for this:

```
import "flowbite/dist/flowbite.turbo.js";
```

Or via CDN it would be:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.turbo.min.js"></script>
```

Cheers,
Zoltan

**Comment by miahabdu** [comment]
Hey @zoltanszogyenyi - the `flowbite.turbo.js` is loading: 
<img width="225" alt="Screen Shot 2023-03-21 at 8 21 11 PM" src="https://user-images.githubusercontent.com/2183397/226769781-0bf1527a-6739-4515-925f-69acd268e6f6.png">

**Comment by handzlikt** [comment]
Hi, I follow the official installation guide for Rails with importmaps.
I have `pin "flowbite", to: "https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.turbo.min.js"` in my importmap.rb file
and `import import "flowbite"` in my application.js file. Everything works fine until I want to apply the fix for turbo streams for the comment above. When I add `import { initFlowbite } from "flowbite";` to my Stimulus controller I get an error:
The requested module 'flowbite' does not provide an export named 'initFlowbite'.

Can anybody help me with that?

**Comment by handzlikt** [comment]
@zoltanszogyenyi any update on my previous post? I'd love to use Flowbite but it's a blocker for me at this point.

**Comment by PauloMiranda98** [comment]
After update of flowbite, old soluction (https://github.com/themesberg/flowbite/issues/499#issuecomment-1483139308) does not work.

Now, to resolve your problem you can do:
```js
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  initialize() {
    window.initFlowbite();
  }
}
``` 

```erb
<%= turbo_frame_tag id="flash" do %>
  <div data-controller="controller-name">
    <%= render "layouts/flash" %>
  </div>
<% end %>
```
