### ISSUE TITLE
Carousel to support both landscape and portrait images

### ISSUE THREAD

**Issue by mlevit** [themesberg/flowbite#507]
**Is your feature request related to a problem? Please describe.**
I'd love to see the ability for carousel to support both image orientations within the same carousel.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/a

**Additional context**
N/A

**Comment by zoltanszogyenyi** [comment]
Hey @mlevit,

Don't see why this couldn't be done by adding the apropiate width and height classes via Tailwind CSS.

Cheers,
Zoltan
