### ISSUE TITLE
datepicker-format does not work date-rangepicker

### ISSUE THREAD

**Issue by mai1237** [themesberg/flowbite#520]
datepicker-format does not work date-rangepicker
also in dark mode the backgrouound of the selection table  remains white.

**Comment by HelixEvo** [comment]
I know its late, but I had the same issue.. Somewhere in the docs though it mentions setting it for the first box, it applys to the second. This works if you set global for the datepicker range; if you set it for both, then it seems to cancel each other out.

Hope this helps you..

Ps. Same goes for the other options also like the Today button etc.
