### ISSUE TITLE
Link to CDN JS results in 404 error

### ISSUE THREAD

**Issue by RadekHavelka** [themesberg/flowbite#523]
In the docs, ie here https://flowbite.com/docs/getting-started/introduction/#init-functions

you mention to link via

https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js

but this link throws 404 File not found error ...

**Comment by zoltanszogyenyi** [comment]
Hey @RadekHavelka,

Thanks for reporting - CDNJS takes about 8 hours to pick up new releases.

It should work now.

Cheers,
Zoltan
