### ISSUE TITLE
Getting error when trying to use Modal

### ISSUE THREAD

**Issue by erichi** [themesberg/flowbite#526]
I'm trying to implement modal example from your docs in my Rails 7 + Hotwired Stimulus + Flowbite (turbo) stack. 
Here is my stimulus controller 

```javascript
import { Controller } from "@hotwired/stimulus"
import { Modal } from 'flowbite';

export default class extends Controller {
  connect() {
  }

  showStoryItem(event) {
    const $targetEl = event.target;

    // options with default values
    const options = {
      placement: 'bottom-right',
      backdrop: 'dynamic',
      backdropClasses: 'bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40',
      closable: true,
      onHide: () => {
          console.log('modal is hidden');
      },
      onShow: () => {
          console.log('modal is shown');
      },
      onToggle: () => {
          console.log('modal has been toggled');
      }
    };

    const modal = new Modal($targetEl, options);
    modal.show();
  }
}
```
When I open this page i'm getting error 
`SyntaxError: The requested module 'flowbite' does not provide an export named 'Modal'`

Flowbite js works on dropdowns and etc though

Can you help please?

**Comment by Alxzu** [comment]
@erichi can you share your solution?

**Comment by erichi** [comment]
I've just copied Modal module from the repo to my project and imported from there.

**Comment by hs-dliaska** [comment]
seems a lot of people has this issue https://github.com/themesberg/flowbite/issues/88
