### ISSUE TITLE
solidjs with solid router component, flowbite js function not work when switch route

### ISSUE THREAD

**Issue by neatlife** [themesberg/flowbite#530]
**Describe the bug**
flowbite tooltip component
when use solid router, after switch route, tooltip component not work again

**To Reproduce**
1. direct Go to page with tooltip component, It's working
2. Click a link to another route and switch back
3. tooltip component not work

**Expected behavior**
tooltip component always work

**Comment by KenjiPcx** [comment]
Hi saw that you closed this, did you managed to figure it out? I am facing the same issue here too... I am using the solid start router and what I realize is that whenever I use the router navigation from the A tag, the js from my flowbite components just fail to run

**Comment by neatlife** [comment]
@KenjiPcx This is because flowbite is a traditional js framework, so js only run once when page loaded

**Comment by Blagoj5** [comment]
Nevertheless, it is still possible to fix it with flowbite's init function, `initFlowbite`. Simple: Insert the following into the lazily loaded root component or page, and flowbite will function:

```
  createEffect(() => {
    initFlowbite();
  });
```
