### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by RadekHavelka** [themesberg/flowbite#531]
The main site is not loading

https://flowbite.com/docs/plugins/datepicker/

ERR_NAME_NOT_RESOLVED

**Comment by zoltanszogyenyi** [comment]
Hey @RadekHavelka,

We're looking into the problem - until then feel free to download the repo locally and use it.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Should work now - it was something out of our control. Can you please check again?
