### ISSUE TITLE
modal interaction issue

### ISSUE THREAD

**Issue by asmraihan** [themesberg/flowbite#536]
Modal doesn't open when dynamically created with template literals. 

Normally when in the same html file it works just fine. but when its in separated file for dynmaically created components modal button doesnt appear to be working.

**Comment by zoltanszogyenyi** [comment]
Hello @asmraihan,

We have released Flowbite v2.0 with a new Instances Manager which allows you to get the instance of the components (ie. modals, dropdown) created via data attributes in a global object to then use programmatically.

Please read more about this here:

https://flowbite.com/docs/getting-started/javascript/
https://github.com/themesberg/flowbite/releases/tag/v2.0.0

Cheers,
Zoltan
