### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by athenawisdoms** [themesberg/flowbite#539]
How can I use this with a React Native app? It does not seem to recognize `div` elements, the closest is `View`.

From [step 4 of installing using npm](https://github.com/themesberg/flowbite#install-using-npm), where should the following line be placed at?

```html
<script src="../path/to/flowbite/dist/flowbite.js"></script>
```

Also getting these errors when starting the app if using `import flowbite`:

> Failed to parse declaration "boxShadow: 0 2px 5px 0px rgba(255, 255, 255, 0.08)"

**Comment by MrCIMD** [comment]
Tailwind provides a large set of classes for styling native browser "components" (such as; div, p, img, button, etc).

Flowbite is a library that provides several components already styled (making use of the Tailwind classes) for a more friendly and fast use.

The use of both tools are focused for the web, not for native applications.

React Native is a library for creating user interfaces using the power of React, but it is not styled in the same way and does not use the same tags. React offers several components that will be compiled and transformed into native components for Android and IOS. It is for this reason that we could not use flowbite in React Native.

I recommend you to use Native Base.
 https://nativebase.io/

Sorry for my English, I used translator.

**Comment by zoltanszogyenyi** [comment]
We will create a React Native based Flowbite library in the future.

**Comment by ax-at** [comment]
Any update on this, how soon can we expect a react-native library, even if it's an alpha release, so that we can start contributing back as well as use it.
