### ISSUE TITLE
Replace icon on the Dropdown Component

### ISSUE THREAD

**Issue by subhadeep1010** [themesberg/flowbite#541]
### Discussed in https://github.com/themesberg/flowbite/discussions/213

<div type='discussions-op-text'>

<sup>Originally posted by **nadiemedicejose** July 13, 2022</sup>
Ability to change the arrow icon on Dropdown Components

I would like to replace the icon to make an actions menu with the 3 dots vertical.</div>

**Comment by zoltanszogyenyi** [comment]
Hey @subhadeep1010,

You can change the icon by selecting one of our icons from Flowbite:

https://flowbite.com/icons/

Cheers,
Zoltan
