### ISSUE TITLE
Why is the navbar hamburger menu not working?

### ISSUE THREAD

**Issue by vkamsingh** [themesberg/flowbite#547]
Hello there, Basically, I have an issue with the navbar hamburger menu because, after clicking on it, there is no response. Also, I installed Flowbite for NextJS. So I think I don't need to configure scripts in my codes.

Navbar: https://flowbite.com/docs/components/navbar/#default-navbar

**Comment by damasch** [comment]
I have the same issue.
I think it is a problem with safari.
I've tried this in Safari on iOS and on my MacBook both doesn't work.

**Comment by deleonjulio** [comment]
I have the same issue using Sidebar. 
It works on Firefox (I can open and close) but not on Safari.

**Comment by TheJazzDev** [comment]
Hi @vkamsingh @damasch @deleonjulio

Are you guys still experience this issue?

@vkamsingh Could you elaborate more on the issue you are having with NextJS?

**Comment by jamaalsmith** [comment]
To make the navbar hamburger show the menu options on click, you have to use the CDN:

<script src="https://unpkg.com/flowbite@1.4.4/dist/flowbite.js"></script>

**Comment by nofendian17** [comment]
u can try import the js

`import 'flowbite/dist/flowbite'`

cheers

**Comment by zoltanszogyenyi** [comment]
As @nofendian17 stated, or if you're using React/Next.js please refer to:

https://flowbite-react.com/docs/components/navbar

Cheers,
Zoltan
