### ISSUE TITLE
[Bug report] Tab content disapear when you click the current tab

### ISSUE THREAD

**Issue by Brendon3578** [themesberg/flowbite#55]
Hello everyone,
I found an error on the "**Interactive Tabs**" Component,
As soon as the page launches, if you click on the current tab (the tab that is active), the "tab content" just disappear.
This error happens on the documentation page too:
https://flowbite.com/docs/components/tabs/#interactive-tabs
Go to the interactive tabs section, and click on the **Dashboard** tab

(Sorry if you don't understand something, my english is a little bad)

**Comment by fritzfr** [comment]
+ 1

**Comment by bigzooooz** [comment]
i fixed it by disabling button.active on document ready

in jquery:

```
$(document).ready(function() {
                $('#myTab li button.active').prop("disabled", true);  
});

```
