### ISSUE TITLE
Javascript Integration of Modal - No onHide event triggered

### ISSUE THREAD

**Issue by percybolmer** [themesberg/flowbite#551]
When programmatically trying to control the Modal, using  the provided examples in the [docs](https://flowbite.com/docs/components/modal/)

I can see the `onShow`, `onToggle` events being triggered when Opening the Modal.

However, when clicking the X button to shut down (or the Cancel) button at the bottom no `onHide` event seems to fire. 

This makes the Modal disappear, but the Overlay is left blocking the rest of the application.

**To Reproduce**

1. Open a new Project and install Flowbite. ( I am running Laravel in this case)
2. Add a script that programmatically Opens the modal at the bottom of a template.
```javascript
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {

            let $targetEl = document.getElementById('staticModal')

            const modal = new Modal($targetEl);

            modal.toggle();
        });
    </script>
```
3. Add the StaticModal to be included in the Template.
`@include('static-modal')`

4. Fill the static-modal.blade.php file with the static modal.

```html

<!-- Main modal -->
<div id="staticModal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true"
    class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Edit Question
                </h3>
                <button type="button"
                    class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                    data-modal-hide="staticModal">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
                
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                <button data-modal-hide="staticModal" type="button"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
                <button data-modal-hide="staticModal" type="button"
                    class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Cancel</button>
            </div>
        </div>
    </div>
</div>

```
5. In `app.js` include the Modal
```javascript
import { Modal } from 'flowbite';
```

**Expected behavior**
Expect the Overlay (Shadow of the background application) to disappear when Closing using the Buttons.

I have tried adding a onClick on the Close button to use the `modal.hide()` but still no event is fired.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser [Brave, Firefox, Chrome]

**Additional context**
This bug only appears when I programmatically Click the Button. 

If I use a button such as 

```html
<button data-modal-target="staticModal" data-modal-toggle="staticModal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
    Toggle modal
  </button>
```
Everything works as expected.

Dependencies from my `package.json`
        "@tailwindcss/forms": "^0.5.2",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.14",
        "axios": "^1.1.2",
        "flowbite": "^1.6.5",
        "laravel-vite-plugin": "^0.7.2",
        "postcss": "^8.4.23",
        "tailwindcss": "^3.3.2",
        "vite": "^4.0.0"

**Comment by alexsotir** [comment]
Any update on this?

**Comment by a-cesari** [comment]
I'm having exactly same problem

**Comment by zoltanszogyenyi** [comment]
Hey @percybolmer,

Please try upgrading to Flowbite v2.0 and use the new Instances Manager.

It's a solution that we use to "sync" together the data attributes components with programmatically working with them.

https://flowbite.com/docs/getting-started/javascript/
https://github.com/themesberg/flowbite/releases/tag/v2.0.0

Cheers,
Zoltan

**Comment by percybolmer** [comment]
This is an amazing update!!

Whao! Big thanks and impressive work guys
