### ISSUE TITLE
JS elements not working in Webpack with Tailwind v3

### ISSUE THREAD

**Issue by Dizzzlectic** [themesberg/flowbite#56]
**Describe the bug**
I have a fresh installation of Tailwindcss 3 and latest version of Flowbite installed via NPM and using Webpack 5 as my bundler.
Flowbite styles are working perfectly but all JS powered elements aren't working it seems.

**To Reproduce**
1. Check out https://github.com/Dizzzlectic/flowbite-test
2. Install dependencies (npm install)
3. Run the project (npm run)
4. Try to dismiss any of the alerts

**Expected behavior**
JS elements should be working, but they don't seem to be

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 95.0.2

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hey @Dizzzlectic,

I've cloned the repo and JS actually works. The hidden class is being applied. It seems like you need to include the Flowbite library's JS inside the content key from `tailwind.config.js` so the `hidden` class is registered.

**Comment by Dizzzlectic** [comment]
@zoltanszogyenyi Oh, really? That's brilliant then. Do you have an example for me? I don't think I came across something like that in the documentation. :)

**Comment by zoltanszogyenyi** [comment]
Try something like this:

`content: ['./src/**/*.{js,jsx,ts,tsx,vue,html}', 'node_modules/@themesberg/flowbite/**/*.js'],`

The path may not be correct, but this should solve the issue.

**Comment by zoltanszogyenyi** [comment]
Alternatively, you could also add your own bundled JS via Webpack as it will contain Flowbite's JS automatically.

**Comment by Dizzzlectic** [comment]
@zoltanszogyenyi I didn't think of that, actually. Anyway, that worked like a charm. Thank you so much. Should this maybe be part of the documentation or is this an implied thing? :)

**Comment by zoltanszogyenyi** [comment]
You're very welcome!

Yes, it should. Good thing we have a community pointing the issues out :)

I'll add it soon to the quickstart guide.

**Comment by zoltanszogyenyi** [comment]
@Dizzzlectic 

Instructions have been [added to the docs](https://flowbite.com/docs/getting-started/quickstart/) :)
