### ISSUE TITLE
Background opacity classes not compatible with Tailwind 3+

### ISSUE THREAD

**Issue by jordigagomerino** [themesberg/flowbite#565]
**Describe the bug**
Some [components](https://github.com/search?q=repo%3Athemesberg%2Fflowbite%20bg-opacity&type=code) use Tailwind 2 opacity classes that are not compatible with TW3 making some components to not work correctly. In my case de drawer component is completly opaque. Now i'm overriding the classes but it would be great to have tw3 compatibility.
I opened a [PR](https://github.com/themesberg/flowbite-svelte/pull/720) on the flwobite-svelte git.
**To Reproduce**
https://github.com/search?q=repo%3Athemesberg%2Fflowbite%20bg-opacity&type=code

**Expected behavior**
Should use tw3 ways to use opacity (bg-color-shade/opacity)

**Comment by TVBZ** [comment]
Any updates on this? I'm new to flowbite, using it in Laravel project,.. but this is just a no-go.

**Comment by tiamiyuwaliu** [comment]
Hi @TVBZ 
The issue with the `modal-backdrop` not working is related to the use of precompiled Tailwind CSS. In my experience, only classes explicitly used in your view files are compiled. The `bg-opacity-50` class is dynamically added by JavaScript, which the compiler does not detect.

**Comment by dan-pascu** [comment]
Hi,

I had the same issue as @TVBZ and I used the fixed from @tiamiyuwaliu and it worked.

Thanks

**Comment by zoltanszogyenyi** [comment]
Hey @jordigagomerino @TVBZ @tiamiyuwaliu @dan-pascu,

Fixed this in the `v2.1.0` release: https://github.com/themesberg/flowbite/releases/tag/v2.1.0

Cheers,
Zoltan
