### ISSUE TITLE
Dismiss import does not work in Vue 3 + Vite app

### ISSUE THREAD

**Issue by jlariza** [themesberg/flowbite#568]
**Describe the bug**
When adding `import { Dismiss } from 'flowbite';` to `<script setup>` script, console returns the following error
```
caught SyntaxError: The requested module '/node_modules/.vite/deps/flowbite.js?v=a9f96e8c' does not provide an export named 'default'
```

**To Reproduce**
1. Create a Vue 3 + Vite app
2. Install and configure flowbite according to the setup instructions
3. Try adding `import { Dismiss } from 'flowbite';` in `App.vue` script setup

**Expected behavior**
It should import the `Dismiss` class according to https://flowbite.com/docs/components/alerts/#example

**Comment by zoltanszogyenyi** [comment]
Hey @jlariza,

Is this still an issue? Dismiss works with our new Vue guide and and Vue starter repo:

- https://flowbite.com/docs/getting-started/vue/
- https://github.com/themesberg/tailwind-vue-starter

Cheers,
Zoltan
