### ISSUE TITLE
How to implement dynamic striped table rows?

### ISSUE THREAD

**Issue by stsrki** [themesberg/flowbite#569]
I'm trying to adjust dark colors on a table row based on `odd:` and `even:` selectors. For the light theme, it works. But for the dark theme, nothing gets applied:

I have tried an example

```
odd:bg-white even:bg-gray-50 border-b odd:dark:bg-gray-800 even:dark:bg-gray-700 dark:border-gray-600
```
found from #54

Maybe I'm missing a config setting somewhere?

**Comment by zoltanszogyenyi** [comment]
Hey @stsrki,

Did you try to use `dark:even:bg-gray-700` instead of `even:dark:bg-gray-700`?

I think you need to add the `dark` variant before `even` and `odd`.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @stsrki,

Are you using Tailwind CSS v3.0? 

I've refactored the tables and here's the list of classes that work for me:

```
odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700
```

Cheers,
Zoltan

**Comment by stsrki** [comment]
I don't think that it works. I have even tried it on Flowbite docs; see the screenshot

![image](https://github.com/themesberg/flowbite/assets/900302/2d954fe6-36e4-459b-a873-6cbec1cbda37)

**Comment by zoltanszogyenyi** [comment]
Here's a Tailwind Play example:

https://play.tailwindcss.com/KZg5W8B3xm
