### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by carlocorradini** [themesberg/flowbite#571]
**Is your feature request related to a problem? Please describe.**
Vertically aligned tabs.

Similar to https://tailwind-elements.com/docs/standard/navigation/tabs/#vertical

![IMG_20230605_140008.jpg](https://github.com/themesberg/flowbite/assets/21266147/c8bbc082-607e-4be4-a2cf-e34e66746de4)

**Comment by zoltanszogyenyi** [comment]
Hey @carlocorradini,

We have added a vertical tabs example: https://flowbite.com/docs/components/tabs/#vertical-tabs

Cheers,
Zoltan
