### ISSUE TITLE
Failed to load source map for `/node_modules/.pnpm/flowbite@1.6.6/node_modules/flowbite/dist/datepicker.min.js`

### ISSUE THREAD

**Issue by KnifeFed** [themesberg/flowbite#580]
**Describe the bug**
When starting the Nuxt 3.5.3 dev server, I get the following warnings:

```
WARN  Failed to load source map for /node_modules/.pnpm/flowbite@1.6.6/node_modules/flowbite/dist/datepicker.min.js.

WARN  Failed to load source map for /node_modules/.pnpm/flowbite@1.6.6/node_modules/flowbite/dist/datepicker.turbo.min.js.
```

**Desktop (please complete the following information):**
 - OS: macOS 13.4

**Additional context**

I have the following in my `tailwind.config.ts`:

```js
export default {
  content: ['./node_modules/flowbite/**/*.{js,ts}'],
  plugins: [
    require('flowbite/plugin'),
  ],
  …
}
```

I haven't used the date picker so I'm not sure if it should actually load the source maps at all, and for the minified version at that. Everything else is working fine though so this is just a minor issue I thought I'd let you know about.

**Comment by RodrigoProjects** [comment]
Same here!

**Comment by RodrigoProjects** [comment]
My datepicker does not work tho... What did you do to make it work?

**Comment by KnifeFed** [comment]
@RodrigoProjects I don't use the date picker so I don't know if it works, but if it doesn't work for you I assume it wouldn't work for me either and that this issue is more than just a nagging message then.

**Comment by nadamai** [comment]
The same problem without datepicker.

**Comment by RodrigoProjects** [comment]
I had to install the datepicker to use it in my nuxt 3 project. Its's supposed to already be installed with my nuxt 3 flowbite start guide correct?

**Comment by zxdream64230** [comment]
Hello everyone, same problem here.
Did someone find a solution?

**Comment by byoungd** [comment]
The same problem at nuxt3.7.3.
No one cares about this problem?

**Comment by NativeAppDeveloper** [comment]
Hello everyone, same problem here.
Did someone find a solution?

**Comment by zoltanszogyenyi** [comment]
Hello everyone,

Since `v2.4.1` the datepicker is a core component of Flowbite so you no longer need to install it separately.

Please check the new guide here:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour

Cheers,
Zoltan
