### ISSUE TITLE
Website out of date

### ISSUE THREAD

**Issue by danielniccoli** [themesberg/flowbite#592]
https://flowbite.com/docs/components/sidebar/ is out of date and wildly inconsistent. For example, most nav items on this page are missing the `group` class in the `a` elements.

The following code block is taken directly from https://flowbite.com/docs/components/sidebar/#default-sidebar:

```html
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
               <svg aria-hidden="true" class="w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
               <span class="ml-3">Dashboard</span>
            </a>
         </li>
```

In github, the code is corrected and contains the `group` class:  
https://github.com/themesberg/flowbite/blob/2f941a72dc3cbe9d1cfbd4f4a5525693817e5959/content/components/sidebar.md?plain=1#L32C68-L32C68

**Comment by zoltanszogyenyi** [comment]
Hey @danielniccoli,

We have updated Flowbite to `v1.7.0` and some of these inconsistencies should be fixed by adding the `group` class.

Cheers,
Zoltan

**Comment by danielniccoli** [comment]
- The Off-canvas sidebar is still bugged. Some nav items highlight on hover, others don't. They also use old icons.
 - Some svg classes use `flex-shrink-0`, others don't
   ![image](https://github.com/themesberg/flowbite/assets/2971735/27c1faf1-65e9-48b3-913e-201fc88e31d1)
 - Sometimes transitions are used on a elements, and sometimes not
   ![image](https://github.com/themesberg/flowbite/assets/2971735/0bb05341-ad93-41f4-bd24-b7b3902c9eca)

And when you go over to the UI layouts (https://flowbite.com/blocks/application/sidenav/ or https://flowbite.com/blocks/application/shells/) it gets even worse. Every UI layout and every variation of it has minor deviations in the smallest components, such as nav items. Up to the point where in the same variation, one nav item is different than the other, even though they are visually almost identical.

**Comment by zoltanszogyenyi** [comment]
Hey @danielniccoli,

Thanks for the feedback - the off-canvas sidebar went out of my radar. After over 70 commits over 5 days it happens I guess.

I'll go over the transitions and flex shrink 0 classes just in case. Regarding the one for blocks - we are quite close to doing a full revamp which will include updating the spacing, font smoothing, reported bugs over time and also integrate the new icons.

The Flowbite Library is open-source and quite a lot of the blocks that we offer too - so we need the community input, feedback, and sometimes even contributions to keep it alive.

Thank you,
Zoltan

**Comment by zoltanszogyenyi** [comment]
I've updated the off-canvas example with the new icons - all examples should have transition and flex-shrink-0 now.

For the "blocks" examples it's going to take about two weeks since there are over 330 of them at this point.
