### ISSUE TITLE
reinit Datepicker

### ISSUE THREAD

**Issue by Eduardo-XavierPaula** [themesberg/flowbite#594]
I have an issue, but I'm not certain if it is a bug or a feature.

I'm trying to use a datepicker input inside a table, and I need to add more rows to the table through a button. However, since this new row doesn't exist in the DOM yet, because it's being created with a template, and the script from Flowbite has already run, the component of Datepicker isn't generated in the new field.

So, I tried to use initFlowbite(); to reload the Datepicker component without success.

I was wondering if there is any other way to do that or if there is something like an initModal() or initDropdown() function that I can use.

I'm not using any framework, just pure html and js combined with Flowbite(1.7.0).

To reproduce the behavior:
1. Add a datepicker field after the js from Flowbite had already run.
2. There is no way to generate the component for the calendar.

1-Before the fields were created 
![image](https://github.com/themesberg/flowbite/assets/49372451/a8a18eec-bbed-4da9-b5c3-ce973e91bede)
2-After the fields were created
![image](https://github.com/themesberg/flowbite/assets/49372451/47b6d1ec-0cc5-4cd8-ab0a-ad6890fedcb4)
3-Calendar wasn't generated 
![image](https://github.com/themesberg/flowbite/assets/49372451/2e531338-ff56-4921-a111-40b7d25b7bb1)

 - Browser [e.g. chrome, edge]

**Comment by zoltanszogyenyi** [comment]
Hey @Eduardo-XavierPaula,

We released `v2.4.1` and made the datepicker a core component of the Flowbite JS.

You can now re-init it just like any other component, please read more here:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour
https://flowbite.com/docs/getting-started/javascript/#instance-manager

Cheers,
Zoltan
