### ISSUE TITLE
Today button not working in date picker

### ISSUE THREAD

**Issue by ArtemRubets** [themesberg/flowbite#595]
In the Action Buttons section, the Today button does not work. Not in this example not in the project - https://flowbite.com/docs/plugins/datepicker/#action-buttons

**Comment by Ryczko** [comment]
By default, clicking the `Today` button takes you to the current date only. I also needed the ability to select today's date, so I added this ability in this MR by adding the `datepicker-today-select` attribute: https://github.com/themesberg/flowbite/pull/608

**Comment by zoltanszogyenyi** [comment]
This PR has been merged and will work with `v2.3`: https://github.com/themesberg/flowbite/pull/608
