### ISSUE TITLE
wrong toast position

### ISSUE THREAD

**Issue by CFarhad** [themesberg/flowbite#62]
Hello.
i find a bug in [Toast position](https://flowbite.com/docs/components/toast/#position)
it not show true in demo . 
![image](https://user-images.githubusercontent.com/44419462/149664539-f7645d07-30eb-46d9-81d0-9bc412fc4c8b.png)

**Comment by zoltanszogyenyi** [comment]
Hey @CFarhad,

It looks like it's a caching problem. Try to clear it using ctrl (cmd) + shift + r.

**Comment by CFarhad** [comment]
thank you its working . 
but if everyone has this problem you can not say to him clear your cache !
i think you need removing caching from js & css files

**Comment by zoltanszogyenyi** [comment]
@CFarhad you're right, fixed it with query strings since we still want to cache the JS and CSS files for increased performance

https://github.com/themesberg/flowbite/commit/e55cc1429f249636ea7d183f643c7beda3f01737
