### ISSUE TITLE
Tailwind UI not working with flowbite CDN

### ISSUE THREAD

**Issue by Sammeeey** [themesberg/flowbite#622]
**Describe the bug**
The [feature section `With product screenshot`](https://tailwindui.com/components/marketing/sections/feature-sections) from Tailwind UI doesn't anymore as soon as I include the flowbite using the [CDN option](https://flowbite.com/docs/getting-started/quickstart/#include-via-cdn) using vanilla HTML/CSS/JS.

**To Reproduce**
1. [setup tailwind UI](https://tailwindcss.com/docs/installation)
2. [include flowbite via CDN](https://flowbite.com/docs/getting-started/quickstart/#include-via-cdn)
3. create HTML file with [feature section `With product screenshot`](https://tailwindui.com/components/marketing/sections/feature-sections)
```
<head>
  <link href="/dist/output.css" rel="stylesheet">
  <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
  <script src="index.js" defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js" defer></script>
</head>
<body>
<!-- feature section code here -->
</body>
```

**Expected behavior**
Tailwind UI feature section shouldn't change.

**Screenshots**
This is how the section looks on desktop for me after adding flowbite via CDN:
![grafik](https://github.com/themesberg/flowbite/assets/49591562/fa75d246-c620-4cf2-a6b7-495aed8dd067)

**Desktop (please complete the following information):**
 - OS: Windows 10 (locally)
 - Browser chrome 
 - Version 115.0.5790.99 (64-Bit)

**Comment by zoltanszogyenyi** [comment]
Hey @Sammeeey,

Remove this:

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
```

And preferably you should set up Flowbite via NPM and install the plugin in `tailwind.config.js`:

https://flowbite.com/docs/getting-started/quickstart/

Then it should work seamlessly!

Cheers,
Zoltan

**Comment by Sammeeey** [comment]
Simply removing the line as you said, worked.
But why is it then described to include this line in https://flowbite.com/docs/getting-started/quickstart/#include-via-cdn ?
