### ISSUE TITLE
When I add `require('flowbite/plugin')` for `tailwind.config.js`, I got these errors: The safelist pattern `/^apexcharts-.*$/` doesn't match any Tailwind CSS classes.

### ISSUE THREAD

**Issue by PublicWorld** [themesberg/flowbite#628]
```shell
warn - The safelist pattern `/^apexcharts-.*$/` doesn't match any Tailwind CSS classes.
warn - Fix this pattern or remove it from your `safelist` configuration.
warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
```

![image](https://github.com/themesberg/flowbite/assets/12987627/fca20723-9e55-4e83-91db-e87af0cbec6d)

and this is dependencies of package.json:
![image](https://github.com/themesberg/flowbite/assets/12987627/443015f5-2789-4d47-8cb9-20c54832cf17)

**Comment by andreigherghe** [comment]
Just ran `npm update` and started having this issue as well.

**Comment by zoltanszogyenyi** [comment]
Hey peeps,

Does this break the project or is it just a warning? I'll take a look at it tomorrow.

Thanks!

**Comment by andreigherghe** [comment]
It doesn't break the project, it's just a warning. Thank you!

**Comment by zoltanszogyenyi** [comment]
Got me a bit worried :)

Should be an easy conditional fix, it's part of our new charts update and adding the regex safelist is an easy way to apply the classes automatically for the charts.

Will patch it in v1.8.1.

Ignore the warning until then, it shouldn't affect anything in terms of performance afaik.

**Comment by zoltanszogyenyi** [comment]
Peeps, please update to `v1.8.1` and check if it still shows the warning:

https://github.com/themesberg/flowbite/releases/tag/v1.8.1

Thanks!

**Comment by andreigherghe** [comment]
@zoltanszogyenyi Thank you so much! The warning is no longer present. 😃

**Comment by zoltanszogyenyi** [comment]
Awesome, thank you all!
