### ISSUE TITLE
import cdn not working 

### ISSUE THREAD

**Issue by lindareddigital** [themesberg/flowbite#629]
i use this drawer component 

https://flowbite.com/docs/components/drawer/

it can use before but now fail

anyone can help me?

now version fail 

https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js

**Comment by zoltanszogyenyi** [comment]
Hey,

It takes a few hours for the CDN to update -- does jt work now?

Cheers,
Zoltan

**Comment by lindareddigital** [comment]
Now import CDN need to import next Script like below   


```

import Script from 'next/script';



 <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js" />
```


Not working

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
```

**Comment by zoltanszogyenyi** [comment]
I think this might be something that is more of a Next.js issue than the CDN link from Flowbite.
