### ISSUE TITLE
Accordion with LiveWire not working

### ISSUE THREAD

**Issue by yassinetrbls** [themesberg/flowbite#631]
Hello,

When loading accordion (or Nested Accordion) with livewire (lazy loading), open/close not working. Even when using wire:ignore.self in LiveWire 3.

I tested with LiveWire 2 (https://laravel-livewire.com/docs/2.x/defer-loading)
And Also with LiveWire 3 (https://livewire.laravel.com/docs/lazy)

https://flowbite.com/docs/components/accordion/

**Comment by wagnerbugs** [comment]
Hello. Please check if it is configured correctly. 

https://livewire.laravel.com/docs/navigate#dont-rely-on-domcontentloaded

In projects with Livewire, I resolved all these details with the doc above.

**Comment by wagnerbugs** [comment]
Hello. Please check if it is configured correctly. 

https://livewire.laravel.com/docs/navigate#dont-rely-on-domcontentloaded

In projects with Livewire, I resolved all these details with the doc above.

**Comment by zoltanszogyenyi** [comment]
Answer by @wagnerbugs is correct. Use the `initFlowbite()` function when the DOM content has loaded.

**Comment by Uhasith** [comment]
I'm facing flowbite JS issues inside my Livewire Components. Such as Accordion , Tooltips Kind Of JS  things not working at All. I'm New to Flowbite what can be the issue? @wagnerbugs  @zoltanszogyenyi @yassinetrbls
