### ISSUE TITLE
Update Search Input docs 

### ISSUE THREAD

**Issue by AdityaGupta20871** [themesberg/flowbite#640]
**Describe the bug**
Missing closing tag for input components in Tailwind CSS Search Input docs

**Screenshots**
![Screenshot (50)](https://github.com/themesberg/flowbite/assets/103377205/74074c17-8707-4132-9001-e426c6e39601)

I have resolved this issue and opened a pull request for it . Hope it helps !

**Comment by AdityaGupta20871** [comment]
I think this would be a feature request rather than bug as I didn't pay attention to html written in documentation ! As I was working with react vite still it would be beneficial for react developers if this feature is implemented !

**Comment by zoltanszogyenyi** [comment]
Hey @AdityaGupta20871,

All input fields now have a closing tag. Will be released soon for `v2.3`.

Thanks,
Zoltan
