### ISSUE TITLE
Issue with interactive elements on Nuxt.js

### ISSUE THREAD

**Issue by chizytony** [themesberg/flowbite#65]
All interactive elements like Tab, Dropdown and modal seems to stop working when you leave current page and back back to the page on Nuxt.js

**Comment by shinokada** [comment]
Same in SvelteKit.

https://github.com/themesberg/flowbite/issues/67

**Comment by aacassandra** [comment]
when use import method
i getting some error like this
```
Cannot find module '@themesberg/tailwind-datepicker/DatePicker'
Cannot find module '@themesberg/tailwind-datepicker/DateRangePicker'
```

im using nuxt

**Comment by zoltanszogyenyi** [comment]
Hey @chizytony @aacassandra,

Please check out the [Flowbite Vue component library](https://github.com/themesberg/flowbite-vue) for Vue or Nuxt projects.
