### ISSUE TITLE
Cannot closed programatically opened modals by clicking on 'x'

### ISSUE THREAD

**Issue by pavitrakumar78** [themesberg/flowbite#652]
Clicking on the close button of models opened via JS initialization does not work. 

**To Reproduce**
Initialize a modal via JS
https://flowbite.com/docs/components/modal/#example

Open the model and to close it by clicking on the 'x' button at the top right corner. 

**Expected behavior**
modal should close

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 116.0.5845.140

**Comment by azeiteiro** [comment]
Same issue here. 

The close button only works when the modal is initialized via data HTML attributes, otherwise, if the exact modal is initialized via javascript (new Modal()) the close buttons do not fire any action.

**Comment by zoltanszogyenyi** [comment]
Hey @pavitrakumar78 @azeiteiro,

With the new Instance Manager from Flowbite v2.0 you can now access the modal instance even if it's created via data attributes.

Please check out the following resources:

https://flowbite.com/docs/getting-started/javascript/
https://github.com/themesberg/flowbite/issues

Cheers,
Zoltan
