### ISSUE TITLE
Interactive Tabs Disappear content

### ISSUE THREAD

**Issue by Arci224** [themesberg/flowbite#66]
**Describe the bug**

**To Reproduce**
1. Go to ['Interactive tabs'](https://flowbite.com/docs/components/tabs/)
2. Click on Default active tab two times
3. Tab content will disappear and you have to click another and back.

**Expected behavior**
Content still will be shown

**Screenshots**
X

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 97.0.4692.71

**Comment by Arci224** [comment]
I see another same report as my: #55

**Comment by zoltanszogyenyi** [comment]
Thanks @Arci224 for the report.

Will patch this soon.
