### ISSUE TITLE
Javascript related functionalities not working in Blazor

### ISSUE THREAD

**Issue by dechaunb** [themesberg/flowbite#660]
For the past 5 days, I've been trying to set up a project with Blazor + Tailwind + Flowbite. I found a lot of repo's like the flowbite blazor starter from themesberg and honestly, kudo's, but my dropdown hovers, popovers and tooltips and some other javascript related functionalities are not working or showing. Anybody know what might cause this? (I cloned this repo to get it started and followed everything in the README.md)

![image](https://github.com/themesberg/tailwind-blazor-starter/assets/64783977/080714ba-728d-422c-87e7-f31607064aac)
![image](https://github.com/themesberg/tailwind-blazor-starter/assets/64783977/7512a50d-b3d7-43b8-b432-85df2226008e)

**Comment by HillCat** [comment]
How to solve this issue?
