### ISSUE TITLE
how to disable dark mode

### ISSUE THREAD

**Issue by vinayiaastha** [themesberg/flowbite#661]
**Describe the bug**
How to disable dark mode in flowbite in nextJS without removing dark mode css

![image](https://github.com/themesberg/flowbite/assets/141990817/5bf5d38b-ec9e-4698-9fe2-902004a0f853)

Description: Right now I have not added dark or light mode functionality to the project but since there is a default dark mode css, I auto-applied the dark theme from the dark mode of the system.  How to stop it so that only light mode is shown to the user?

**Comment by canaleal** [comment]
Hello @vinayiaastha , could you upload an image of the tailwind.config.js file? 

By default, dark mode is set to media (Computer preferences), and you'll need to set it to false inside the tailwind.config.js as shown [here](https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration) to only show light mode.

**Comment by zoltanszogyenyi** [comment]
Hey @vinayiaastha @canaleal,

That's right, that is the best way to disable dark mode for Flowbite and Tailwind CSS.

We may add a feature to the docs to remove the dark mode variants if needed, but that's for another issue.

Cheers,
Zoltan

**Comment by mrckzgl** [comment]
We do have the same problem. The anchor `#remove-dark-mode-configuration` in the link you provided: https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration does not exist anymore, so there is no section which explains how to disable dark mode. Also if I add:
```
export default {
  darkMode: false, // Disable dark mode
  ...
```
to the tailwind.config.js I get the following warning:
```
warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
warn - Change `darkMode` to `media` or remove it entirely.
warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
```
which, again has a link to the non existing section / anchor in the upgrade-guide. Also the warning tells me that essentially it is not possible to disable dark mode as false is now the same as media and even with darkMode: false the components change to dark mode if I set firefox to use dark mode.
So it remains, how to disable dark mode?
