### ISSUE TITLE
Customizing active tab with aria-selected:{class} is not working properly

### ISSUE THREAD

**Issue by yurivis** [themesberg/flowbite#670]
**Describe the bug**

In the Components documentation, Tabs section [Customize active tab subsection](https://flowbite.com/docs/components/tabs/#customize-active-tab) you describe how to apply styling to an active button with `aria-selected:{class}`. There is no explanation on how exactly it is applied nor what is the expected behavior. Is the `class` added to the button's classlist? Should the class be already declared in my CSS on compilation? I've tried different combinations of `aria-selected:{class}` including `aria-selected:{text-primary-200}`, `aria-selected:text-primary-200`, `aria-selected:{class}="text-primary-200"`, but there is no reason trying, since I don't know what to expect.

**Comment by GeorgeKryptonian** [comment]
@yurivis Have you solved your problem? I have the same question.

**Comment by yurivis** [comment]
@GeorgeKryptonian Unfortunately, no. In my case I have rewritten the default color to suit my theme and went on from there. Not sure if this was fixed.

**Comment by zoltanszogyenyi** [comment]
Hey everyone! The next release for `v2.3` will include two new data attributes that will allow you to update the active and inactive classes using Tailwind CSS classes:

<img width="873" alt="Screenshot 2024-02-07 at 12 52 11" src="https://github.com/themesberg/flowbite/assets/8052108/0b1c899d-ec85-4af2-840e-9ced2c103899">

Cheers,
Zoltan
