### ISSUE TITLE
change sides default drawer

### ISSUE THREAD

**Issue by developertrinidad08** [themesberg/flowbite#671]
I am using the default drawer for my application but by default it comes out from the left and hides on the left... how can I make it do the opposite? that is, it comes out from the right and hides to the right

I achieved something similar with this div but the animation works in reverse

```
<!-- drawer component -->
	<div id="drawer-update-product-default"
		class="fixed top-0 left-full  z-40 w-full h-screen max-w-xs p-4
	        overflow-y-auto transition-transform -translate-x-full bg-white "
	        tabindex="-1"
	        aria-hidden="true"
	        aria-labelledby="drawer-label" 
	        >
```

The example I am using is the first of those that are predefined in the following link: 
 
 https://flowbite.com/blocks/application/crud-update-drawers/

**Comment by zoltanszogyenyi** [comment]
Hello @developertrinidad08,

Did you try the position examples?

https://flowbite.com/docs/components/drawer/#placement

Cheers,
Zoltan
