### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'position')

### ISSUE THREAD

**Issue by quizafebrick** [themesberg/flowbite#673]
**Describe the bug**
Could not load content for http://[::1]:5173/node_modules/flowbite/src/components/carousel/index.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

last sunday it is working, then suddenly happen like this 
![image](https://github.com/themesberg/flowbite/assets/102888867/029f9b1f-1f53-4e30-9dd7-dc454a5fc11b)

I'm having an foreach statement and it is working on the first carousel right now but the third one is not and last sunday it is all working, i don't know what happened. This is Laravel 10

here's the source code 
![code1](https://github.com/themesberg/flowbite/assets/102888867/6c07ea13-7a27-4e12-b314-d0ebc6d5a5d6)
![code2](https://github.com/themesberg/flowbite/assets/102888867/7577fde9-828f-4413-82cb-c8eb9c9a3743)

**Comment by zoltanszogyenyi** [comment]
Hey @quizafebrick,

Please make sure that all of the required elements are available on the page.

Looks like some items may have not rendered hence why the issue persisted.

Cheers,
Zoltan
