### ISSUE TITLE
Flowbite docs don't have correct theme toggle behavior

### ISSUE THREAD

**Issue by ArunBohra12** [themesberg/flowbite#676]
**Describe the bug**

**To Reproduce**
1. Go to [flowbite docs](https://flowbite.com/docs/getting-started/introduction/)
2. Open same page on another tab (it can be any page on flowbite docs)
3. Toggle the theme on the first page
4. Go to the second page and toggle the theme there
5. On the second page the icon to toggle the theme changes but the theme remains the same

**Expected behavior**
The theme should be changed with the icon

**Screenshots**
![image 1](https://github.com/themesberg/flowbite/assets/94133102/e719c76f-f79b-459c-85e4-5a26b10c8982)
![image 2](https://github.com/themesberg/flowbite/assets/94133102/48dc1874-be1e-4a0f-b77e-c61bad8a580e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 117.0.5938.132

**Additional context**
I encountered this issue when I had multiple tabs opened with light theme and I wanted to go to dark theme.

**Comment by ArunBohra12** [comment]
If this is something that's considered valid and is decided to work upon, I'd like to contribute.

**Comment by zoltanszogyenyi** [comment]
Hey @ArunBohra12,

Thanks for writing and providing feedback.

I've just checked this out and the theming behaviour seems to be okay.

The icon changes as I refresh the page and navigate the website.

Here's a video on my end:

https://github.com/themesberg/flowbite/assets/8052108/8d57a58f-aec6-4ea5-8c1e-3a120f039ef6

Cheers,
Zoltan

**Comment by ArunBohra12** [comment]
Hmm.. if I'm not wrong, you're always in the same tab. If that's the case, you might want to check it by opening a new tab, changing the theme there, coming back to the first tab, and trying to change the theme on this first tab. I'll leave a video of my own.

https://github.com/themesberg/flowbite/assets/94133102/e7d99cb5-cbe4-4e55-9329-3a17e4eeb7fc

If the behavior is okay, then it's all good.
