### ISSUE TITLE
Getting error on Nextjs TypeError: document.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by dan-valang** [themesberg/flowbite#681]
**Describe the bug**
Getting an error in nextjs when importing components

Server Error
TypeError: document.getElementsByTagName is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file: <PROJECT>/node_modules/react-indiana-drag-scroll/dist/index.js (21:928)

**To Reproduce**
1. import {Button, Label, Modal, Radio, TextInput} from 'flowbite-react'
2. When building will give that error, my guess is that is trying to build that as SSR

**Expected behavior**
Component can be rendered server side without dynamic imports on nextjs

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu
 - Browser Chrome
 - "flowbite": "^1.8.1",
	"flowbite-react": "0.5.0"

Using page router

**Comment by RajKunx2** [comment]
can you please share this chart component used in next js, it would be extremely helpful
