### ISSUE TITLE
Asp.Net Blazor support

### ISSUE THREAD

**Issue by tdashworth** [themesberg/flowbite#69]
**Is your feature request related to a problem? Please describe.**
As a .NET developer, I would love to use this library in my Blazor project 

**Describe the solution you'd like**
A Nuget package, similar to NPM for React and Vue.

**Comment by zoltanszogyenyi** [comment]
Hey @tdashworth,

I am not that familiar with .NET, however, it would be awesome if you could create a PR to help us get started.

You can tune in with the [community on Discord](https://discord.gg/4eeurUVvTy),

My username is zoltanszogyenyi.

.NET support would be awesome!

**Comment by tdashworth** [comment]
Hey @florian03-1 

I haven't started yet but was planning to soon. Support would be amazing. 

If you are eager to start, don't wait for me but keep me posted 😀

**Comment by florian03-1** [comment]
@tdashworth When do you plan to start?
I will wait for you...

**Comment by tdashworth** [comment]
@florian03-1 I hope to have time next, even if it's just a skeleton project.

**Comment by tdashworth** [comment]
@florian03-1 I have created a basic project (copying the structure from the `flowbite-svelte` project): https://github.com/tdashworth/flowbite-blazor

It only has a library project currently but we should add a test project (using `bunit`?) and a sample project. There is lots to get working on and I'll add you as a contributor so you don't need to fork. 😄

**Comment by florian03-1** [comment]
@tdashworth Great!

I'm on vaccation at the moment, but when I am back, i will take a look.

Should we create a subchannel on the Flowbite discord server, that we can discuss the project?

**Comment by zoltanszogyenyi** [comment]
Hey @florian03-1, @tdashworth,

I created a subchannel on the Discord server :)

**Comment by MiroslavMikus** [comment]
Hey, amazing library :heart_eyes:
Is there any new info about the support for Blazor? Is there anything I could do?

**Comment by florian03-1** [comment]
Hey,

i was very busy last time, but I will start soon with the implementation. Your help would be amazing.
Do you want to join the discord server and talk with us about the project?

**Comment by tdashworth** [comment]
Hey @MiroslavMikus, thanks for your interest. I did make a start but didn't get too far with other priorities... 

I'm still very interested, selfishly for a personal project or two, so I'll keep you posted with progress. I would recommend joining discord to hear the latest 😀

**Comment by zoltanszogyenyi** [comment]
Hey peeps 👋

I created a more formal issue here: https://github.com/themesberg/flowbite/issues/395

I'll close this one so we can discuss there if anyone is interested to help us with the guide.
