### ISSUE TITLE
Dropdown not working with Laravel Livewire 3 wire:navigate

### ISSUE THREAD

**Issue by nasirkhan** [themesberg/flowbite#691]
**Describe the bug** 
I am using Flowbite in a number of Laravel projects. In a recent project, I started to use `Livewire 3` and its [wire:navigate](https://livewire.laravel.com/docs/wire-navigate).

The dropdown menu works only after a full page refresh but not for the `wire:navigate`. I would like to mention that the menu area remains the same for regular `blade` pages and `livewire full-page components`. 

**To Reproduce**
1. Create Livewire 3 full page component https://livewire.laravel.com/docs/components#full-page-components. Implement `wire:navigate` for pages. 
2. Create a dropdown menu. 
3. Change the page using menu, 
4. now click on the dropdown menu item again and see if the dropdown items appears or not

**Expected behavior**
The drop-down menu should appear each time I click the related parent menu item.

**Comment by reasecret** [comment]
I'm facing same issue right now and looks like I found solution:
https://www.youtube.com/watch?v=gkDq2E6g0F0

Just add this to app.js file:
```
document.addEventListener('livewire:navigated', () => { 
    initFlowbite();
})
```

**Comment by nasirkhan** [comment]
@reasecret thanks. This solves the issue.
