### ISSUE TITLE
closeAlert function for alert

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#70]
## Is your feature request related to a problem? Please describe.

I am using Flowbite with Svelte. When I click a link in an alert take me to another page. When I click the browser button to go back to a page, the close button on the alert doesn't work. I need to refresh the page to close it.

## Describe the solution you'd like

The modal has the `toggleModal` function to toggle. If the alert has `closeAlert` function, the button can run the event handler to fire the `closeAlert`.

**Comment by zoltanszogyenyi** [comment]
This has been fixed for v1.4.0 by using the `onHide` callback function on the `Dismiss` object.

**Comment by gfernandez-me** [comment]
![image](https://user-images.githubusercontent.com/5313969/158860572-c330a6fc-8888-4bd4-a802-bf5935a3d08d.png)

related to toggleModal, do you guys know a way to hide this warning?
