### ISSUE TITLE
DatePicker in Angular not working

### ISSUE THREAD

**Issue by torresmald** [themesberg/flowbite#701]
Using Angular 16 with lazy load the datepicker doesnt show the dates.

1. Installed Tailwind with Angular--> working fine.
2. Used datepicker in the app component--> working fine.
3. Tried to use the datepicker in any other module using lazy load--> not working

Tried to apply the @Flowbit decorator but not working too. 

When you use the loadChildren in the app-routing.module the datepicker is not working in their own module

**Comment by GitHubish** [comment]
same problem - i think there's something wrong with the initialization. it would be cool to have some help and an example.

**Comment by issamjebrane** [comment]
same goes for me

**Comment by zoltanszogyenyi** [comment]
This PR will make it work: https://github.com/themesberg/flowbite/tree/datepicker-instance

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

Good news! The datepicker now works with Angular too, please install `v2.4.1`:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour
https://github.com/themesberg/tailwind-angular-starter

This repo also has the datepicker configured.

Cheers,
Zoltan
