### ISSUE TITLE
How should I enable interactive UI components in Flowbit? import { Tabs } from 'flowbite'; How should it be added?

### ISSUE THREAD

**Issue by BahramElf** [themesberg/flowbite#705]
At https://flowbite.com/docs/components/tabs/#example there are three sections about JavaScript code. Where should we add JavaScript codes?
I added these codes in a file called admin.js to my project. But the line:

import { Tabs } from 'flowbite';

It encounters an error (Uncaught SyntaxError: Cannot use import statement outside a module).

I think I'm adding the js codes to the project in the wrong way or something else because it's not working for me.
just create admin.js file, Copy the javascript codes related to the tabs from the site in the same order as they are on the page related to the tabs (https://flowbite.com/docs/components/tabs/#example) to admin.js, call admin.js at the end of admin.html file.

Is there anything else I need to do? For example, should I introduce the admin.js file in tailwind.config.js? (Of course, I did this) or should I enter a special command in the terminal to activate the features related to JavaScript (interactive UI components)? Or add a file to the project? I don't know what I missed.

**Comment by BahramElf** [comment]
sry I think this was not the right way to ask the question here, so I close this

**Comment by aditya-ayare** [comment]
Struggling with the same issue

**Comment by zoltanszogyenyi** [comment]
Hello @BahramElf,

You can import components if you're using ES6 locally. If you're only using it with HTML then I recommend the CDN setup:

https://flowbite.com/docs/getting-started/quickstart/#include-via-cdn

Cheers,
Zoltan

**Comment by BahramElf** [comment]
Hi @zoltanszogyenyi

I want use Tailwind and Flowbite to create pages related to admin panel settings of a WordPress plugin that is not by React and actually is created with PHP, JavaScript, HTML, and CSS. I used CLI npm method and tailwind.config.js to add tailwind and flowbite to project and it worked fine. But now when I get to the part of adding tabs to the page, the tabs don't work and apparently it's related to Javascript and the part of adding Javascript codes related to Flobite tabs. I would be grateful if you could guide me, what is the correct way to do this?

import { Tabs } from 'flowbite'; Where should I put it in codes? In the js file related to the JavaScript codes of the project? (admin-panel.js) Along with the rest of the JavaScript codes? or it's like CSS part and I have to use input.js and output.js?

Or should I put it in tailwind.config.js or enter in CLI npm?
And in the command (import { Tabs } from 'flowbite';), part from 'flowbite'; Is always fixed or does it need to be addressed?
for example as:
import { Tabs } from '.node_modules/flowbite/dist/flowbite.js';
I would be grateful if you could guide me in this matter, because I tried almost all the methods that I mentioned and unfortunately I did not get an answer.
This is my tailwind.config.js file:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
   content: [
     'advncode-.php',
     './view/admin-settings-form.php',
     './view/advanced-setting-form.php',
     './assets/js/*.js',
     './node_modules/flowbite/**/*.js'
   ],
   theme: {
     extend: {},
   },
   plugins: [
     require('@tailwindcss/forms'),
     require('flowbite/plugin')
   ],
   important: '#cmWrapper',
}
```
