### ISSUE TITLE
Can someone tell me how the modal closable works?

### ISSUE THREAD

**Issue by Angel-sg-s** [themesberg/flowbite#707]
Buenos dias, disculpen alguien me puede decir como usar el closable, solo estoy usando a flowbite por cdn, este es mi modal
![code](https://github.com/themesberg/flowbite/assets/114315557/6bbae74e-bcd3-4403-8366-2aebb879cd38)
Podrian ayudarme por favor

**Comment by zoltanszogyenyi** [comment]
Hey @Angel-sg-s,

Not sure what you mean, but if you want the modal to close when clicking outside then you need no change.

If you want it to close only when clicking on the "X" icon then uses the static modal data attributes from here:

https://flowbite.com/docs/components/modal/#static-modal
