### ISSUE TITLE
Datepicker doesn't hide on date selection with autohide true

### ISSUE THREAD

**Issue by aroncal** [themesberg/flowbite#708]
**Describe the bug**
Datepicker doesn't hide on date selection ('onChangeDate' event) with autohide=true.

**Expected behavior**
It should hide.

**Desktop (please complete the following information):**
 - OS: Macos 13.5.2
 - Browser : Chrome 118.0.5993.117 
 - Version: flowbite-datepicker 1.2.4

**Additional context**
Inspecting /node_modules/flowbite-datepicker/dist/js/datepicker-full.js I see this 'hide' function:

```js
    hide() {
      if (!this.active) {
        return;
      }
      this.datepicker.exitEditMode();
      this.element.classList.remove('active', 'block');
      this.element.classList.add('active', 'block', 'hidden');
      this.active = false;
      triggerDatepickerEvent(this.datepicker, 'hide');
    }
```
I think the line in which classes are added, 'active' and 'block' shouldn't be there. If I remove them, it works as expected, like this:

```js
    hide() {
      if (!this.active) {
        return;
      }
      this.datepicker.exitEditMode();
      this.element.classList.remove('active', 'block');
      this.element.classList.add('hidden');
      this.active = false;
      triggerDatepickerEvent(this.datepicker, 'hide');
    }
```

**Comment by zoltanszogyenyi** [comment]
Hey @aroncal,

We pushed a new update with `v2.4.1` for the datepicker. Please check the upgraded API and examples:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour

Cheers,
Zoltan
