### ISSUE TITLE
[BUG] Errors after installing Flowbite

### ISSUE THREAD

**Issue by angelhdzmultimedia** [themesberg/flowbite#71]
**Describe the bug**
I have a basic TypeScript Vue 3 Script Setup + TailwindCSS  app with login form and a home page that creates and load posts. It was working like a charm before installing Flowbite. 

**To Reproduce**
1. Installed Flowbite
2. Added the plugin in the tailwind.config.js
3. Imported in the main.ts

**Expected behavior**
Wanted to use the Tooltip component to try Flowbite for first time.

**Screenshots**
![image](https://user-images.githubusercontent.com/10191085/151645848-cf913c92-4039-4cd6-9d1a-7df6671c4dd2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 64bit latest 
 - Browser: Chrome latest
 - Editor: VSCode latest
 - npm packages versions: 
 
 ![image](https://user-images.githubusercontent.com/10191085/151645963-6482331e-c5bb-40e6-b25d-3e2389d5415a.png)

**Smartphone (please complete the following information):**

**Additional context**
Uninstalling Flowbite fixes the errors.

**Comment by angelhdzmultimedia** [comment]
### UPDATE
It seems like Flowbite is not compatible with TypeScript. I just created a JavaScript Vue 3 fresh app with Vite, installed Flowbite and it's working 100%.

**Comment by aacassandra** [comment]
and not working with nuxt

**Comment by zoltanszogyenyi** [comment]
Hey @angelhdzmultimedia @aacassandra,

You should start using the [Flowbite Vue component library](https://github.com/themesberg/flowbite-vue) if you're using Vue or Nuxt.
