### ISSUE TITLE
apexcharts with angular

### ISSUE THREAD

**Issue by youurt** [themesberg/flowbite#716]
**Describe the bug**
I am trying to add some charts into my angular application, described like here https://flowbite.com/docs/plugins/charts/ - I can't see the charts.

**To Reproduce**
1. Generate angular app, install tailwind and configure flowbite as in docs.
2. Add `charts: true` option to plugins
3. Install `npm install apexcharts --save`
4. Add this example https://flowbite.com/docs/plugins/charts/#area-chart into template as it is
5. Can't see the chart, but the template only, seems like apexcharts can't add the charts to the template

**Expected behavior**
I want to see the charts in the template, just seeing the template only though.

**Screenshots**
<img width="448" alt="Screenshot 2023-11-11 at 22 05 41" src="https://github.com/themesberg/flowbite/assets/39196535/7e1d20b2-65c9-4d22-88ad-7cb9ed21d9f8">

**Desktop (please complete the following information):**
 - OS: MacOs 13.1 (22C65)
 - Browser Chrome
 - Version 119.0.6045.123 (Official Build) (arm64)

**Additional context**
My angular app runs with nx.

**Comment by zoltanszogyenyi** [comment]
Hey @youurt,

Please try to use the Angular version of ApexCharts together with our plugin for styling: https://apexcharts.com/docs/angular-charts/

I believe that the examples we've provided in terms of options can also be used with the Angular version.

Cheers,
Zoltan
