### ISSUE TITLE
Add Right to Left Support

### ISSUE THREAD

**Issue by motahharm** [themesberg/flowbite#72]
## Hello to Flowbite team

Some sites are right to left.
But Flowbite may not work properly on these sites !!!!

Do you have a plan to add right-to-left support?
Can I help you add this feature?

**Comment by zoltanszogyenyi** [comment]
Hey @motahharm,

We're definitely looking into providing RTL support for Flowbite!

Not sure on the methodology, yet. But this has been added to the roadmap.

If you got any ideas on how to get started, share it with us!

**Comment by motahharm** [comment]
I would like to help you in this project.

But I do not know what the structure of the project is.
Is there a map?

Can I add PullRequest to the project?

**Comment by mstfkhazaal** [comment]
@zoltanszogyenyi any update?

**Comment by iiDon** [comment]
@zoltanszogyenyi any update?

**Comment by aeq-dev** [comment]
Any update?

**Comment by ahmadabdelhalim** [comment]
@zoltanszogyenyi it seems that the new version of tailwind supports rtl out of the box. Is that gonna simplify things for flowbite?

**Comment by zoltanszogyenyi** [comment]
Started working on this :)

https://github.com/themesberg/flowbite/pull/678

**Comment by zoltanszogyenyi** [comment]
Fixed with https://github.com/themesberg/flowbite/pull/678. Will be released in `v2.1.0` shortly. Thanks!

**Comment by zoltanszogyenyi** [comment]
RTL is here with v2.1.0!

https://github.com/themesberg/flowbite/releases/tag/v2.1.0
