### ISSUE TITLE
Tabs with JS don't work as expected

### ISSUE THREAD

**Issue by Sulfyderz** [themesberg/flowbite#734]
**Describe the bug**
The JS part of tab doesn't work as expected (described [here](https://flowbite.com/docs/components/tabs/#javascript-behaviour)).
I have copied and pasted your example and here are the bugs :

1. `const tabs = new Tabs(tabsElement, tabElements, options, instanceOptions);`, you have to change the position of `tabsElement` with `tabElements`. Otherwise, the tab doesn't work;
2. Even if you give the `options` argument to `new Tabs(tabsElement, tabElements, options, instanceOptions);`, it doesn't take it into consideration at all... `defaultTabId`, `activeClasses`, `inactiveClasses` and `onShow` are not taken into consideration;
3. The unexpected workaround to only replicate `activeClasses` is to use `aria-selected:` selector to style the currently active tab.

**To Reproduce**
1. Just copy and paste the example given in the official website [here](https://flowbite.com/docs/components/tabs/#javascript-behaviour).

**Expected behavior**
`const tabs = new Tabs(tabsElement, tabElements, options, instanceOptions);` should work as described [here](https://flowbite.com/docs/components/tabs/#javascript-behaviour).

**Desktop:**
 - OS: macOS Sonoma 14.1.1
 - Browser: Safari 17.1

**Additional context**
- Django 4.2
- Flowbite & Tailwind installed through NPM.

**Comment by dylanjcastillo** [comment]
I also came across the same issue.

**Comment by Sulfyderz** [comment]
> I also came across the same issue.

Use the version 2.0.0. Not later.

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

I've used the example from the docs and updated the colors to `red` and seems to work with JS:

<img width="876" alt="Screenshot 2024-01-26 at 15 45 34" src="https://github.com/themesberg/flowbite/assets/8052108/3f565446-7373-45c8-be71-3a8415c709a4">

Is the issue still persisting?

Thanks,
Zoltan
