### ISSUE TITLE
Carousel don't show item when they have only 1

### ISSUE THREAD

**Issue by kichetof** [themesberg/flowbite#740]
Hello,

Thanks for your excellent library, really enjoy it!! 🔥

I've discover a bug with a Carousel who get items from external API.
When you've only 1 item, you get a white screen (item is on the right overflow)

Bug with latest version 2.2.0 (and certainly before, but not yet tested)
I reproduced it with the doc example  https://jsfiddle.net/jmto6b9e/3/

As you can see, nothing is displayed with only 1 item
<img width="942" alt="Capture d’écran 2023-12-01 à 11 49 13" src="https://github.com/themesberg/flowbite/assets/12150996/74ed5ad1-e0cc-4341-9fe4-ce92563c6f53">

When you've 2 or more items, you'll see it:
<img width="933" alt="Capture d’écran 2023-12-01 à 11 50 19" src="https://github.com/themesberg/flowbite/assets/12150996/4a9a0783-7bf5-45b9-b785-a85693408865">

I hope that you'll have a fix for it :)
Thanks a lot!
Cheers

**Comment by kichetof** [comment]
Happy new year! 🎉

This issue will be resolved when #550 will be merged :)

**Comment by zoltanszogyenyi** [comment]
Fixed with the new PR merge. Thanks!
