### ISSUE TITLE
Users can scroll background when modal is open

### ISSUE THREAD

**Issue by vascocarreira** [themesberg/flowbite#741]
Hi,

When using Flowbite's modals, users can scroll the background.
Does Flowbite provide a flag/directive to prevent this?

Regards

**Comment by zoltanszogyenyi** [comment]
Hey @vascocarreira,

You can apply the `overflow-y-none` utility class from Tailwind CSS to the body of the modal to prevent the scroll.

Cheers,
Zoltan
