### ISSUE TITLE
Flowbite integration with new Qwik version with warning

### ISSUE THREAD

**Issue by nelsonprsousa** [themesberg/flowbite#757]
**Describe the bug**
New eslint warning with new Qwik version (1.3.1):
![image](https://github.com/themesberg/flowbite/assets/8364345/5e287870-21c1-4218-b2f8-d8eec86784f1)

**To Reproduce**
1. Integrate Flowbite with the new Qwik version

**Expected behavior**
No warnings with default installation.

**Comment by zoltanszogyenyi** [comment]
Hey @nelsonprsousa,

This seems to be an ESLint warning related to Qwik and not to the Flowbite related functions.

Cheers,
Zoltan

**Comment by nelsonprsousa** [comment]
Yes, it is a ESLint related with the integration with Qwik. However, this means that Flowbite isn't properly following Qwik's philosophy. JS should only be loaded on request, and not using useVisibleTask.

I'd not recommend this approach for Qwik apps.

cc @zoltanszogyenyi
