### ISSUE TITLE
Performance issues with Flowbite on Lighthouse

### ISSUE THREAD

**Issue by aryanshirani** [themesberg/flowbite#761]
**Describe the bug**
If you run the website on lighthouse like in our test, where we used the Flowbite website, we really have bad scores.

**To Reproduce**
1. Go to any pages of flowbite.com
2. Get the url
3. Run it on lighthouse from the inspection dev tool of chrome or use google site speed checker
4. You will see the error in the results

**Expected behavior**
Those are really simple and small elements that takes a lot of time to load

**Screenshots**
https://imgur.com/a/1SaNj42

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome
 - Version: 120.0.6099.119 / 12 December 2023

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS17.2.1
 - Browser: Safari
 - Version: 17.2

**Additional context**
We tested directly on the website of Flowbite, and look like performance issues are quite big for elements that are really small, so we don't understand how this is possible.

**Comment by zoltanszogyenyi** [comment]
Hey @aryanshirani,

Thanks for opening up the issue.

I ran a test on Lighthouse: https://pagespeed.web.dev/analysis/https-flowbite-com/rqde219ej7?form_factor=desktop

The Flowbite components and JS are not responsible for the Lighthouse result, our homepage contains a lot of SVG markup and third-party JS plugins (ie. YouTube, Crisp) that block rendering, hence why the pages have a higher loading time.

<img width="1023" alt="Screenshot 2023-12-27 at 19 26 48" src="https://github.com/themesberg/flowbite/assets/8052108/1af80a60-2b5e-4ad3-beb2-2a9e4d0fbf9f">

<img width="1008" alt="Screenshot 2023-12-27 at 19 26 40" src="https://github.com/themesberg/flowbite/assets/8052108/ee1c48d5-8836-465e-bc7b-d107540a4de6">

Of course, we continously try to improve performance for our own website, but currently we're focused on releasing new features and resolving current bugs for the library.

The Lighthouse performance of the homepage doesn't have anything to do with the Flowbite library itself.

Thanks,
Zoltan

**Comment by aryanshirani** [comment]
Hello,
I'm sorry to see that you did not dig in the screenshot and just ignored the ones I added,
you could see that the test was also runned on basic text pages like this: https://flowbite.com/license/
<img width="1500" alt="Screenshot 2023-12-27 at 18 33 51" src="https://github.com/themesberg/flowbite/assets/32386631/bb3884ec-f7f8-4262-9396-0dd9173570f8">
<img width="1568" alt="Screenshot 2023-12-27 at 18 33 21" src="https://github.com/themesberg/flowbite/assets/32386631/2c1e6b83-3fb5-4e22-ad19-3b3584859175">

So there is no other elements than text and in the screenshot we have the details

**Comment by zoltanszogyenyi** [comment]
Hey @aryanshirani,

I've ran the test for this page: https://flowbite.com/license/ (https://pagespeed.web.dev/analysis/https-flowbite-com-license/b3r1ttty12?form_factor=desktop)

I believe that the rendering issue could be to two reasons:

- font loading
- the `antialiased` class that is being added for font smoothing

**Comment by aryanshirani** [comment]
Very strange I really have no clue why we get this issues on google page speed



Aryan Shirani
CEO & Full Stack Designer
at Blurr

+39 377 093 54 29
***@***.***
www.blurr.it
Via III Novembre 35/1, 38060 Calliano, Trento
