### ISSUE TITLE
The toggle switch does not work correctly on mobile

### ISSUE THREAD

**Issue by ignaciolarranaga** [themesberg/flowbite#767]
**Describe the bug**
On mobile:
- does not align well if the text doesn't fit in one line
- the transition has a blue background which extends over the label

**To Reproduce**
Just put a couple of toggles with a large description

**Expected behavior**
- the toggle aligns correctly when it has more than 1 line
- the transition does not show a blue background when transitioning

**Screenshots**
<img width="493" alt="Screenshot 2024-01-06 at 09 37 28" src="https://github.com/themesberg/flowbite/assets/15932965/cfddf3d2-d195-4610-b38d-b58cce4f66b1">

**Comment by zoltanszogyenyi** [comment]
Fixed via https://github.com/themesberg/flowbite/commit/902e2ea084b0eccd6749d32779fdcdb9d1a0daa6. Will be released with `v2.3` soon. Thanks!
