### ISSUE TITLE
Datepicker Icon and date overlap when using Flowbite React in Astro.JS project

### ISSUE THREAD

**Issue by codewriter3000** [themesberg/flowbite#771]
**Describe the bug**
I'm using the Flowdate date picker in Astro.JS and I see an overlap between the icon and the date text, as well as no padding on to the left side. Also, when I click on the datepicker it should display a calendar but it doesn't do anything.

**To Reproduce**
1. Create an Astro project
2. Enable React
3. Install flowbite-react
4. Drop this in an Astro page:
```jsx
import { Datepicker } from 'flowbite-react';
...
<Datepicker />
```

**Expected behavior**
I expect it to work as expected.

**Screenshots**
![image](https://github.com/themesberg/flowbite/assets/58712923/33ad3652-2028-4d53-aac0-c5fe60009521)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Microsoft Edge 120.0.2210.121
 - Version: 0.7.2

**Comment by Abhishekbharti9910** [comment]
Same Issue encountered did you got the solution for this or any alternatives.

**Comment by dlopesa** [comment]
Same issue, so far no reply

**Comment by raphaelalingig** [comment]
same in reactjs still overlapping still no fix

**Comment by dlopesa** [comment]
I was able to fix it

**Comment by dlopesa** [comment]
go on the tailwind config and make sure you have these:
`content: ['./src/**/*.{js,jsx,ts,tsx}', '/node_modules/tailwind-datepicker-react/dist/**/*.js',  './public/index.html', './resources/js/**/*.js', './node_modules/flowbite/**/*.js', 'node_modules/flowbite-react/lib/esm/**/*.js','./node_modules/react-tailwindcss-datepicker/dist/index.esm.js', flowbite.content(),],` and `plugins: [
    flowbite.plugin(),
  ],`
  
  also add this on top
`const flowbite = require("flowbite-react/tailwind");`

That fixed it for me

**Comment by dlopesa** [comment]
this is the all file:
```
/** @type {import('tailwindcss').Config} */
const flowbite = require("flowbite-react/tailwind");
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', '/node_modules/tailwind-datepicker-react/dist/**/*.js',  './public/index.html', './resources/js/**/*.js', './node_modules/flowbite/**/*.js', 'node_modules/flowbite-react/lib/esm/**/*.js','./node_modules/react-tailwindcss-datepicker/dist/index.esm.js', flowbite.content(),],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        'color1': '#fb6b5c',
        'color1-2': '#cb5c57',
        'color1-3': '#954f4e',
        'color2': '#28353b',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    flowbite.plugin(),
  ],
};
```

**Comment by zoltanszogyenyi** [comment]
@dlopesa is right, you need to make sure the tailwind config paths are correct
