### ISSUE TITLE
Dropdown button sometimes work, sometimes not work

### ISSUE THREAD

**Issue by zamcoder** [themesberg/flowbite#779]
### Summary of problem or feature request

hello, can you please help me with this problem
i have issue that my dropdown button sometimes work, but sometimes not work

i use tailwind css and flowbite, i already make unique id in every dropdown button, but still not work

My action dropdown button
![image](https://github.com/yajra/laravel-datatables/assets/76896394/7f178555-7587-4cd1-9b75-02d388c690e5)

my controller
![image](https://github.com/yajra/laravel-datatables/assets/76896394/17ee47e0-ca4d-4fc2-93ec-f90af57f29a0)

### System details

- Operating System Windows 10 (Local)
- PHP Version 8.1
- Laravel Version 10.10
- Laravel-Datatables Version 10.0

**Comment by zamcoder** [comment]
fixed using this added code into javascript 

![image](https://github.com/themesberg/flowbite/assets/76896394/6f4fb27f-a1af-435c-a331-30d3baa60125)

**Comment by zamcoder** [comment]
fixed using this added code into javascript 

![image](https://github.com/themesberg/flowbite/assets/76896394/6f4fb27f-a1af-435c-a331-30d3baa60125)

**Comment by r4cker** [comment]
I had the same probleme but i fixed it like this (I have no js framework)

in app.js

```
import * as flowbite from 'flowbite';
global.flowbite = flowbite;
```

In my page : 
`flowbite.initDropdowns();`
