### ISSUE TITLE
Input component, when the type is set to password, the "show hidden" icon cannot be displayed and switched as expected.

### ISSUE THREAD

**Issue by graphsay** [themesberg/flowbite#781]
**Describe the bug**
1,Input component, when the type is set to password, the "show hidden" icon cannot be displayed in the latest firefox,however it could be displayed in chrome or edge. 
2,In edge,When the input box loses focus, the button("show hidden" icon) will disappear. After regaining focus, the button will still not be displayed, which is not consistent with usage habits. Often when we submit and find that the password is wrong, we need to switch  to display the password and modify it ,but  at this time  the button("show hidden" icon) cannot be displayed and switched as expected.
**To Reproduce**
for the latest firefox
1. Go to 'https://flowbite.com/docs/components/forms/#default-form'
2. Type any characters into the password input box,the he "show hidden" icon could not be displayed as expected

for chrome and edge
1. Go to 'https://flowbite.com/docs/components/forms/#default-form'
2. Type any characters into the password input box,the he "show hidden" icon could will display as expected
3. Click on 'submit'
4.Refocus on the password input box，
5. See error: the  "show hidden" icon cannot be displayed and switched as expected.

**Expected behavior**
1,the "show hidden" icon should work well in firefox and webview.
2,the "show hidden" icon will always displayed when focusing on the password input box

**Screenshots**
![图片](https://github.com/themesberg/flowbite/assets/32170136/ce1af65f-a925-4086-8810-b5d2b7542702)
![图片](https://github.com/themesberg/flowbite/assets/32170136/68bca8fa-842a-4fd6-96da-47e1291777fd)

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [ edge120.0.2210.121 and firefox 121.0.1]

**Additional context**
thanks a lot!

**Comment by alfi-dim** [comment]
Still have this issue on edge 127.0.2651.86, is there any solution for this?
