### ISSUE TITLE
Responsive Sidebar

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#80]
## Feature request for a responsive sidebar

Adding [a sidebar (like this)](https://kit.svelte.dev/docs) component.

**Comment by zoltanszogyenyi** [comment]
We had this on the roadmap already :)

ETA probably end of the month.

**Comment by shinokada** [comment]
See [https://flowbite-svelte.com/](https://flowbite-svelte.com/). It shows sidebar menu for a wide screen and close it for a smaller screen.
You can see the code in [+layout.svelte](https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/%2Blayout.svelte). 
I'm on the process of writing how to do it for a blog post and let you know once it is done.

**Comment by shinokada** [comment]
Meanwhile, have a look at this [repo, flowbite-sveltekit-responsive-sidebar-layout](https://github.com/shinokada/flowbite-sveltekit-responsive-sidebar-layout). 

You can find [demo](https://flowbite-sveltekit-responsive-sidebar-layout.vercel.app/).
