### ISSUE TITLE
Country flags source

### ISSUE THREAD

**Issue by nelsonprsousa** [themesberg/flowbite#814]
Hi team,

Thank you for your awesome work with this lib.

Can you please provide the sources of the country flags Flowbite blocks are using?

They look pretty similar to https://flagicons.lipis.dev/  (also OSS: https://github.com/lipis/flag-icons) but I couldn't find any reference. Also, the code is a little bit different, so maybe there were some adjustments as well?

Thank you

**Comment by joska1993** [comment]
+1

**Comment by zoltanszogyenyi** [comment]
Hey @nelsonprsousa,

They can be found inside the Figma file here:

https://flowbite.com/figma/

Available also on the free edition. We might create a page to easily export them like with [Flowbite Icons](https://flowbite.com/icons/) though.

Cheers,
Zoltan
