### ISSUE TITLE
[Documentation] GitHub’s unauthenticated API rate limit crashes Flowbite website’s homepage

### ISSUE THREAD

**Issue by dtinth** [themesberg/flowbite#819]
**Describe the bug**
The whole website crashes when contributor list cannot be loaded due to GitHub’s unauthenticated API rate limit.

> Application error: a client-side exception has occurred (see the browser console for more information).

**To Reproduce**
1. Go to https://flowbite.com/

2. Get your IP address rate-limited by GitHub (e.g. by using a co-working space’s public wifi network)

   <img width="714" alt="image" src="https://github.com/themesberg/flowbite/assets/193136/7d80a096-43f1-4133-91f7-c9efcce07258">

**Expected behavior**
Error should not crash the whole page. Maybe add an error boundary?

**Screenshots**
<img width="1427" alt="image" src="https://github.com/themesberg/flowbite/assets/193136/b62cb98c-13bf-41ff-bb48-32c785034843">

**Comment by zoltanszogyenyi** [comment]
Hey @dtinth,

Thanks for the reporting! I'll have a look at this today.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
I've just pushed a fix for this. I'll close the issue if no further errors happen.
