### ISSUE TITLE
Support the Popover api

### ISSUE THREAD

**Issue by xcaptain** [themesberg/flowbite#842]
Please support the new Popover api: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API 

With this, we can achieve dropdown menu, modal without writting js

**Comment by zoltanszogyenyi** [comment]
Hey @xcaptain,

We will consider it, but the dropdowns that we have also calculate the width and height of the container.

This means that it could still be more advantageous to use our current API as opposed to the new HTML Popover.

Cheers,
Zoltan
