### ISSUE TITLE
DatePicker does not work in Blazor wasm

### ISSUE THREAD

**Issue by vincentnl** [themesberg/flowbite#844]
Just importing the js does not cause the datedropdown to show.

should the initFlowbite be extended upon to include the datepicker?

https://flowbite.com/docs/getting-started/blazor/

**Comment by zoltanszogyenyi** [comment]
Hey @vincentnl,

The new datepicker update has arrived in `v2.4.1` so please try again:

https://flowbite.com/docs/components/datepicker/index.html#javascript-behaviour

It is now part of the instances and will initialize when calling `initFlowbite()` too.

Cheers,
Zoltan

**Comment by NathanVG** [comment]
I am also having issues with this: 

https://github.com/themesberg/flowbite/issues/986

I am using <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
