### ISSUE TITLE
Dropdown close with trigger type hover 

### ISSUE THREAD

**Issue by bhavik712** [themesberg/flowbite#845]
I am using mega menu in my project with trigger type is hover. When I click on my submenu technically my cursor is inside the menu box dropdown so when I tried with this:
const dropdown = FlowbiteInstances.getInstance('Dropdown', id)
  dropdown.toggle()
  
  I am not getting close my megamenu

**Comment by zoltanszogyenyi** [comment]
Hey @bhavik712,

Dropdowns can be closed or opened via hover already:

https://flowbite.com/docs/components/dropdowns/#dropdown-hover

Cheers,
Zoltan
