### ISSUE TITLE
Datarange picker does not become inline

### ISSUE THREAD

**Issue by Mauro207** [themesberg/flowbite#856]
The datarange picker cannot be put inline in any way. Using the current attributes, the datarange picker cannot be fixed.

**Comment by zoltanszogyenyi** [comment]
Hey @Mauro207,

Unfortunately it is not currently possible to add a date range picker inline.

However, you can add two separate inline datepickers and take the value from each of them.

It would get to the same result, the difference would be the lack of the range bar only.

Thanks,
Zoltan
