### ISSUE TITLE
Modal over Modal, can not be removed appropriately

### ISSUE THREAD

**Issue by monster-echo** [themesberg/flowbite#858]
When I have a Modal over another Modal.

The top modal backdrop is not cover the bottom Modal by the z-40. 

if I add the top Modal backdrop with z-50 and Modal with z-[60], it's worked. 

but when removed the top Modal. it fails, because the the top Modal backdrop is alive and bottom Modal backdrop is destroyed.

https://github.com/themesberg/flowbite/blob/30b276bfd19cbb4592612fcff2161b0a0e589243/src/components/modal/index.ts#L88-L95

**Comment by zoltanszogyenyi** [comment]
Hey @monster-echo,

Should be fixed via your PR. Thanks!
