### ISSUE TITLE
Typo in Flowbite Blocks Website 

### ISSUE THREAD

**Issue by kerimovok** [themesberg/flowbite#874]
**Describe the bug**
Typo in register form, [Create and account] -> [Create an account]

**To Reproduce**
1. Go to [Flowbite Blocks](https://flowbite.com/blocks/marketing/register/)
2. Scroll down to the first form
4. See typo

**Expected behavior**
[Create and account] -> [Create an account]

**Screenshots**
![image](https://github.com/themesberg/flowbite/assets/136202877/5da8a165-83ed-49bb-aed8-c074a12aa682)

**Comment by kerimovok** [comment]
Also, there is no such class as `ring-3`

In first block
[Flowbite Blocks - Login Form](https://flowbite.com/blocks/marketing/login/#:~:text=gray%2D50%20focus%3A-,ring%2D3,-focus%3Aring%2Dprimary)

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

Thanks for the reports!

1. Typo in the register form is now fixed
2. Fixed the `items-center` class for the checkout block

Please create separate issues though for better tracking, thanks!

Zoltan
