### ISSUE TITLE
Backdrop not hiding when hide() function is call

### ISSUE THREAD

**Issue by AzPogoDev** [themesberg/flowbite#875]
**Describe the bug**
When I click on my hide() function the modal is hidding, but i steal show the backdrop

**Comment by Lexachoc** [comment]
I've had this issue before with the backdrop not hiding. I fixed the issue by changing the `z-index` value, but it may be different in your case (not sure as you didn't provide the minimal code).

It may be related to https://github.com/themesberg/flowbite/issues/858#issue-2242596726 and may be resolved by https://github.com/themesberg/flowbite/pull/859#issue-2242610350

**Comment by zoltanszogyenyi** [comment]
Should be fixed via this https://github.com/themesberg/flowbite/commit/6a610096a9f6630fc2a30a2894e308bf351d33e0. Will be added to the next NPM release in a couple of days. Thanks!

**Comment by JungleHH** [comment]
@zoltanszogyenyi  Hasn't release yet? I have the same issue in npm v2.4.1 :(

**Comment by zoltanszogyenyi** [comment]
Hey @JungleHH,

In what context of a framework are you using it?

Cheers,
Zoltan

**Comment by JungleHH** [comment]
oh! Thanks for your response so quickly!
I use vite + vue3.
The latest version has solve it? If i should wait for the next release?

**Comment by JungleHH** [comment]
oh! Thanks for your response so quickly!@zoltanszogyenyi 
I use vite + vue3.
The latest version has solve it? If i should wait for the next release?

**Comment by JungleHH** [comment]
Additionally, issue occurs in v-for tag. It works well when invoke modal.hide() out of v-for.
Here is my code:
```
function initSchemeModal(elementId: string): Modal {
  // set the modal menu element
  const $modalElement: HTMLElement | null = document.querySelector(elementId);

  const modalOptions: ModalOptions = {
    placement: "bottom-right",
    backdrop: "dynamic",
    backdropClasses: "bg-gray-900/50 dark:bg-gray-900/80 fixed inset-0 z-40",
    closable: true,
    onHide: () => {
      // console.log("modal is hidden");
    },
    onShow: () => {
      // console.log("modal is shown");
    },
    onToggle: () => {
      // console.log("modal has been toggled");
    },
  };
  // instance options object
  const instanceOptions: InstanceOptions = {
    id: elementId,
    override: true,
  };
  return new Modal($modalElement, modalOptions, instanceOptions);
}

let modal: Modal;
onMounted(() => {
  initModals();
  modal = initSchemeModal("#select-scheme-modal");
});

function openModal() {
  modal.toggle();
}
function closeModal() {
  if (modal) {
    console.log("close modal");
    modal.hide();
  }
}
```

**Comment by JungleHH** [comment]
It is my fault. 
I call modal.hide() in v-for tags and forget to set attribute data-modal-target.

Thanks!
