### ISSUE TITLE
Rails install documentation incomplete

### ISSUE THREAD

**Issue by swombat** [themesberg/flowbite#880]
**Describe the bug**
Rails install doc mentions `datepicker` in the turbo section but does not mention installing the package.

**To Reproduce**
1. Follow instructions
2. Run project
3. See error while building/running the server:

```
09:10:00 js.1               | ✘ [ERROR] Could not resolve "flowbite-datepicker"
09:10:00 js.1               | 
09:10:00 js.1               |     app/javascript/application.js:34:7:
09:10:00 js.1               |       34 │ import 'flowbite-datepicker'
09:10:00 js.1               |          ╵        ~~~~~~~~~~~~~~~~~~~~~
09:10:00 js.1               | 
09:10:00 js.1               |   You can mark the path "flowbite-datepicker" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
09:10:00 js.1               | 
```

**Expected behavior**
If you follow the instructions, things should work.

**Suggested docs fix**
Mention somewhere that to get the `datepicker` you have to run:

```
npm install flowbite-datepicker
```

**Comment by zoltanszogyenyi** [comment]
Hey @swombat,

The datepicker is now a core component of the main package so you no longer need to install the plugin:

https://flowbite.com/docs/getting-started/rails/#datepicker

Cheers,
Zoltan
