### ISSUE TITLE
[Typo]: dark:hover:bg-bray-800 -> dark:hover:bg-gray-800

### ISSUE THREAD

**Issue by kerimovok** [themesberg/flowbite#882]
**Describe the bug**

**To Reproduce**
1. Go to [Flowbite Forms - File Input](https://flowbite.com/docs/forms/file-input/#:~:text=dark%3Ahover%3Abg%2D-,bray,-%2D800%20dark%3Abg)
2. Scroll down to 'Dropzone'
3. See error

**Expected behavior**
dark:hover:bg-bray-800 -> dark:hover:bg-gray-800

**Screenshots**
![image](https://github.com/themesberg/flowbite/assets/136202877/a46cd38c-8a86-4d54-a7c4-7dca98afe714)

**Comment by zoltanszogyenyi** [comment]
Fixed this in `v2.4.1` - thanks!
