### ISSUE TITLE
Demo Documentation for Tabs broken

### ISSUE THREAD

**Issue by christoferd** [themesberg/flowbite#890]
**Describe the bug**
Some demos in Documentation > Tabs 

**To Reproduce**
1. Go to https://flowbite.com/docs/components/tabs/
2. Click on the button/tab you see in the image below...

**Expected behavior**
Switch tabs content

**Screenshots**
![image](https://github.com/themesberg/flowbite/assets/1835883/35d38faf-6061-4b26-b331-fc2011bc1aa9)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: MS Edge
 - Version: the latest version

**Smartphone (please complete the following information):**
Did not test on smartphone.

**Additional context**
No.

**Comment by Lexachoc** [comment]
Hi~These are just designs, so they are not actually broken.
You need to add attributes to the elements to make them switchable.
Check https://flowbite.com/docs/components/tabs/#interactive-tabs

**Comment by zoltanszogyenyi** [comment]
@Lexachoc is right, the first few examples are static. We might update them though in the future.
