### ISSUE TITLE
Remix Installation Documentation Not Working

### ISSUE THREAD

**Issue by Odinvt** [themesberg/flowbite#892]
**Describe the bug**
By configuring tailwind content like this :
```typescript
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./node_modules/flowbite-react/**/*.js"
  ],
  plugins: [
    // other plugins...
    require("flowbite/plugin")
  ],
  theme: {},
};
```

Flowbite doesn't work unless you do this instead :

```typescript
import type { Config } from 'tailwindcss'

export default {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    "./node_modules/flowbite-react/**/*.{js,cjs}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require("flowbite/plugin"),
  ],
} satisfies Config
```

**To Reproduce**
1. Follow the Flowbite Remix installation docs.

**Expected behavior**
Flowbite examples should work out of the box.

**Versions:**
 - "flowbite": "2.3.0"
 - "flowbite-react": "0.9.0"
 - NodeJS v22.2.0 x64

**Comment by zoltanszogyenyi** [comment]
Hey @Odinvt,

Thanks a lot for the issue! If you want to, you're welcome to update our Remix docs here: https://github.com/themesberg/flowbite/blob/main/content/getting-started/remix.md

I'll review the PR and pull in @SutuSebastian too for a double check, he's the master maintainer for Flowbite React :)

Cheers,
Zoltan

**Comment by SutuSebastian** [comment]
Indeed the [Remix guide](https://flowbite.com/docs/getting-started/remix/) is outdated and is referencing an old version of `flowbite-react` (< `0.8.x`).

Also the [remix starter template](https://github.com/tulupinc/flowbite-remix-starter) link needs to be updated to the new official repo [flowbite-react-template-remix](https://github.com/themesberg/flowbite-react-template-remix).

**Comment by zoltanszogyenyi** [comment]
@SutuSebastian can you help do a PR on this Remix update for our docs? <3

**Comment by SutuSebastian** [comment]
> @SutuSebastian can you help do a PR on this Remix update for our docs? <3

Ofc 🚀
