### ISSUE TITLE
How to change the language for datepicker when using СDN?

### ISSUE THREAD

**Issue by devmitrandir** [themesberg/flowbite#897]
Hello.
I want to use dakatpicker as сdn.
How to change language?

`<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>`

This does not work. Datepicker not found
```
<script>
Datepicker.locales.fr = ...
<script>
```

**Comment by Lexachoc** [comment]
I haven't tested it yet but in the [documentation ](https://github.com/themesberg/flowbite-datepicker/blob/master/docs/i18n.md#for-browser) the locale file is mentioned. Perhaps that's what you're looking for.

**Comment by zoltanszogyenyi** [comment]
Hey @devmitrandir, @Lexachoc,

Please check the solution here: https://github.com/themesberg/flowbite/issues/32

Will add to the docs.
