### ISSUE TITLE
Accordion doesn't open unless I refresh the browser

### ISSUE THREAD

**Issue by brianshimkus** [themesberg/flowbite#91]
**Description**: I have the accordion component on a page and when going to that page from the home page and I click on one of the tabs, nothing happens and the tab doesn't open. Now if I refresh the browser while already on the page, the accordion then will open on click.

**Comment by zoltanszogyenyi** [comment]
Hey @brianshimkus,

What tech stack are you using? Is there any online preview?

Thanks.

**Comment by brianshimkus** [comment]
@zoltanszogyenyi This is a site that was created with Create React App. I don't have an online preview as this is for work and in a private repo for the time being. 

Unless the accordion is on the originally rendered route, it won't work and I have to refresh the browser to get it to work again.

**Comment by brianshimkus** [comment]
@zoltanszogyenyi I think this is the same issue as #86

**Comment by samuelsteven0902** [comment]
what is ur solution ? 

> @zoltanszogyenyi This is a site that was created with Create React App. I don't have an online preview as this is for work and in a private repo for the time being.
> 
> Unless the accordion is on the originally rendered route, it won't work and I have to refresh the browser to get it to work again.

**Comment by fasaya** [comment]
Same problem here. I'm using Nuxt3.

**Comment by aliaz-programmer** [comment]
[fasaya](https://github.com/fasaya) your saved my day 😊👌
