### ISSUE TITLE
2.4.1 javascript cdn url 404 not found

### ISSUE THREAD

**Issue by mukiwu** [themesberg/flowbite#910]
**Describe the bug**
the cdn url: https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.4.1/flowbite.min.js
is not found

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hey @mukiwu,

Will soon be available, until then please use:

```
https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js
```

Cheers,
Zoltan

**Comment by mukiwu** [comment]
got it ! thanks
