### ISSUE TITLE
CDN Resources return 404

### ISSUE THREAD

**Issue by mazz** [themesberg/flowbite#914]
`curl https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.4.1/flowbite.min.css`

and 

`curl https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.4.1/flowbite.min.js`

return 404

**Comment by zoltanszogyenyi** [comment]
Hey @mazz,

CDNJS reported internal issues so we switched to another CDN provider: https://www.jsdelivr.com/package/npm/flowbite

Cheers,
Zoltan
