### ISSUE TITLE
Incorrect Type for autoSelectToday in DatePickerOptions

### ISSUE THREAD

**Issue by andreweberle** [themesberg/flowbite#916]
**Describe the bug**
The `autoSelectToday` property in the `DatePickerOptions` object is incorrectly documented as a boolean when it is actually defined as a number in the codebase.

**To Reproduce**
1. Initialize a `DatePickerOptions` object with `autoSelectToday` set to a number, e.g., `1` or `0` to replicate a `boolean` 
2. Attempt to use the datepicker functionality relying on `autoSelectToday`.
3. Observe that `autoSelectToday` does not behave as expected based on the documentation.

`const datePickerOptions = {
 defaultDatepickerId: null,
  autohide: false,
  format: 'dd/mm/yyyy',
  maxDate: null,
  minDate: null,
  orientation: 'bottom-right',
  buttons: false,
  autoSelectToday: 1,
  title: null,
  language: 'en',
  rangePicker: false,
} as DatepickerOptions;`

**Expected behavior**
`autoSelectToday` should be documented and typed consistently as a boolean in the `DatePickerOptions` interface, allowing it to correctly indicate whether today's date should be preselected.

**Comment by zoltanszogyenyi** [comment]
Hey @andreweberle,

As the parent library uses 0 and 1 instead of `false` and `true` it will most likely stay with numbers.

I'll update the docs from boolean now so that there is no confusion here.

Cheers,
Zoltan

**Comment by andreweberle** [comment]
@zoltanszogyenyi 
No worries at all mate :)
