### ISSUE TITLE
[vite] Error when evaluating SSR module /main.server.mjs: failed to import "/chunk-RUDII4PE.mjs" Angular SSR 

### ISSUE THREAD

**Issue by eideard-hm** [themesberg/flowbite#918]
**Describe the bug**
When updating to the new version 2.4.1 I get an error when trying to compile the flowbite package; it gives me the following error:
![image](https://github.com/themesberg/flowbite/assets/82130680/174e8358-144c-43eb-bdfd-6894aed4da46)

I am currently using angular version 18.0.5. 
![image](https://github.com/themesberg/flowbite/assets/82130680/dd14af08-c788-4eb6-9987-8b93e086472c)

**To Reproduce**
1. Go to ' package.json and install the latest flowbite version'
2. Install the new versión
3. Running the project with @angular/ssr
4. Check the error on console

**Expected behavior**
When I'm running the project I should not get the error, as far as I can see the error is because of the package flowbite-datepicker which, by the way, I do not use in the project

![image](https://github.com/themesberg/flowbite/assets/82130680/5fadbce3-3ee6-402c-b7cf-fef3a00d1394)

**Comment by eideard-hm** [comment]
It should be noted that the error disappears using the previous version: 2.3.0.

**Comment by zoltanszogyenyi** [comment]
Hey @eideard-hm,

Is there a way you can only import and use Flowbite when using a client server?

Here's an updated Nuxt guide for this type of situation:

https://flowbite.com/docs/getting-started/nuxt-js/#data-attributes

Cheers,
Zoltan

**Comment by eideard-hm** [comment]
Hey @zoltanszogyenyi 

Thank you in advance for reviewing the issue. 

I am initializing the flowbite instance when it detects that it is in the browser and not in the server.
![image](https://github.com/themesberg/flowbite/assets/82130680/79f574a3-e21a-4220-8370-bd1ee03f8cc9)

**Comment by zoltanszogyenyi** [comment]
Hey @eideard-hm,

Please check this new guide:

To enable using Flowbite with SSR (Server-Side Rendering) you need to create a custom service that will handle the dynamic import of Flowbite:

```javascript
// src/app/services/flowbite.service.ts
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class FlowbiteService {
  constructor(@Inject(PLATFORM_ID) private platformId: any) {}

  loadFlowbite(callback: (flowbite: any) => void) {
    if (isPlatformBrowser(this.platformId)) {
      import('flowbite').then(flowbite => {
        callback(flowbite);
      });
    }
  }
}
```

After that, you can use this service in your component to start using the Flowbite API and data attributes:

```javascript
// src/app/components/some-component/some-component.component.ts
import { Component, OnInit } from '@angular/core';
import { FlowbiteService } from '../../services/flowbite.service';

@Component({
  selector: 'app-some-component',
  templateUrl: './some-component.component.html',
  styleUrls: ['./some-component.component.css']
})
export class SomeComponent implements OnInit {
  constructor(private flowbiteService: FlowbiteService) {}

  ngOnInit(): void {
    this.flowbiteService.loadFlowbite(flowbite => {
      // Your custom code here
      console.log('Flowbite loaded', flowbite);
    });
  }
}
```

This will prevent the "document is undefined" error that happens after upgrading to `v2.4.1` for SSR applications.

https://flowbite.com/docs/getting-started/angular/#using-with-angular-ssr

Cheers,
Zoltan

**Comment by eideard-hm** [comment]
I'll try it out and let you know
Cheers,
Edier Hernandez

**Comment by eideard-hm** [comment]
To complement this you can initialize the whole flowbite instance or just the components you want.

The solution worked well for me, thank you very much!
![image](https://github.com/themesberg/flowbite/assets/82130680/1676fcfa-67e5-405f-9514-b845d0740532)

Cheers,
Edier Hernandez

**Comment by zoltanszogyenyi** [comment]
Even better if you want to optimize. Glad it works, mate 💙
