### ISSUE TITLE
datepicker causing error in ssr in the version v2.4.1 (document is not defined)

### ISSUE THREAD

**Issue by tawfikyassine** [themesberg/flowbite#921]
![Capture d’écran 2024-07-04 120913](https://github.com/themesberg/flowbite/assets/125127556/6d2ba508-8355-437c-80e3-9ec66ea1e80b)

version with problem : [v2.4.1](https://github.com/themesberg/flowbite/releases/tag/v2.4.1)

there is no problem with this version : [v2.3.0](https://github.com/themesberg/flowbite/releases/tag/v2.3.0)

Im using Vuejs3 with laravel using inertiajs ssr

**Comment by Rubanrubi** [comment]
same issue 
![image](https://github.com/themesberg/flowbite/assets/47156761/03d247ff-95d7-4199-abe4-d1df0143d03e)

**Comment by zoltanszogyenyi** [comment]
Hey @Rubanrubi @tawfikyassine,

Please make sure that you create a composable and you only import Flowbite this way:

https://flowbite.com/docs/getting-started/nuxt-js/#data-attributes

The client (aka. the browser) needs to be available so the document object is present.

Cheers,
Zoltan

**Comment by tawfikyassine** [comment]
Hi @zoltanszogyenyi and Thanks for you reply,
Im not using nuxt.js im using [inertiajs SSR](https://inertiajs.com/server-side-rendering) with laravel. I have done exactly what you mention and it is not working, i guess i will stick with the version to 2.3.0 for now :) as this version does not include the datepicker core.

### in laravel ressources/js

![1](https://github.com/themesberg/flowbite/assets/125127556/3209981e-7ab5-4343-9991-26ae74235499)

### in a component

![2](https://github.com/themesberg/flowbite/assets/125127556/dcfc882f-36e0-48c5-8303-8d923005a8c0)

### same error

![Capture d’écran 2024-07-04 120913](https://github.com/themesberg/flowbite/assets/125127556/4d5842ad-87cc-4058-a9ca-08bf6f935e8d)

**Comment by zoltanszogyenyi** [comment]
I've uodated the docs, please remove the `import initFlowbite` since it should be available already via the callback.

**Comment by Besufikad17** [comment]
> I've updated the docs, please remove the `import initFlowbite` since it should be available already via the callback.

I am getting `Cannot find name 'initFlowbite'` warning if I use `initFlowbite` without importing it.
