### ISSUE TITLE
SPAM blacklist false positive

### ISSUE THREAD

**Issue by Lexachoc** [themesberg/flowbite#923]
Hello @zoltanszogyenyi 

Today I found that I cannot access the Flowbite website:

```
{
"error": "Your IP address is a proxy connection and is associated with recent SPAM blacklist activity or abusive behavior."
}
```

Is this a false alarm? I bought a new router with a new Internet contract today and I am using its WLAN/wifi.

more info: gigacube from vodafone in Germany

**Comment by Lexachoc** [comment]
@zoltanszogyenyi Has the problem been solved or does the website bandwidth provider require more time?

I'm still seeing this error and cannot access the [Flowbite](https://flowbite.com/) website:
![image](https://github.com/user-attachments/assets/fbc69951-28c6-410e-8423-ba536eea3337)

But [Flowbite Reac](https://flowbite-react.com/) is always fine:

![image](https://github.com/user-attachments/assets/c1537341-7165-4f06-a3f9-881f5bd379a0)

**Comment by zoltanszogyenyi** [comment]
We use standard AWS spam detectors. Can you send over your IP via support (private) so we can whitelist it? Thanks.

**Comment by Lexachoc** [comment]
Thank you! I have sent via the contact form.
