### ISSUE TITLE
[NuxtJS] Unable to initiate Flowbite, document not found

### ISSUE THREAD

**Issue by ValentinRgt** [themesberg/flowbite#933]
**Describe the bug**
I'm currently unable to use Flowbite with NuxtJS 3 (latest), I get an error telling me datepicker document not found... okay, I just want to init Flowbite on my app nothing more.
I did my npm install flowbite and just followed this doc: [https://flowbite.com/docs/getting-started/quickstart/](https://flowbite.com/docs/getting-started/quickstart/)

**Screenshots**
![image](https://github.com/user-attachments/assets/a8905897-3d1d-477a-af22-8deced894272)

**Desktop (please complete the following information):**
 - OS: [Windows with WSL]
 - Browser [chrome]
 - Version [126.0.6478.182]

**Code**
app.vue
```
<script setup lang="ts">
  import { initFlowbite } from 'flowbite'

  onMounted(() => {
    initFlowbite();
  })
</script>

<template>
  <NuxtPage />
</template>
```

tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
    "./node_modules/flowbite/**/*.{js,ts}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('flowbite/plugin')
  ]
}
```

**Comment by zoltanszogyenyi** [comment]
Hey @ValentinRgt,

Please create a wrapper so the client is always available:

https://flowbite.com/docs/getting-started/nuxt-js/#data-attributes

This is also part of the guide.

Cheers,
Zoltan
