### ISSUE TITLE
Question: How can I inject data into a modal?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [themesberg/flowbite#935]
How can I inject data into a modal? Say I have a set of buttons:

```
<button 
   data-modal-target="default-modal" 
   data-modal-toggle="default-modal" 
   class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" 
   type="button">
  One
</button>
<button 
   data-modal-target="default-modal" 
   data-modal-toggle="default-modal" 
   class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" 
   type="button">
  Two
</button>
<button 
   data-modal-target="default-modal" 
   data-modal-toggle="default-modal" 
   class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" 
   type="button">
  Three
</button>
```
How can I inject data into the modal based on the button pressed?

**Comment by nitesh2920** [comment]
give class to all button example : modal-button (according to below implementaion)
Step 1: Create  a modal.
`
<div id="default-modal" class="modal hidden">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p id="modal-text">Default content</p>
  </div>
</div>
`

Step2 : use JavaScript to handle the button clicks, update the modal content, and show the modal.

`document.addEventListener('DOMContentLoaded', () => {
  // Select all buttons with the class 'modal-button'
  const buttons = document.querySelectorAll('.modal-button');

  // Select the modal and its content area
  const modal = document.getElementById('default-modal');
  const modalText = document.getElementById('modal-text');
  const closeModal = document.querySelector('.close');

  // Function to open the modal and set content
  const openModal = (content) => {
    modalText.textContent = content;
    modal.classList.remove('hidden');
  };

  // Function to close the modal
  const closeModalHandler = () => {
    modal.classList.add('hidden');
  };

  // Add click event listener to all buttons
  buttons.forEach(button => {
    button.addEventListener('click', () => {
      const content = button.getAttribute('data-modal-content');
      openModal(content);
    });
  });

  // Add click event listener to close button
  closeModal.addEventListener('click', closeModalHandler);

  // Optionally, close the modal if user clicks outside the modal content
  window.addEventListener('click', (event) => {
    if (event.target === modal) {
      closeModalHandler();
    }
  });
});
`

**Comment by CharlesIrvineKC** [comment]
Thanks
