### ISSUE TITLE
Add support for nextjs

### ISSUE THREAD

**Issue by chainerprince** [themesberg/flowbite#94]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I tried to use flowbite with nextjs. It failed bringing the error that document is not defined

**Describe the solution you'd like**
I would you to add support for nextjs

**Describe alternatives you've considered**
Consider making this framework friendly to server side rendered apps

**Additional context**

**Comment by volp99** [comment]
Hey @chainerprince !
A issue about Nextjs has already been opened and you can find here the topic https://github.com/themesberg/flowbite/issues/51#issuecomment-1000283380

**Comment by sgehrman** [comment]
same issue.

**Comment by yangyueche** [comment]
Just a quick note hope this helps. 
https://github.com/themesberg/flowbite/issues/51
After tracking down this issue, `import 'flowbite'` in _app.tsx/jsx works for me. 
The thing with flowbite-react is it can become hard to maintain if you need to customize the component. 
For more information, you can check out this page. 
https://flowbite-react.com/theme
