### ISSUE TITLE
the block code is in html

### ISSUE THREAD

**Issue by user4302** [themesberg/flowbite#952]
how can i get them in typescript?
similar to how the free files are available in the node modules folder?

edit:
or rather how can i use the exiting html to import them as blocks in sunce?

i want to do something like this:
(these are the free blocks from node_modules (just to test what im working on))
![image](https://github.com/user-attachments/assets/3be97fe8-2ec5-4c9c-9e41-651a203051ce)

**Comment by zoltanszogyenyi** [comment]
Hey @user4302,

If you have the pro version you can get the React/TS version from here:

http://flowbite.com/dashboard/downloads/

Specifically, they are called "React Blocks".

Cheers,
Zoltan
