### ISSUE TITLE
WYSIWYG:  When text is set to bold, it is no longer possible to set a color for it.

### ISSUE THREAD

**Issue by itsalongstory** [themesberg/flowbite#973]
https://flowbite.com/docs/plugins/wysiwyg/

**Comment by Jameslebron6** [comment]
I have fix the problem

**Comment by Jameslebron6** [comment]
I have pull this at the below link
https://github.com/themesberg/flowbite/pull/983

**Comment by Jameslebron6** [comment]
@qwjzka please review it and assign this issue to me

**Comment by zoltanszogyenyi** [comment]
It works now thanks to @Jameslebron6.

<img width="859" alt="Screenshot 2024-11-24 at 10 43 37" src="https://github.com/user-attachments/assets/114c1cc3-7625-496f-9ab1-dede0974e211">
