### ISSUE TITLE
javascript: reinit all events after DOMLoaded

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#98]
**Is your feature request related to a problem? Please describe.**
reattach events for all elements or single elements after DOMLoaded

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
i try re-dispatch DOMLoaded with this code
```
window.document.dispatchEvent(new Event("DOMContentLoaded", {
        bubbles: true,
        cancelable: true
    }));
```
but all exists elements not work after reinit

**Additional context**
-

**Comment by KinG-InFeT** [comment]
any update?

**Comment by zoltanszogyenyi** [comment]
Hello @KinG-InFeT,

We now load the event listener based on the window loaded event.

Is this issue still relevant?

Cheers,
Zoltan
