### ISSUE TITLE
update tailwindcss lib to latest version (now have 3.0.1) today 3.0.23 is out

### ISSUE THREAD

**Issue by KinG-InFeT** [themesberg/flowbite#99]

**Comment by zoltanszogyenyi** [comment]
Will update it for the next version after the JS refactorization.

**Comment by KinG-InFeT** [comment]
> Will update it for the next version after the JS refactorization.

ETA?

**Comment by zoltanszogyenyi** [comment]
2-3 weeks, but you can update Tailwind CSS in your own project since there are no breaking changes for Flowbite.

**Comment by HPODEV** [comment]
connected this issue/discussion : https://github.com/themesberg/flowbite/discussions/214
